### ISSUE TITLE
[ メディアとテキスト] モバイルで画像が上にはみ出す

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/lightning#1004]
[メディアとテキスト] ブロックで画面幅が狭くなり縦表示になったとき、画像が上にはみ出ます
左右余白も大きめな気がします
下記スクリーンショット(右) Twenty Twenty-One のように表示されると便利と思います

![mediatotext](https://user-images.githubusercontent.com/4631838/226283922-d1bf3f47-a3f0-4592-8150-f98239f7833a.jpg)

**Comment by sysbird** [comment]
[メディアとテキスト] ブロックをグループ化して余白を付けたので、見えるようになってしまったのかもしれません
グループ化しなければ目立たないです

**Comment by mtdkei** [comment]
マージされていたのでCloseします
