### ISSUE TITLE
G2: module_pageTit が二重で呼び出される

### ISSUE THREAD

**Issue by hinaloe** [vektor-inc/lightning#1005]
おそらく3年前から放置されていた問題のため今更かとは思うのですが、page-headerの旧ファイル名、module_pageTit.phpを子テーマで使用している場合、これが2回呼び出されてしまいます。

実際には、パンくずリストが読み込まれるべき部分でこれが読み込まれているようです。

原因としては、以下で `$old_file_name` を使いまわしてしまっているためです。

https://github.com/vektor-inc/lightning/blob/e9030e0cf4a209b99f9ef6feee8482e894b18dde/_g2/singular.php#L26-L27

尤も、locate_templateは配列で指定した優先順で選択するわけなので排列要素として新旧双方を持たせることも可能だったかもしれませんが、今更それはフックに破壊的影響を与えてしまうのでだめでしたね。

**Comment by kurudrive** [comment]
@hinaloe ふぁー、ご無沙汰です。お元気そうで何より！
なにか良い解決策があればプルリクいただければとは思いつつ、
もう結構経つのでみなさん手動でファイル名変更したりして対応済みだったりするからまぁいいかなとも...

**Comment by hinaloe** [comment]
（他にも同様の箇所ありそうですね。）

まあ流石に残ってないと信じて、該当箇所はいっそのことメジャーアップデートとして消してしまいつつ、マッチするファイルがある場合はどこかに警告出すのがいいのかもしれませんね。

また、未初期化配列への要素代入は禁止してしまったほうが安全（ドキュメントでも推奨されていない）かとおもうのですが、そういうルールセットが見当たらない……

**Comment by kurudrive** [comment]
@hinaloe こんな感じでOK（・ｗ・？

https://github.com/vektor-inc/lightning/pull/1009

**Comment by hinaloe** [comment]
> @hinaloe こんな感じでOK（・ｗ・？
> 
> #1009

ざっくりと対処としてはよさそうです、他のテンプレートでも同様の問題をはらんでいる箇所があったので `locate_template` してる箇所ほぼ全部にやってもよさそう。

**Comment by kurudrive** [comment]
あ、ほんまや、他にもあるな...まぁ過去に報告あったのはページヘッダーだけだけど一通り処理しておこう...。

**Comment by kurudrive** [comment]
対応済みclose
