### ISSUE TITLE
フッターのCopyRightのLightning Theme のリンク先が過去のURLになっている（404）

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#1007]
お客様からのお問い合わせもあり、優先度高にしました。

【誤】
https://lightning.nagoya/ja/
【正】
https://lightning.vektor-inc.co.jp/

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/942/files

**Comment by kurudrive** [comment]
@goutetsuguma ありがとうございます。今リリースしました！
_|＼○_ﾋｬｯ ε=＼＿○ﾉ ﾎｰｳ!!
