### ISSUE TITLE
「最新の投稿」の「続きを読む」のリンクが違う

### ISSUE THREAD

**Issue by eve24a** [vektor-inc/lightning#1053]
ExUnitのブロック「最新の投稿」で、投稿コンテンツの表示を「抜粋」にすると表示される「…続きを読む」のリンクが、対象の記事のリンクではなく、元の固定ページのリンクのままである。

**Comment by kurudrive** [comment]
ExUnit には 最新の投稿 ブロックはありません。
WordPress標準の 最新の投稿 ブロックの事でしょうか？

**Comment by kurudrive** [comment]
close : Lightning の問題ではないため
