### ISSUE TITLE
MountainLionのSafari（v6.2.8）でLightning Origin Proのヘッダー上部機能拡張のお問合せボタンが左にずれる

### ISSUE THREAD

**Issue by fujisunny** [vektor-inc/Lightning#106]
おつかれさまです。
MountainLionのSafari（v6.2.8）で見ると、Lightning Origin Proのヘッダー上部機能拡張のお問合せボタンが左にずれる事象が発生しました。

もし、改善できるようでしたら、お願いいたします。

**Comment by kurudrive** [comment]
ご報告ありがとうございます。
調査・修正いたしますので今暫くお待ち願います。

**Comment by kurudrive** [comment]
検討いたしましたがブラウザが古いためOriginProの製品自体での修正は対応が難しいです。
ただ、下記のCSSを外観→VK ExUnitのCSSカスタマイズに貼ればおそらく改善されるかと思います。
しかしながら、
.headerTop nav と headerTop .headerTop_contactBtn のwidthの値はご利用のサイトの文字数や項目数にあわせて対応ください。
~~~
@media (min-width: 992px){
.headerTop .container { display: table;width:1170; }
.headerTop .headerTop_description { width:auto; }
.headerTop nav { display:table-cell;width:150px; }
.headerTop .headerTop_contactBtn { display:table-cell;width:150px; }
}
~~~
何卒よろしくお願いいたします。

**Comment by fujisunny** [comment]
ありがとうございました。
きちんと右上に表示されるようになりました。
古いブラウザに対応していただき、ありがとうございます！

**Comment by fujisunny** [comment]
と思っていたら、電話番号が1行ほど上に表示されてしまうようです。
ウインドウサイズを変更すると、大丈夫なのですが。

「.headerTop nav と headerTop .headerTop_contactBtn のwidthの値はご利用のサイトの文字数や項目数にあわせて対応ください。」という部分だと思いますが、どのように変更すらばいいか検討がつきません😅

サイトは、
http://matsukawa-cruise.jp
なのですが、何かアドバイスが頂ければ幸いです。

**Comment by fujisunny** [comment]
上記の電話番号が1行ほど上にずれて表示されてしまう件は、「再読み込み」を行った時に発生するようです。

**Comment by kurudrive** [comment]
す、すみません、現行のSafariで表示崩れは発生しないので 、
旧Safariの環境もなく検証できない＆コストがかかるのでcloseとさせていただきます。
ご期待に添えず恐れ入ります。
