### ISSUE TITLE
lightningでスマホ表示にすると、smart slider 3プラグインの表示がメニューに重なってしまう。

### ISSUE THREAD

**Issue by fujisunny** [vektor-inc/Lightning#108]
lightningでスマホ表示にすると、メニューのところに、使用しているsmart slider 3プラグインのスライドがメニュー上に重なって表示されてしまいます。最初に表示させた時点では大丈夫なのですが、上下に移動したりして触っているとそうなります。

また、モバイル時のメニュー表示が、なぜか、横スライドしか選べなくなってしまいました。
（縦表示のチェック項目がない？）

よろしくお願いします。

なお、サイトはこちらです。
http://matsukawa-cruise.jp/

P.S.

http://forum.bizvektor.com/forums/topic/スマホでメニューを表示させると、smart-slider3のスライ/
でも書いていましたが、こちらにも、少し内容を補充して、書かせて頂きました。

**Comment by kurudrive** [comment]
スライダー自体を改善するためこちらはcloseさせていただきます。
https://github.com/vektor-inc/Lightning/issues/182
