### ISSUE TITLE
mobile-nav-menuのボタンアイコンが正しくエクスポートされない

### ISSUE THREAD

**Issue by BioBomber7** [vektor-inc/lightning#1081]
以下の環境でサイトを構築し、SimpleyStaticを使ってサイト全体を静的なページとして
エクスポートした時の不具合です。

・WordPress 6.3.1
・Ligtning 15.14.1
・SimpleyStatic 3.1.0

エクスポート時に「vk-menu-btn-close.svg」や「vk-menu-acc-icon-open-white.svg」などの
mobile-nav-menuに関連した画像ファイルが見つかりません。
しかし、WordPressが稼働しているオンライン上では正しく表示されていると思います。

原因を探るためにWordPressが吐き出したページのソースをチェックしました。
すると以下に示したインラインでCSSを記述している部分にアドレスの誤りと思われる部分が見つかりました。
``
```
<style id='lightning-common-style-inline-css' type='text/css'>
url("http://XXX.XXX.XXX.XXX/wp-content/themes/lightning/_g2/inc/vk-mobile-nav/package//images/vk-menu-btn-black.svg")

```
※imagesの前に/が２つある

これが原因でしょうか？
また対処は可能でしょうか？

**Comment by kurudrive** [comment]
ご報告ありがとうございます。おそらくそれが原因だと思います。
次のリリースで修正しますが、数日お時間をいただきたく思います。

**Comment by BioBomber7** [comment]
早速のご対応、誠にありがとうございます。
よろしくお願いいたします。

**Comment by kurudrive** [comment]
@BioBomber7 
おまたせしました。
15.14.2 で変更いたしましたのでご確認くださいませ。

**Comment by BioBomber7** [comment]
インラインでCSSが記述されている部分でのアドレスの修正は確認しました。
ありがとうございました。

ただ、残念ながら静的HTML出力時の不具合は改善しませんでした。
もしかしたら使用しているプラグイン「SimpleyStatic」側に原因があるかもしれません。

それから気になる部分がもう１箇所あります。
WordPressで生成されたHTML内で呼び出している以下のCSSファイルの中で、
相対パスで２つのSVGファイルを呼んでいます。

・SVGファイルを呼び出してる該当のCSSファイル
  /wp-content/themes/lightning/_g2/assets/css/common.css

・「common.css」ファイル内で記載されている問題のSVGファイルへの相対パス
  ../images/vk-menu-acc-icon-open-white.svg
  ../images/vk-menu-btn-close.svg

これにより、２つのSVGファイルはトップページからだと以下の絶対パスで見つけに行っているようです。

・http://XXX.YYY.ZZZ.AAA/wp-content/themes/lightning/_g2/assets/images/vk-menu-acc-icon-open-white.svg
・http://XXX.YYY.ZZZ.AAA/wp-content/themes/lightning/_g2/assets/images/vk-menu-btn-close.svg

※該当のSVGファイルは、/wp-content/themes/lightning/_g2/assets/cssをカレントディレクトリとしてアクセス？

こうなっているのでSVGファイルを見つけることができず、正しくエクスポートされません。
Lightning側の不具合という確証が持ていない状態での報告になりますが、よろしくお願いいたします。

**Comment by kurudrive** [comment]
@BioBomber7 とりあえず g2 を利用されているようですが g3 ではダメなのでしょうか？

**Comment by kurudrive** [comment]
※ 外観 > カスタマイズ > Lightning 機能設定 > Generation 3
※ 切り替えの際は必ずバックアップをとった上で行ってください。
※ 詳細は下記参照ください https://lightning.vektor-inc.co.jp/difference-free/

**Comment by BioBomber7** [comment]
ご対応＆ご助言、誠にありがとうございました。
g2からg3に変更したところ、今回の問題は発生しなくなりました。
誠にありがとうございました。
