### ISSUE TITLE
スマホ表示でのメニューの文字色について

### ISSUE THREAD

**Issue by nobu3855** [vektor-inc/Lightning#109]
Variety（ヴァラエティ）のスマホ画面でのメニュー文字色がグレー（灰色）で見にくいのですが白抜きに出来ないでしょうか？

**Comment by nobu3855** [comment]
追伸です、Varietyでキーカラーを青色（#1e73be）にした状態です。
スマホ表示と書きましたが　iPhone　で確認するとメニューの色は　黒　で文字色がグレーとなり標準の見え方なのですが　iPad等のタブレットで縦表示しますとメニューがキーカラーの色になってしまいます？PCで確認しましたらおおよそ　800～990ピクセルくらいの大きさの時この状態になります。
メニューの色が黒ならばまだ良いのですが明るめになると文字色がグレーですと見えにくくなってしまいます。
なんとか文字色を　白　に表示させる方法はないでしょうか？

**Comment by kurudrive** [comment]
症状確認いたしました。
申し訳ございません、前回のアップデート時の不具合でした。
只今修正作業を行なっており、本日中に修正版をアップ予定です。
ご迷惑をおかけして申し訳ございませんが今暫くお待ち願います。

**Comment by nobu3855** [comment]
当初、タブレットばかりで表示確認をしていたもので背景の標準が黒だと気がつきませんでした。
早々に対応いただき誠にありがとうございました。
