### ISSUE TITLE
サイトタイトルをBogoで翻訳できるように、lightning_get_print_headlogoを修正してほしい

### ISSUE THREAD

**Issue by webplant** [vektor-inc/lightning#1093]
template-tags.phpで定義しているlightning_get_print_headlogo関数について。

　
```
/**
 * Head logo
 *
 * @return string image tag or site name text
 */
function lightning_get_print_headlogo() {
	$options = get_option( 'lightning_theme_options' );
	if ( ! empty( $options['head_logo'] ) ) {
		$head_logo = apply_filters( 'lightning_head_logo_image_url', $options['head_logo'] );
		if ( $head_logo ) {
			return '<img src="' . esc_url( $head_logo ) . '" alt="' . esc_attr( get_bloginfo( 'name' ) ) . '" />';
		}
	}
	return get_bloginfo( 'name' );
}

```
`return get_bloginfo( 'name');`　
に第二引数に、'display'　を追加して

`return get_bloginfo( 'name' ,'display');`

のように変更してほしいです。

get_bloginfoは、第2引数の'display'がないと、フィルターが効かいないです。

File: wp-includes/general-template.php　を参照
https://developer.wordpress.org/reference/functions/get_bloginfo/

get_bloginfoにフィルターが効かないと、Bogoで翻訳したテキストを出力をできないので、よろしくお願いします。

**Comment by kurudrive** [comment]
@webplant 対応版リリースいたしました。アップデートの上ご確認ください。

**Comment by webplant** [comment]
@kurudrive 確認しました。ありがとうございます。
