### ISSUE TITLE
Variety（ヴァラエティ）でのBootstrapのCSS設定

### ISSUE THREAD

**Issue by nobu3855** [vektor-inc/Lightning#110]
ボタンを入れますと　文字色が反転（白ぬき）しません？

**Comment by kurudrive** [comment]
『ボタンを入れる』というのは具体的にどういう操作をした状態でしょうか？
例）
* どの部分にどんなコードを書いた
* どこぞこのウィジェットエリアに問い合わせボタンを設定した
* 本文欄下に問い合わせ情報を表示した
など

**Comment by nobu3855** [comment]
失礼いたしました、私の勘違いでし。
表示の確認をするために　デザイン要素サンプル　のページを
http://variety.lightning.nagoya/business-site/sample-design/
そのまま固定ページペーストして確認してみたところボタンだけ上手く表示されませんでした

ExUnit の「解説のページ制作に役立つ便利なCSS設定」のソースでやったら正常に表示されました
http://ex-unit.vektor-inc.co.jp/ja/about/class
お騒がせいたしました。

**Comment by kurudrive** [comment]
こちらは問題なかったとの事でcloseさせていただきます。
