### ISSUE TITLE
スマホでブラウザで開くと、editor画面のコンテナ幅が狭くなる(追記：フルスクリーンモードにしていない場合に狭くなる)

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#1104]
editor用のcssにスマホ用のコンテナ幅を追加する

おそらく左メニューの160pxがマイナスされているので（--vk-width-editor-container-body）、スマホサイズだとコンテナ幅が狭くなってしまうのかな？ちがっていたらすみません。。

https://github.com/vektor-inc/lightning/blob/88825a6afc0c8a317a502ead2e43fdc91868e689/_g3/assets/_scss/block/_block_editor_width.scss#L37-L44

![固定ページを編集-‹-デコボコノワ-でこぼこのわ-—-WordPress](https://github.com/vektor-inc/lightning/assets/5525368/5dce1660-8e71-4909-833b-1637185ad026)

**Comment by ChiakiKouno** [comment]
[なかしま様](https://docs.google.com/spreadsheets/d/1Yvk3AN4pWn2tjL7DBe0HZm4OvvWOWhfp9ub76bAjmpQ/edit#gid=1720129799&range=G9)より。

```
端末はwin11
ブラウザはchromeです
なかしま
```

**Comment by kurudrive** [comment]
フルスクリーンモードじゃない状態で利用している場合に発生する事が判明

**Comment by kurudrive** [comment]
なおしたん。
