### ISSUE TITLE
vk_PR Blocksの丸枠内アイコンがずれてしまう

### ISSUE THREAD

**Issue by bbchai** [vektor-inc/Lightning#111]
VK All in One Expansion Unit  バージョンを更新すると awesome iconが左上に小さく移動してしまい中央にきません。現在はバージョンを4.4.1にダウングレードして使用して正常です。テーマはLightningを使用しています。

**Comment by kurudrive** [comment]
Lightningのバージョンはいくつを利用していますか？
拡張スキンは何か適用されていますか？利用されている場合はバージョンはいくつを利用していますか？
ブラウザは何で確認されていますでしょうか？

**Comment by bbchai** [comment]
Lightningのバージョンは 3.0.0で子テーマを使用中です。拡張スキンは使用していません。ブラウザはIE・chrome共に前記のようになります。
よろしくお願い致します。

2017年1月20日 16:10 Hidekazu Ishikawa <notifications@github.com>:

**Comment by kurudrive** [comment]
うーん、おかしいですね。
確かに PR Blockの仕様変更の影響でバージョンの組み合わせによっては一時的に指摘の症状になる事はあったのですが、Lighnting及びExUnitが最新版なら問題は解消されているはずなので...
http://lightning.vektor-inc.co.jp/ja/

一番考えられるのは子テーマなのではないかなと思いますが、子テーマを解除して、ブラウザのキャッシュをクリアして確認してみてください。

**Comment by bbchai** [comment]
そうですよね。実は何度も試していまして子テーマ解除、キャッシュクリア、スマホでもwordpressにログインしてみても同じ状況なのです。気に入っているのでほんと改善できればなと思っていました。自己サイトと別のサイトも同じです。bizvektorからLightningにテーマ変更していまして。

**Comment by kurudrive** [comment]
うーん、こにURL張れる症状が出ているサイトありますかね？

**Comment by bbchai** [comment]
ほんと初心者なんでご迷惑をおかけして申し訳ありません。

プラグインを最新にしておきます。

サイトは
http://www.hoken-r.com/
です。

お手数をおかけ致します。

**Comment by kurudrive** [comment]
ExUnitの有効化設定でFontAwesomeを出力する設定になってるか確認してみてください。
なってたら外してください。

**Comment by bbchai** [comment]
外してあります。

**Comment by kurudrive** [comment]
プラグイン wc-shortcodes 停止してみてください？

**Comment by bbchai** [comment]
停止いたしました

**Comment by bbchai** [comment]
直ってます！

**Comment by bbchai** [comment]
色々とありがとうございました。Lightningテーマお気に入りでプラグインも機能満載でこれからも使い続けたいです！親身にご伝授頂き、感謝致します！

**Comment by kurudrive** [comment]
うーむ・・・そこでCSS負けるかぁ...
便利そうなプラグインなので、これはたぶん使いたいですよねー・・・
原因はわかりましたが、ちょっと今忙しいのと、
迂闊に対応すると他で弊害が出る可能性があるので後日改めて検討します。

**Comment by bbchai** [comment]
ありがとうございます。
