### ISSUE TITLE
【Forumから】【ヘッダー設定】ヘッダーレイアウトを中央揃えにしたときのロゴ画像のリンクエリアが横に広がっている

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#1113]
## 概要

https://vws.vektor-inc.co.jp/forums/topic/%e3%83%98%e3%83%83%e3%83%80%e3%83%bc%e3%83%ac%e3%82%a4%e3%82%a2%e3%82%a6%e3%83%88%e3%82%92%e4%b8%ad%e5%a4%ae%e6%8f%83%e3%81%88%e3%81%ab%e3%81%97%e3%81%9f%e3%81%a8%e3%81%8d%e3%81%ae%e3%83%ad%e3%82%b4

**Comment by kurudrive** [comment]
対応済み close
