### ISSUE TITLE
ボタンのhover時、ボタンが無効の場合は:not(:disabled)で除外する

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#1114]
https://vws.vektor-inc.co.jp/forums/topic/contact7%e3%81%a7%e8%a8%ad%e7%bd%ae%e3%81%97%e3%81%9f%e3%83%9c%e3%82%bf%e3%83%b3%e3%82%92lightning%e3%81%ae%e3%83%9c%e3%82%bf%e3%83%b3%e3%81%a8%e5%90%8c%e3%81%98%e8%a6%8b%e3%81%9f%e7%9b%ae%e3%81%ab#post-84532

**Comment by kurudrive** [comment]
close as completed
