### ISSUE TITLE
［ヘッダーレイアウト］ナビゲーション回り込みの時のロゴのリンクエリアが広い

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#1118]
### フォーラムより
[ヘッダーロゴがないところまでクリック可能になってしまう](https://vws.vektor-inc.co.jp/forums/topic/%e3%83%98%e3%83%83%e3%83%80%e3%83%bc%e3%83%ad%e3%82%b4%e3%81%8c%e3%81%aa%e3%81%84%e3%81%a8%e3%81%93%e3%82%8d%e3%81%be%e3%81%a7%e3%82%af%e3%83%aa%e3%83%83%e3%82%af%e5%8f%af%e8%83%bd%e3%81%ab%e3%81%aa)

-----
`.site-header-logo`部分の100%が原因だが、コメントアウトに以下の様にあるため、.site-header-logo部分を`width: fit-content;`にすると問題ある場合はaタグの方を調整するとよいのかもしれない。
  
            width:100%; // この指定がないとFlexでナビ部分の幅が余分になるためナビ項目に余分な左右余白ができる

https://github.com/vektor-inc/lightning/blob/eddc5587703548071e182a88e8aab8f8c0c808bf/_g3/assets/_scss/project/_site-header.scss#L85C1-L85C71

**Comment by kurudrive** [comment]
close as completed
