### ISSUE TITLE
VK_3PR や VK_PR Blocksやフッターなど、3つと決められているエリアについて

### ISSUE THREAD

**Issue by nnamm** [vektor-inc/Lightning#112]
2つ指定した場合、現状では3つ目のブロックが空白領域になります。これを横幅全体で指定した2つのコンテンツを表示するようにはできないでしょうか？
空き領域はない方が、見た目（特にPC画面）では良いと感じています。

**Comment by kurudrive** [comment]
ご意見ありがとうございます。
しかしながら、技術的に不可能ではありませんが、需要の割にソースコードが複雑化してしまい、構築工数・メンテナンス工数が現状の経営状態では捻出できないので現状では考えておりません。
ご期待に添えられずすみません。
貴重なご意見がりがとうございます。今回はご期待に応えられませんが、また何かございましたらよろしくお願いいたします。
※今後実装されるWordPressの新しいエディターではそのあたりのレイアウトも格段にやりやすくなるかと思います。
