### ISSUE TITLE
VKボタンを複数縦方向に並べると1つ目以外の余白がなくなる

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/lightning#1126]
## 現状
VKボタンを複数縦方向に並べると1つ目以外の余白がなくなります。この現象が起きるのは表示確認済みテーマが「Lightining」の時だけです。
![image](https://github.com/vektor-inc/vk-patterns/assets/21466284/f5d1fe4d-0660-48a7-a4a6-241250b01f54)

## 現象が確認できるURL
https://patterns.vektor-inc.co.jp/vk-patterns/%e3%83%9c%e3%82%bf%e3%83%b3%e7%a2%ba%e8%aa%8d%e7%94%a8/

## 原因と思われる部分
1つ目のVKボタンのCSSでは
.vk_button, .editor-styles-wrapper .vk_button {
    margin-bottom: 5px;
}
が効いているのですが
![image](https://github.com/vektor-inc/vk-patterns/assets/21466284/efef60cc-26d8-4d5c-9f7b-4dcd18991ca7)

2つ目以降のVKボタンのCSSでは
body .container .is-layout-flow>*+:where(:not(:is(h1,h2,h3,h4,h5,h6))), body .is-layout-constrained>*+:where(:not(:is(h1,h2,h3,h4,h5,h6))) {
    -webkit-margin-after: unset;
    margin-block-end: unset;
}
が効いているようでした。
![image](https://github.com/vektor-inc/vk-patterns/assets/21466284/1a3717ed-299b-43c6-b4bf-d30cceca4837)

## 確認したこと
- Lightninig以外の表示確認済みテーマのX-T9、TT3、TT4では、1つ目以外の余白もついている状態でした。
- Generation3 かつ theme.json を有効にする 状態で発生します。(Rickさんにご確認いただきました。)

**Comment by goutetsuguma** [comment]
margeされているのでClose
