### ISSUE TITLE
[リンク]下線がグレーのため見えない場合がある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/lightning#1128]
リンクの下線がグレー固定のため、グループの背景色が暗い場合に下線が見えず、リンク箇所がわからないときがあるっぽい

* 編集画面では見えている
「ウェブサイト」にリンクを設置
![link-1](https://github.com/vektor-inc/lightning/assets/4631838/148bf43c-2f61-4b13-a726-59341df01d17)

* フロントエンド
リンク箇所がわからない
![link-2](https://github.com/vektor-inc/lightning/assets/4631838/854bd330-e4c7-40e4-8cb9-92b3876547ab)

**Comment by mtdkei** [comment]
マージされましたのでCloseいたします。
