### ISSUE TITLE
ダッシュボード上のモーダル広告表示でセッション切断するので、function.phpで抑止する方法を教えてほしい

### ISSUE THREAD

**Issue by MCKK2024** [vektor-inc/lightning#1136]
2024年になってから、ダッシュボードページでVektor関連と疑われるモーダル広告がフェードイン・フェードアウト表示される際の影響としてセッション切断が生じています。

・他の会員制プラグイン動作不具合になるため、この事象は迷惑に感じております。
・応急策として、モーダル広告表示の影響でセッションを止めないよう
　function.php記述による抑止策があればご教示いただきたいです。
・別途LightningとVKプラグインから自作テーマへ切り替え動作検証したいのですが、
　自作テーマへの移行には工数がかかるため保留しております。

貴社でモーダル告知掲載を行っているか、また抑止方法はあるか
ご確認をよろしくお願いいたします。

**Comment by kurudrive** [comment]
> Vektor関連と疑われるモーダル広告がフェードイン・フェードアウト表示される

していません。

**Comment by MCKK2024** [comment]
ありがとうございます。他のプラグインが関係しているか確認いたします。
