### ISSUE TITLE
Lightning Varietyでのフロントページ2カラム表示

### ISSUE THREAD

**Issue by hicomal2016** [vektor-inc/Lightning#116]
Lightning Varietyで、フロントページを2カラム表示をしようとすると、サイドバーがメインカラムの下部に表示されてしまいます。フロントページ以外の固定ページでは、2カラム表示になっているようですが・・仕様でしょうか。

**Comment by kurudrive** [comment]
いえ、本来２カラムでも表示されます。
該当のURLを記載いただく事は可能でしょうか？

**Comment by hicomal2016** [comment]
http://handalawどっとjp/
です(「どっと」は「.」に変えてご入力ください)。
使用方法に誤りがあるのかもしれませんが、ご確認いただけると幸いです。

**Comment by kurudrive** [comment]
@hicomal2016 様

トップページに設定してある固定ページについて、恐らく「ランディング用テンプレートが」管理画面で選択されているのではないかと思いますので、デフォルトテンプレートに変更してみてください。

**Comment by hicomal2016** [comment]
ご教示いただいた固定ページをデフォルトテンプレートに変更したところ、2カラム表示ができました。
お手間をとらせてしまいました。
ありがとうございました。
