### ISSUE TITLE
［6.6-RC2］編集画面の幅によって画面にブロックが収まらず横スクロールが出ます

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/lightning#1160]
6.6で過去のパターンをいくつか確認したところ、どのパターンも画面幅によってコンテンツが横にはみ出してしまいました。
6.5.5では収まっています。

## 6.5.5
![スクリーンショット 2024-07-08 14 34 28](https://github.com/vektor-inc/lightning/assets/21466284/c1069ee9-d189-442d-a0ed-7bd8b68ebd42)
![スクリーンショット 2024-07-08 14 34 35](https://github.com/vektor-inc/lightning/assets/21466284/199214e4-097e-4232-942a-52636161118f)
![スクリーンショット 2024-07-08 14 34 55](https://github.com/vektor-inc/lightning/assets/21466284/a323d007-3124-4a3e-937f-ff2450eba20b)

## 6.6
![スクリーンショット 2024-07-08 14 36 54](https://github.com/vektor-inc/lightning/assets/21466284/3f6dd51f-1a09-4436-9c73-0627bd468644)
![スクリーンショット 2024-07-08 14 37 01](https://github.com/vektor-inc/lightning/assets/21466284/cc000af3-0b4e-4078-b26a-28f1b538a497)
![スクリーンショット 2024-07-08 14 37 14](https://github.com/vektor-inc/lightning/assets/21466284/57007e64-7358-4341-b0b4-2ec94ba5f844)

**Comment by goutetsuguma** [comment]
https://github.com/vektor-inc/lightning/pull/1163
↑ こちらの修正で6.6-RC-4 でLightning G3 と G2 確認しまして、治っているようでしたので、いったんCloseしますね
