### ISSUE TITLE
iPad9.7での表示不具合　Lightning Variety　Media Posts 　Vertical card 3 column

### ISSUE THREAD

**Issue by sssatonaka** [vektor-inc/Lightning#117]
環境：iPad pro9.7 safari、chrome　

iPadにてMedia Postsの「Vertical card 3 column」を使用すると表示が崩れます。
デモサイトでも表示が崩れておりました。
https://variety.lightning.nagoya/feature/lp/

**Comment by kurudrive** [comment]
@sssatonaka 様

こちらで確認する限りは特に異常なさそうなのですが、
「崩れる」というのは2列になるという事以外で表示がおかしくなるのでしょうか？

お手数ですがスクリーンショットの画像などどこかにアップいただけますと幸いです。

**Comment by sssatonaka** [comment]
kurudrive様

下記URLよりご確認お願いします。iosは10.2.1です。10.1.1でも同様の症状が見られました。
https://drive.google.com/file/d/0B-YqbfdQZiJfSFhOWWxYd001U1E/view?usp=sharing

9.7インチで横持ちです。縦の場合でも崩れます。

別件ですが、横持ちだとハンバーガーメニューが表示されず通常のナビメニューが表示されるので、その弊害で2回クリックしないとリンク先に飛べない現象が発生してしまいますね。
参考：https://hatamoto.biz/ios-841-hover-image-2clicks/
iosの不具合かそういう仕様になったのか分かりませんが・・・

タブレットのサイズも多様化してるのでヘッダーメニューのブレイクポイント対策だけでは漏れがでそうですね。

私は下記の記事を参考に対策しました。
https://kaminarimagazine.com/web/2016/11/29/ios-bug-using-hover-and-opacity/
スマートな対策じゃないので、良い方法があればいいですね。

**Comment by sssatonaka** [comment]
kurudrive様

もう一点、Media Posts についてですが、
画像サイズの異なるアイキャッチを指定すると高さが揃わないのですが、そのような仕様と思ってよいですか？
下記URLをご確認ください。
https://drive.google.com/file/d/0B-YqbfdQZiJfdzdDcGJvUU1RbGc/view?usp=sharing

WordPress 4.7.3　Lightning Varietyデフォルトの状態　プラグインはライトニングに必要なもののみです。

**Comment by kurudrive** [comment]
@sssatonaka 様

アイキャッチ画像のサイズに関しましては下記の記事を参照の上再生成するとキレイに揃います。
http://www.vektor-inc.co.jp/wordpress-tech/regenerate-thumbnails/

横レイアウトについては症状検証中です。

以上よろしくお願いいたします。

**Comment by kurudrive** [comment]
@sssatonaka 様

Vertical card 3 column について確認・修正版をDLmarketにアップいたしました。

**Comment by sssatonaka** [comment]
kurudrive様

対応ありがとうございました。

**Comment by kurudrive** [comment]
@sssatonaka 様
別途Safariで高さが揃わないなどの不具合もあり併せて修正いたしましたので、大変お手数ですが改めて最新版を適用くださいませ。
ご報告ありがとうございました。
今後ともLightningをよろしくお願いいたします。
