### ISSUE TITLE
編集画面：過去に作ったパターンで、全幅or幅広のカバーorグループブロックのインナーに設置したブロックがコンテンツ幅からはみ出す

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#1175]
新規で設置した全幅のカバーやグループブロックには`"layout":{"type":"constrained"}`属性がつくようでコンテンツ幅に収まります。
パターンの[Evergreenのパターン](https://patterns.vektor-inc.co.jp/?post_type=vk-patterns&pattern-product=evergreen&s=&supported-themes_operator=or&license-classification_operator=or&pattern-type_operator=or&pattern-industry_operator=or&pattern-category_operator=and&pattern-product_operator=or&demo-site_operator=or&vkfs_form_id=11755)が編集画面でインナーがはみ出していたので、パターンの方は`"layout":{"type":"constrained"}`を付与して、コンテンツ幅に収まるようにしました。

WPバージョン:6.5.5とLightningのバージョン: 15.21.1ではコンテンツ内に収まっているようですので、編集画面のcssの調整をしたときに変わったのかな？と思いましたが、違うかもしれません。

デモサイトのEvergreenの[トップの固定ページを編集画面](https://demo.dev3.biz/evergreen/wp-admin/post.php?post=2&action=edit)から、新しいバージョンの環境に設置すると症状が確認できます。

----
追記
終礼で共有したところ、仕様が変わり幅処理はわからない部分もあるので難しいかもしれないとのことでした。

**Comment by kaorock72** [comment]
WP6.6で確認していて症状が似ているパターンがあったため、コメント入れておきます...！

[ビジネス全般_CTA](https://patterns.vektor-inc.co.jp/vk-patterns/cta/)
ブロックテーマだと、全幅のカバーのインナーがコンテンツ幅からはみだしてしまうようです。
フロント・編集画面ともはみでる / Lightning だと問題なし
新規に設置した全幅のカバーだとインナーはコンテンツ幅を維持します。
https://github.com/vektor-inc/vk-patterns/issues/355#issuecomment-2259801129

**Comment by goutetsuguma** [comment]
> [ビジネス全般_CTA](https://patterns.vektor-inc.co.jp/vk-patterns/cta/)
> ブロックテーマだと、全幅のカバーのインナーがコンテンツ幅からはみだしてしまうようです。（「コンテント幅を使用するインナーブロック」が有効でないため）

@kaorock72 
確認ありがとうございます！同じ症状でした。
[ビジネス全般_CTA](https://patterns.vektor-inc.co.jp/vk-patterns/cta/)のパターンは、いったんカバーブロックに`"layout":{"type":"constrained"}`の属性を付与して対応しました!

**Comment by kaorock72** [comment]
@goutetsuguma 対応してくれてありがとうございます〜！

**Comment by goutetsuguma** [comment]
Evergreenのコンテンツデータは `"layout":{"type":"constrained"}`をつけて対応しましたので、一旦このissueはCloseしようかなとおもいます
