### ISSUE TITLE
リストブロックの色が勝手に変わっている

### ISSUE THREAD

**Issue by toshi2303** [vektor-inc/lightning#1176]
過去に書いた記事のリストブロックのリストマークとリスト文章の色が、いつの間にか勝手に全て変わってしまっています。たとえば、リストのマーク（水色)リストの文章（デフォルト黒）にしてたものは、すべて文章も水色になってしまっています。さらに、リストが数字形式の場合は、たとえば、リストの数字（水色）リストの文章（デフォルト黒）だったのに、全て色が逆転（数字が水色→黒、文章が黒→水色）となっています。非常に見にくくなってしまった部分が多々あり、急いで修正していますが、300記事近くあり大変困っています。ちなみに、最近書いた記事は問題ありません。また、あらためて色を修正して保存するとその通り保存されて問題ありません。Lightningの不具合なのか、他の要因なのかは断定できませんが、Lightningの可能性が非常に高いと思い報告することにしました。もし、Lughtningの不具合の場合は至急改善していただけると助かります。無料版のLightningなので強くはお願いできませんが、かなり困っているので、もし、Lughtningの不具合の場合はご検討お願いいたします。

**Comment by kurudrive** [comment]
該当のURLがないので症状が確認できません。

**Comment by toshi2303** [comment]
ありがとうございます。たとえば、https://ts-smartplan.com/?p=18480のページの冒頭の「この記事は〜」「この記事を読むことによって〜」のあとに続くリスト箇条書きの部分で、リストの印の色だけ黄色にし、箇条書き文章は黒だったのですが、いつの間にか文章まで黄色に変わっていました。過去に投稿したページはほとんど同じような状況です。いつからこうなったのかはわからないのですが、おそらく最近だと思います。ちなみに最新のlightningへのアップデートとかは怠っておりません。変わったプラグインなども使っていません。

**Comment by kurudrive** [comment]
確認しました。
おそらく外部プラグインの影響が高いと思います。
特に高速化関連のプラグインを停止してご確認くださいませ。

サポートにつきましては現状ライセンス購入の方及びプライベートサポートのユーザー様の対応がたまっておりますので、そちらを優先しないと課金ユーザーの皆様に筋が通りませんので恐れ入りますがこれ以上はご容赦願います。

**Comment by kurudrive** [comment]
VK Blocks 側で対応

**Comment by toshi2303** [comment]
お忙しい中ありがとうございます。プラグインが干渉しているんですね…。プラグインの停止をいろいろやってみます。ありがとうございました！

**Comment by kurudrive** [comment]
該当箇所は VK Blocks の機能で、VK Blocks 側で確認・修正作業をおこなっていますので今しばらくお待ちください。

**Comment by toshi2303** [comment]
ありがとうございます！
