### ISSUE TITLE
/themes/lightning/_g3/_g3/plugin-support/woocommerce/css/woo.css が 404 not found

### ISSUE THREAD

**Issue by waviaei** [vektor-inc/lightning#1178]
マルチサイトにて、WooCommerce を有効化している環境です。ブロックエディターを開いている時に、Developer Tools のコンソールタブでエラーを確認しました。

```
GET https://tennis.jp/wp-content/themes/lightning/_g3/_g3/plugin-support/woocommerce/css/woo.css?wp-mce-49110-20201110 net::ERR_ABORTED 404 (Not Found)
```

このロードをトリガーしていた JS ファイルはコアの TinyMCE Advanced に含まれているJSファイルでした。

- TinyMCE Advanced がロードしようとしているということは、エディター用のスタイルファイルでは？
- `/_gp3/_gp3/` というディレクトリは存在しない。`/_gp3/` の誤りでは？

上記2点から探したところ、下記コードの引数に指定してあるパスの冒頭の `/_gp3/` が原因のようです。

https://github.com/vektor-inc/lightning/blob/ee598c017372adac3247cc77d5ac275412beb1c9/_g3/plugin-support/woocommerce/functions-woo.php#L36

実際にパスを `/plugin-support/woocommerce/css/woo.css` に変更するとエラーは解消されました。

**Comment by kurudrive** [comment]
@waviaei ふぁー！ありがとうございます！
来週中には修正版リリースいたしますー (￣人￣)

**Comment by kurudrive** [comment]
@waviaei おまたせしました！修正版 15.26.3 リリースしました！

**Comment by waviaei** [comment]
@kurudrive ありがとうございます！修正版で修正を確認しました！

**Comment by kurudrive** [comment]
_|＼○_ﾋｬｯ ε=＼＿○ﾉ ﾎｰｳ!!
