### ISSUE TITLE
Lightning の編集画面で投稿リストブロックのメディアレイアウトが編集画面で崩れているのでなおしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#1183]
![スクリーンショット 2024-10-01 9 55 36](https://github.com/user-attachments/assets/66716e20-84cf-41ac-93fe-9d95e35fd5a6)

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kurudrive** [comment]
close as completed
