### ISSUE TITLE
[編集画面] グループのパディング設定で数値の入力欄が狭い

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/lightning#1184]
グループのパディング設定などで 数値欄が狭くて見づらい場合がある
選択できる単位のなかに文字列が多いの(dvmaxなど長い単位)があるため そのぶん数値欄が狭くなっている
*  theme.json 有効時
![padding-unit](https://github.com/user-attachments/assets/0599aa68-b3f9-4d98-9e7d-5672dcb16972)

**Comment by sysbird** [comment]
テーマで対応、編集画面ようのスタイル追加

**Comment by kurudrive** [comment]
マージ・リリースしましたん！
ありがとうございました。
