### ISSUE TITLE
[WP 6.7] カスタマイズ画面の左サイドバーの間隔が空きすぎてる

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/lightning#1188]
![WP-67-theme-customize](https://github.com/user-attachments/assets/304f33b2-597b-486f-a8a9-eac6f9d2c8bf)

クラシックテーマでも他のは問題ない

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by goutetsuguma** [comment]
とりさん確認ありがとうございます、こちらの件と同じかもしれません。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1143#issuecomment-2475156416
私の場合は masterブランチでプルして最新のLightning と最新のvk-all-in-one-expansion-unit で確認したところカスタマイズ画面が正常に戻りました。

**Comment by kurudrive** [comment]
こちらもう発生しないと思いますので close します。
また発生していましたら open してください (￣人￣)
