### ISSUE TITLE
トップページビジュアル下に貫通のウィジェットエリアを追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/Lightning#121]

**Comment by kurudrive** [comment]
時代はブロックなのでclose

**Comment by rick-addison** [comment]
現状ブロックの支配領域は the_content() 内なので、
ウィジェットエリアは増やしたほうがいいかもしれません。

ウィジェットエリアを設ける利点は１度設置してしまえば
設置の仕方次第では違う記事でも、違う投稿タイプでも
同じものを表示できるという点にメリットがあります。

まあ、後々ブロックエリアと名前を変えて
ブロックを設置できるエリアに変わるかもしれませんが・・・

**Comment by kurudrive** [comment]
エリアを増やす事は瞬殺なのですが、デザインスキンによって枠ありと枠なしが存在して（Charmなど）、
じゃぁウィジェットエリアを元からある枠の中に入れるのか独立した枠にするのかとか、ウィジェットの前後に余白を入れたほうがいいのか悪いのかなどが絡んできて、
余白無しにすれば「余白がなくくっついてしまう」と言われて余白を入れれば「余白なく要素をくっつけたい」という人が出てきたりで、調整に精神が削られるけれど、直近の見出しデザイン変更機能もそうですが、実装は楽そうでも後々のメンテナンス・調整コストが結構かかるけれど、
ブロックでウィジェット相当の機能は年内にほぼ揃うし、余白は好みに応じてスペーサーブロックで調整可能になるので、この部分のウィジェットエリアは見送ろうと思います。
Gutenbergの最新プラグインを見る限りウィジェットもブロックも扱いがごちゃごちゃになっていきますしね...

**Comment by rick-addison** [comment]
記事のあるカラムの部分にウィジェットを追加するのは難しそうですね・・・

スライドショーの真下あたり（２カラムに分割される前）にウィジェットエリアを設置して、Advanced Slider と同等の機能を持ったウィジェットを Ex Unit に追加して、
そこにスライドショーを追加するように仕向けるのはいかがでしょうか？

BS3版とBS4版の両方に適合するように Advanced Slider を調整するよりは、
（Advanced Slider を有効化した状態でBS4版のスキンを選択するとスライドショーの下部に余計な余白ができてしまいます。）
BSに依存せず Swiper にのみ依存するスライドショーウィジェットを設けたほうが
メンテナンスも簡単になりそうな気がしますが。

**Comment by kurudrive** [comment]
いや、実はBS版でフェード機能は追加したので、Advanced Slider は廃止しようかと思っています。
Swiperを別読み込みだとその分遅くなるから、Bootstrapにそこそこの機能が備わってるのでそれでいいかなと...
あ、ショートコードでは使えるようにしようと思ってます。
で、今トップページのみの利用を想定してますが、複数のスライドセットを作れるようにするにはまた構造変更しないといけないので、そこは推定１０月〜１１月頃の対応になるかなと。

**Comment by rick-addison** [comment]
なるほど、了解しました。
ウィジェットが欲しかったら各自で設定しろということですね。
（↑そこまではいっていないかもしれませんが）
そこらへんについての勉強会を開くのもありかもしれませんね。
需要は多少はあるようですし。
https://vws.vektor-inc.co.jp/forums/topic/%e3%82%a6%e3%82%a3%e3%82%b8%e3%82%a7%e3%83%83%e3%83%88%e3%81%ae%e3%83%88%e3%83%83%e3%83%97%e3%83%9a%e3%83%bc%e3%82%b8%e3%82%b3%e3%83%b3%e3%83%86%e3%83%b3%e3%83%84%e3%82%a8%e3%83%aa%e3%82%a2%e4%b8%8b

https://vws.vektor-inc.co.jp/forums/topic/%e3%83%88%e3%83%83%e3%83%97%e3%83%9a%e3%83%bc%e3%82%b8%e3%81%ae%e3%82%b3%e3%83%b3%e3%83%86%e3%83%b3%e3%83%84%e3%82%a8%e3%83%aa%e3%82%a2

**Comment by kurudrive** [comment]
BS4版以降は以下で可能になります。
```
function my_add_widgets_area_slide_after() {
	register_sidebar(
		array(
			'name'          => 'トップページスライドショー下',
			'id'            => 'front-slide-after-widget-area',
			'before_widget' => '<div class="widget %2$s" id="%1$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h2 class="mainSection-title">',
			'after_title'   => '</h2>',
		)
	);
}
add_action( 'widgets_init', 'my_add_widgets_area_slide_after' );

/**
 * トップページスライドショーの下にウィジェットエリアを表示
 * @return [type] [description]
 */
function my_print_widget_front_top_area() {
	if ( is_front_page() && is_active_sidebar( 'front-slide-after-widget-area' ) ) {
		echo '<div class="col-md-12">';
		dynamic_sidebar( 'front-slide-after-widget-area' );
		echo '</div>';
	}
}
add_action( 'lightning_siteContent_container_prepend', 'my_print_widget_front_top_area' );
```
