### ISSUE TITLE
varietyでのページ内リンクがずれる問題

### ISSUE THREAD

**Issue by sssatonaka** [vektor-inc/Lightning#123]
varietyにてページ中断へのページ内リンクをおこなった場合、ヘッダー固定の関係でずれが発生します。

下記のようにCSSで設定しましたが、ヘッダーの動作が不安定になります。

#link01 {
   margin-top:-54px;
  padding-top:54px;
}

良い解決方法がありましたらお教えください。

**Comment by kurudrive** [comment]
『ヘッダーの動作が不安定』というのはどういう事でしょうか？

**Comment by sssatonaka** [comment]
下記画像のように、ブラウザごとで動きが異なります。

![111](https://cloud.githubusercontent.com/assets/26642917/26659636/108b3110-46ad-11e7-8e7e-c1a5e7aab02e.jpg)

**Comment by kurudrive** [comment]
ExUnit の スムーススクロール機能で解消済みにてCloseします。
