### ISSUE TITLE
Bizvektorフォーラムにログインできません

### ISSUE THREAD

**Issue by mwanko** [vektor-inc/Lightning#128]
すみません、どちらで質問したらいいのかわからず、こちらをお借りします。
WordpressテーマのLightningについて質問したく、フォーラムにログインしようと思いましたが、「ログイン」ページに入ってもログインできるボタン等が見つかりません。
PCからもスマホからも入ろうとしましたが、見当たりませんでした。
フォーラムで質問するにはログインしなければならず、Lightningテーマのページでは個別の問い合わせを受け付けていないため、どうすればいいのかわかりません。
下記のリンクなのですが、皆さんはどのようにしてフォーラムにログインされているのでしょうか。
http://forum.bizvektor.com/register/
こちらで質問すべき内容ではないかも知れませんが、どなたかご存知でしたら教えていただけると大変助かります。
よろしくお願いいたします。

**Comment by kurudrive** [comment]
すみません、修正しました（汗）
http://forum.bizvektor.com/wp-login.php
http://forum.bizvektor.com/wp-login.php?action=register
