### ISSUE TITLE
固定ページの各種ボタンが無効になる

### ISSUE THREAD

**Issue by kosnet** [vektor-inc/Lightning#137]
Lightningをテーマに設定し、プラグインでLightning Varietyを有効にすると
固定ページ編集のパーマリンクの編集ボタンや
【b】【i】【link】などの各種タグ挿入ボタンが非表示になってしまう。

プラグインを停止すると問題なく表示されます
対応策などあればご教授お願い致します。

wordpress
バージョン4.8

Lightning
バージョン: 3.1.1

Lightning Variety
バージョン 2.0.7 
--

**Comment by kurudrive** [comment]
現状確認する限りではボタンが非表示になるという症状は確認出来ないので、
一旦クローズとさせていただきますが、現状の最新版でも症状が発生しているようでしたら再度コメントくださいませ。
