### ISSUE TITLE
[ トップページスライドショー ] 画像のモバイル用スライド画像が表示されない

### ISSUE THREAD

**Issue by takanashicompass** [vektor-inc/Lightning#146]
カスタマイザーで登録したモバイル用のトップページスライドショー画像が表示されません。生成されたソースにも反映されていません。デザインスキン「Charm」を利用しています。
ご対応いただけると助かります。よろしくお願いいたします。

Wordpress　バージョン: 4.8.1
Lightning　バージョン: 3.4.1
Lightning Advanced Unit　バージョン: 2.4.1 
VK All in One Expansion Unit　バージョン: 5.6.0 
Lightning Skin Charm　バージョン: 2.0.5

**Comment by kurudrive** [comment]
確認は実機でされていますでしょうか？
端末判定をしていますので、PCのブラウザで画面を狭くしているだけの場合はモバイル画像にはなりませんので念のためご確認くださいませ。

あと、Charmは 最新が 2.1.0 になりますので、DLmarketより最新版をDLしてご確認くださいませ。

以上よろしくお願いいたします。

**Comment by takanashicompass** [comment]
PCのシミュレーターで検証していました。
以前、実機検証のときは大丈夫だったのを失念していました。
ありがとうございました。
