### ISSUE TITLE
カスタマイザーで保存できなくなる時があります

### ISSUE THREAD

**Issue by takanashicompass** [vektor-inc/Lightning#147]
たびたびすみません。
カスタマイザーで時々、『保存して公開』ボタンが反応しなくなります。
内容を編集してクリックしても『保存しました』ボタンになりません。
一旦ダッシュボードの他の画面に遷移し、カスタマイザーに戻ると反応するようになることがあります。
ご確認をお願いいたします。

Wordpress　バージョン: 4.8.1
Lightning　バージョン: 3.4.1
Lightning Advanced Unit　バージョン: 2.4.1
VK All in One Expansion Unit　バージョン: 5.6.0
Lightning Skin Charm　バージョン: 2.1.0

**Comment by kurudrive** [comment]
おそらく画像関連のウィジェットなどで、画像を変更しても反映されないなどの問題ではないかと思われます。VK All in One Expansion Unit の 5.7.0 で改善いたしましたので一度ご確認ください。
