### ISSUE TITLE
Lightning3.4.0でPC表示は問題ないが、スマホ表示が崩れる

### ISSUE THREAD

**Issue by okubo3** [vektor-inc/Lightning#148]

**Comment by okubo3** [comment]
素人で失礼します。PCで問題ないのですが、スマホではスライドショーや３PR、VK　Blockなど表示されず、ブログも記事がそのまま羅列されてしまいます。どのような対応をしたらよいかわからず、ここに記載致しました。よろしくお願いいたします。
http://okubo3.com  です。

**Comment by kurudrive** [comment]
AMPのプラグインを有効化しているので、AMP頁になっていますが、Lightningでは現在AMP対応はまだ作業中で配布されているリリース版にはAMP用のテンプレートが入っていません。
よってLightningで指定したデザインは適用されない状態となっています。
AMP&現在のデザインのまま暫く運用いただくか
AMPプラグインを停止してLightningのデザインにするかの選択になるかと思います。
Lighting側でのAMP対応はなるべく早く対応したいと考えております。遅くとも年内には対応したいと考えております。
以上よろしくお願いいたします。

**Comment by okubo3** [comment]
ご連絡ありがとうございます。AMPのプラグインは入れていないのですが、Jetpackをいじって、設定される様なことは考えられますでしょうか？AMPは外したいのですが、どうしたら良いか分かりません。場違いかと存じますが、良いスポットコンサルなど有ればご教授いただけると幸いです。

大久保 iPhoneから送信

2017/10/11 11:13、Hidekazu Ishikawa <notifications@github.com>のメール:

**Comment by okubo3** [comment]
Jetpack変更で直りました。ありがとうございます。

iPhoneから送信

2017/10/11 11:13、Hidekazu Ishikawa <notifications@github.com>のメール:
