### ISSUE TITLE
トップページのスライドショー上の見出し・キャプション・リンクボタンがモバイル表示で小さすぎる

### ISSUE THREAD

**Issue by pcjmasui** [vektor-inc/Lightning#164]
新しい機能でトップページのスライドショー上に 見出し・キャプション・リンクボタン・カバーカラー が設定出来るようになったとのことですが、モバイル表示の際文字が小さすぎて、キャプションリンクボタンは可視性がかなり低いです。改善をお願い致します！

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/Lightning/commit/e87a74e5e037c44cb63b28639b8748d106dadfbd

**Comment by kurudrive** [comment]
@catherine87 
https://github.com/vektor-inc/Lightning/commit/e87a74e5e037c44cb63b28639b8748d106dadfbd
の _slide.scss の修正箇所について、
@media (max-width: 767px){
}
指定で追加してあるが、基本的には
1.モバイルサイズ
2.@media (min-width: 768px){
3.@media (min-width: 992px){
のように小さいサイズ用から順に記述する。
案件によっては大きい方から書く事もあるが、Lightningは小さいサイズから書くので、
後から @media (max-width: 767px){ というような指定をするのではなく、40行目あたりの数値を変更する。

そして、もとが 1.7vw だったのに対して、4vwに変更しているので、実際にモバイルサイズで見ると文字が大きすぎてはみ出す感じになってるので、再調整よろしくお願いいたします。

**Comment by catherine87** [comment]
@kurudrive 
「そして、もとが 1.7vw だったのに対して、4vwに変更しているので、実際にモバイルサイズで見ると文字が大きすぎてはみ出す感じになってるので、再調整よろしくお願いいたします。」

=>前回一度相談させてもらったのですが...これって高さ（縦幅）の話ですよね？
元の1.7だとしても一定の長さ(こまめに改行したり)を超えると見切れちゃうので、そこはスマホ用の画像を必ず設定してもらうっていう条件にして、可視性重視でこのサイズで大丈夫ですか？って相談させてもらってそのまま流れちゃってた感じです...

こういう場合はどうやって調整するのが適切ですかね？
