### ISSUE TITLE
改善の要望

### ISSUE THREAD

**Issue by takanashicompass** [vektor-inc/lightning#174]
多機能で軽く、大変利用しやすいテーマで重宝しています。
下記についてご検討いただければ幸いです。

1. single.phpのページネーション
　同カテゴリー内の投稿ページのみにしていただけるとありがたいです。
　現状、子テーマでテンプレートファイルを作成するか、非表示にするようにしています。

2. 子ページのh1
　固定ページでは、ページのタイトルがh1(page-header_pageTitle)となる仕様ですが、
　親ページがある子ページの場合は、親ページのタイトルを表示するようにできないでしょうか。
　現在は、子テーマでmodule_pageTit.phpを作成して対応しています。

既に実装済みでしたら見落としているのかも知れませんので、その旨ご回答いただけると助かります。
よろしくお願いいたします。

**Comment by kurudrive** [comment]
Lightning G3 Pro Unit で実装済み close
