### ISSUE TITLE
インターネットエクスプローラーie10でのグローバルナビ、子ページ一覧の崩れ

### ISSUE THREAD

**Issue by wasabinakagawa** [vektor-inc/Lightning#177]
Lightning Variety
（originでも)
を使用していますが、IE10の環境下だとグローバルナビゲーションが横にはみ出てしまう、子ページ一覧の枠や文章画像がくずれておかしくなります。
下記デモサイトでも同じ現象になります。
http://variety.lightning.nagoya/feature/

改善及び解決法をお教え下さい。

**Comment by kurudrive** [comment]
恐れ入りますがIE10には対応しておりませんのでcloseとさせていただきます。
