### ISSUE TITLE
Lightning Fortの「ExUnit 設定」-「お問い合わせ情報」メニューについて

### ISSUE THREAD

**Issue by nisi1134** [vektor-inc/Lightning#178]
▼お問い合わせバナー画像／お問い合わせ情報として表示するHTMLについて
「外観」-「カスタマイズ」‐「ExUnit 設定」‐「お問い合わせ情報」メニューにて、以下が設定されている場合は優先表示されるようですが、バナーやHTMLを設定しても何も表示されません。

・お問い合わせバナー画像
・お問い合わせ情報として表示するHTML

Lightning Fortのclass-header-contact.phpのlightning_header_contact_html関数を見ても上記のオプション設定

・お問い合わせバナー画像 → $options[contact_image]
・お問い合わせ情報として表示するHTML → $options[contact_html]

に関する表示判定のロジックが書かれていないようです。

▼メッセージ／電話番号／営業時間などの初期設定について
初期設定の状態でお問い合わせ情報のオプション設定（メッセージ／電話番号／営業時間）をデバッグ出力しても$optionsは空のようです。
ですから、初期設定の「お気軽にお問い合わせください。」をそのまま使おうと思っても、いったんテキストを変更して$optionsに格納しないとヘッダー右側の連絡先には表示されません。

また、$optionsに何も入っていないので、初期設定の内容では（サンプルとしての）連絡先や問い合わせボタンが表示されません。

以上、こちらの勘違いでしたら大変申し訳ありませんが、よろしければご確認をお願いできませんでしょうか。

**Comment by kurudrive** [comment]
あぁ....
なるほど...
ExUnitのお問い合わせ情報を画像やHTMLで上書きする機能は、固定頁下部などに表示される部分（ https://demo-ja.lightning.nagoya/ の画面下部 シェアボタン上）の書き換え用機能で、
Fort の ヘッダー上部に電話番号・問い合わせボタンを書き換えるという事は想定していませんでした。
現状Fortのヘッダー連絡先情報が画像やHTMLにならないのは仕様です。
しかしながら現状の入力画面の見る限りではFortのユーザーからすると @nisi1134 様のように 「あれ？」と思われるかと思いますので、対策を検討したいとは思いますが、
先述の通り、書き換え機能は固定頁下部などに表示されるお問い合わせ情報を想定しているので、そこに表示させるものとヘッダーに表示されるものはサイズ的に同じになってしまっては無理が出るので、
ちょっと仕様を検討します。
ご報告がりがとうございます。

**Comment by nisi1134** [comment]
ご連絡ありがとうございます。
そのような使い方だったのですね。わかりました。

**Comment by nisi1134** [comment]
「お問い合わせ情報として表示するHTML」にHTML（divタグなど）を入力してみましたが、タグがそのまま表示されてしまいました。

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/VK-All-in-One-Expansion-Unit/pull/291/commits/21b54a286da02d0e07107eda8432f5d9daa14b9f

**Comment by kurudrive** [comment]
ありがとうございます。
修正いたしました。
