### ISSUE TITLE
薄い背景色を選んだときの文字色が反転すると良いのでは？

### ISSUE THREAD

**Issue by jjiijjii** [vektor-inc/Lightning#18]
.page-header, .btn-primary などに設定できるカラーリングは、今のところ濃い色が使われることを前提に構築されていると思います。たとえば16進数のカラーコードのうち、平均値が8を超える色を使った場合は、文字の色を白黒反転できると親切ではないかな、と思いました。優先度は低い要望として、お考えいただければ幸いです。

**Comment by kurudrive** [comment]
地味ーにハードルが高いのですみません...
