### ISSUE TITLE
新しいユーザーを追加する際、パスワードが入力できない

### ISSUE THREAD

**Issue by tomohiro5525** [vektor-inc/Lightning#180]
新しいユーザーを追加する際、画像のようになってしまいパスワードが入力できないです。
環境はmacOS High Sherra , ブラウザはsafari いずれも最新です。Google chromeでも同じ症状が起きます。
<img width="644" alt="screen shot 2018-02-26 at 1 18 21" src="https://user-images.githubusercontent.com/36819713/36643715-f8305dce-1a92-11e8-8c73-9336351a6476.png">

**Comment by kurudrive** [comment]
[ パスワードを表示 ] ボタンをクリックしてください。
