### ISSUE TITLE
新しいユーザーを追加する際、パスワードを表示をクリックしても何も起こりません

### ISSUE THREAD

**Issue by tomohiro5525** [vektor-inc/Lightning#181]
新しいユーザーを追加する際、画像のようになってしまいパスワードが入力できないです。
パスワードを表示をクリックしても何も起こりません。ユーザー名等入力した後にパスワードを表示をクリックしても同じです。
環境はmacOS High Sherra , ブラウザはsafari いずれも最新です。Google chromeでも同じ症状が起きます。
windows10でも行いましたが同じです。
<img width="644" alt="screen shot 2018-02-26 at 1 18 21" src="https://user-images.githubusercontent.com/36819713/36678363-e169df36-1b53-11e8-9e7c-c99e4e04bd58.png">

**Comment by kurudrive** [comment]
各ブラウザにて [ パスワードを表示 ] をクリックして反応しないなら、WordPress自体が正しくインストール出来ていないか、何かのプラグインがJSのエラーを吐き出しているかもしれません。
プラグインを全て停止して確認してください。

あるいはテーマも他のに変更して試してください。

それでもダメなら他のサーバー環境で確認してください。

それでもだめならそのまま新規ユーザー登録をしてて、登録したユーザーアカウント宛に届いたメールをクリックしたらパスワード設定画面が表示されるのでそこからパスワードを設定できます。
