### ISSUE TITLE
FontAwesome4 からFontAwesome5 へのバージョンアップ

### ISSUE THREAD

**Issue by catherine87** [vektor-inc/Lightning#191]
■バージョンアップによる変更点
★参照
https://qiita.com/tamaina/items/4a0747bf20296e0aab15

---
* JavaScriptとSVGによる描画が新たに追加されました。今バージョンではこれが推奨
* faプレフィックスに代わり、種類ごとのプレフィックスfas,far,fal,fabに変更
---

■バージョンアップ手順
★参照
https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes-complete-list

---

１．プロジェクトからFont Awesome Version 4に関連するファイルを削除
２．<head>からFont Awesome V4のJSまたはCSSへの参照を削除
３．FA5を使用するあなたの方法を選び、ファイル読み込み
４．バージョン4と5の間で異なる名前を持つアイコンを検索して置き換え
（アイコン名変更完了リストがあるのでそれを元に記事を作成して公開。自力で変更してもらう）
５．Font Awesome 5 Freeで疑似要素(:after,:before)のcontent指定する場合の対応（CSS）
-> https://qiita.com/Garyuten/items/6d68da5cdac6dab9ba26

---

■埋め込み js について
★参照
https://fontawesome.com/get-started/svg-with-js

---

```
<head>
  <script defer src="/static/fontawesome/fa-v4-shim.js"></script>
  <!--your other font awesome references-->
</head>
```

---

**Comment by catherine87** [comment]
@kurudrive 

こんな感じでバージョンアップに関して進めれば、あまりトラブルなくいけるかなーっと思っていますーm(_ _)m

**Comment by kurudrive** [comment]
@catherine87 ありがとう。たぶんウチの場合利用者が多くて利用状況が人それぞれだから結局両方のバージョンを切り替えられるようにしないと厳しいかなー。
ExUnit内で使ってるアイコンのクラス名もバージョンで切り替えたりしないといけないかぁ....
はふー。
今からチマチマやりまする（・ｗ・；

**Comment by catherine87** [comment]
@kurudrive 

カスタマイザー上でラジオボタンとかで「４」か「５」を選択できるようにするみたいな感じですか？

アイコンのクラス名は、末が「xxx-xxx-o」じゃないものは変更しなくても表示されますみたいな記事も見ましたけど定かではないし、いずれ完全移行のときがくると思われるので今回対応しちゃったほうが後々楽かなーと思います(´_　_｀)
