### ISSUE TITLE
VK Mobile Nav で子メニューを多く作った場合下部が表示されない。

### ISSUE THREAD

**Issue by 53rd** [vektor-inc/Lightning#192]
子メニューを15個ほど作ったら、スマホ表示する際に１0個めくらい以下の子メニューが、下の親メニューと重なって表示されません。

http://nakaku.biz

改善方法はありますでしょうか。

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/lightning-advanced-unit/commit/d133d92eb76477e4abcb2352c2b0ae94771b589c

**Comment by kurudrive** [comment]
修正したLightning Advanced Unit をアップいたしました。
ご報告ありがとうございました！
