### ISSUE TITLE
fontawesomeアイコンが表示されません。

### ISSUE THREAD

**Issue by 53rd** [vektor-inc/Lightning#196]
Lightningテーマを実装した全サイトで同様にＰＲブロック内のアイコンが表示されなくなりました。

何か改善する方法はありますでしょうか？

**Comment by kurudrive** [comment]
外観 > カスタマイズ > FontAwesome で 一度5.0 にして保存してからそのまま4.7にして保存してみてください。

LightningとExUnitはいずれも最新版にアップデートしてください。

**Comment by 53rd** [comment]
ありがとうございました。

ライトニングのサイトにも載っていました。
お手数かけました。

**Comment by kurudrive** [comment]
問題なさそうで何よりです。
今後ともLightningをよろしくお願いいたします。
