### ISSUE TITLE
投稿記事の一覧の不具合について

### ISSUE THREAD

**Issue by chocobananacrepe** [vektor-inc/Lightning#202]
初心者です。
よろしくお願い致します。

管理画面ではなく、投稿した記事をアイキャッチ画像で一覧にして表示する画面（投稿記事の親ページ）において、サイドメニューを表示している場合、画面サイズを小さくすると記事と記事の（アイキャッチ画像の）間に食い込んでしまい、記事をクリック出来ずにサイドメニューの項目をクリックしたと見なされてしまいます。
「アーカイブ」や「カテゴリー」をサイドメニューに表示していた場合、記事のアイキャッチ画像の上部分（画像部分）をクリックすると、「カテゴリー」などをクリックされたことになり、画面遷移が意図しない形になってしまいます。
本来であれば、アイキャッチ画像の投稿記事一覧の下にサイドメニューが表示されるべき状態なのですが、（スマホなどでは大丈夫です）メニューの一部が記事一覧に食い込む状態になっております。

無料機能の一部とは思いますが、検証と対策をお願い致します。

**Comment by kurudrive** [comment]
ちょっとどの画面かわからないのですが
https://lightning.nagoya/ja/information
とかの事ですか？

**Comment by chocobananacrepe** [comment]
ご返信ありがとうございます。
そうなります。

ただ、私共のWebサイトでは、
3lineのアイキャッチ画像のみの表示です。
（すみません、どこで設定するのか失念しました）

説明が拙く申し訳ありません。

**Comment by kurudrive** [comment]
有料の拡張デザインスキンをご利用で、
外観 > カスタマイズ 画面で「Lightning アーカイブページレイアウト」からレイアウトを変更していますか？

**Comment by chocobananacrepe** [comment]
どこで設定するのか思い出しました。
当社のサイトでは、
「Image Card 1st」の設定になっていました。

投稿ページに設定したウィジェットが、
一部、食い込んでしまうという事象です。

**Comment by kurudrive** [comment]
Image Card 1st feature での挙動確認いたしました。
不都合おかけして恐れ入ります。
修正作業を行って予めご連絡いたします。
ちなみにデザインスキンは何をご利用でしょうか？

**Comment by chocobananacrepe** [comment]
ご対応ありがとうございます。
「Lightning Origin Pro」を使用しておりますが、
理由あって、バージョンアップが漏れており、2.04のままになっています。
来週までアップデート出来ない状態です。

**Comment by kurudrive** [comment]
Lighnting 4.4.12 にて対応いたしました。

アップデートできない場合は下記CSSを　外観 > カスタマイズ の 追加CSS あたりに記載してみてください。

`.postList::after { content: "";clear: both;display: block; }`

以上よろしくお願いいたします。

**Comment by chocobananacrepe** [comment]
ありがとうございました。
ご対応に感謝致します。
