### ISSUE TITLE
Webアイコンが見えない

### ISSUE THREAD

**Issue by berghilo** [vektor-inc/Lightning#204]
http://demo.vs1.biz/lightning-origin-pro/
ここの「サービス案内」の3列の●の中のアイコンですが、
win10
クローム最新版
では見えません。
よろしくお願いします。

**Comment by kurudrive** [comment]
ご報告ありがとうございます。修正しました。

**Comment by kurudrive** [comment]
※ サイト全体のFont Awesome のバージョンが5.0に変更してあったが、PR Blockウィジェットに入力していたアイコンフォントのクラス名が4.7のままであったため
https://ex-unit.nagoya/ja/archives/v-6-4-1
