### ISSUE TITLE
テーマディレクトリ名の変更時の「Lightning デザイン設定について」不具合

### ISSUE THREAD

**Issue by berghilo** [vektor-inc/Lightning#206]
Lightningテーマのインストールディレクトリ名を「lightning」から別名にしてインストールしたところ、「外観＞カスタマイズ＞Lightning デザイン設定」において「投稿詳細ページで投稿者名を表示しない」項目以降が表示されなくなりました。

●デザインスキン
Lightning origin

●非表示項目
□サイドバーに表示されるページリストを全て表示せずにアクティブでない階層を非表示にする 
□サイドバーを固定しない

・メニュータイプ（モバイル端末時）
・メニューボタンの位置（モバイルモード）
・サイドバーの位置（PC閲覧時）

●ウィジェットに於いても下記が消えます。
LTG コンテンツエリア投稿リスト
LTG 全幅見出し

●その他
他の設定箇所などでも機能が制限されているかもしれません。

●環境
Lightningバージョン: 4.4.12
win10
ブラウザー　クローム最新版

ディレクトリ名を「lightning」から別名に変更できない仕様なのでしょうか？

よろしくお願いします。

**Comment by kurudrive** [comment]
機能を制限しているというより その部分は Lightning Advanced Unit から制御しているので、
Lightning以外のテーマの時に Lightning Advanced Unit が動いていては無駄な処理であったり誤動作を引き起こす要因となるので Lightning でない時は動作しない処理になっています。
必要に応じて Advanced Unit を改変してください。

※Advanced Unit 自体は近日Lightning本体などに取り込んで廃止予定です。

**Comment by berghilo** [comment]
了解いたしました。

**Comment by kurudrive** [comment]
ちなみにモバイルメニューは今後 Vk  Mobile Nav に一本化

LTG コンテンツエリア投稿リスト
LTG 全幅見出し
は本体取り込みとなるので、待ってれば何も作業は必要なくなると思います。

**Comment by berghilo** [comment]
更新日を楽しみにしつつ、それまではプラグインのテーマ名をいじって対応します。

ちなみにそれらの更新でプラグインが不要になり、同時にテーマ名を変えている場合でも不具合はないのでしょうか？

お手数でなければ分かる範囲でご回答いただけますと幸いです。
よろしくお願いします。
