### ISSUE TITLE
[ TGM ] VK All in One Expansion Unitの更新時の通知を管理者以外で非表示にしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#229]
Lightningを有効化するとtgm-plugin-activation というライブラリを使って ExUnitとAdvanced Unit をインストールするように促す設定となっている。
で、更新がある時も全ページの上部にアップデートの通知が表示されてしまうが、
インストール以外の更新通知は表示しないように...たぶん設定が変更出来るんじゃないかなと思う。

**Comment by naogify** [comment]
@kurudrive これって、「管理者以外に通知を出さない」でも良いでしょうか？

**Comment by kurudrive** [comment]
@naogify 無かったですか〜。ふむ〜。ではfunctions.phpから設定してください〜。

**Comment by naogify** [comment]
@kurudrive りょうかいです！その方向で進めます!

**Comment by kurudrive** [comment]
@naogify 
あ、ごめんなさい。
更新通知に関してはどうせプラグイン一覧とかには出るので、
管理者関係なく非表示にしてください。

なので表示されるのはインストール・有効化されてない時だけになります。

あと、非表示にする処理ってdisplay:none;じゃなくってメッセージ自体を
remove_action か remove_filter で外せないかな？
※ 難しそうだったら無理しなくて良いっす。

**Comment by naogify** [comment]
@kurudrive りょうかいです！ちょっと見てみます。

**Comment by naogify** [comment]
@kurudrive 
この実装はかなり難しそうです。remove_action か remove_filter などで外せそうなフックが見当たらなかったのと、CSSで非表示にするにしてもアップデート通知だけに振られているidやクラスがないので厳しそうです。。。

**Comment by kurudrive** [comment]
@naogify 了解です。ではCSSで行きましょう。調査ありがとうございます。

**Comment by naogify** [comment]
@kuniyuki わかりました!

**Comment by naogify** [comment]
@kurudrive このままマージしてもらう、ということで大丈夫ですよね？

**Comment by kurudrive** [comment]
@naogify うぃす（・ｗ・

**Comment by kurudrive** [comment]
@naogify 

> 更新通知に関してはどうせプラグイン一覧とかには出るので、
> やっぱり管理者関係なく非表示にしてください。

だけよろ

**Comment by naogify** [comment]
@kurudrive 更新通知だけCSSで非表示というのが難しいです。。。というのも、各通知だけに振られているIdや、classがないんです。

`<strong>`で囲われている`<span>`がそれぞれ上から、インストール通知、更新通知、インストールボタン、になっているんですが、それぞれにidやclassは振り分けられてないんです。

もし、必要であればもう少し、調査してみますが、ちょっと時間はかかると思います。

![2018-08-02 10 55 01](https://user-images.githubusercontent.com/8760841/43558142-e943971e-9642-11e8-9413-48bef5dfddab.png)

**Comment by naogify** [comment]
一応、方法がないか、もう1度調査してみます。

**Comment by kurudrive** [comment]
@naogify あー、新規インストールも非表示になっちゃうのね。
まぁでもそうか、、、ぐぬぬ、、、
いや、じゃあ今の仕様（管理者にはインストールも更新も表示）でいいや。
今の所そんなに重要な機能でもないし。

**Comment by naogify** [comment]
@kurudrive わかりました!
