### ISSUE TITLE
h1タグに関して

### ISSUE THREAD

**Issue by hamu0** [vektor-inc/Lightning#234]
ご担当者様

いつもお世話になっております。
非常に使いやすく、魅力的なテーマだと感じております。

1つ改善の要望となります。
https://bizvektor.com/manage/seo/
こちらに記載があるように、h1は基本的に各ページにひとつが望ましいとされていますが
サイドバーのタイトルやウィジェットのタイトルがほとんどh1タグで構成されています。

できることなら、h4などに変更していただけないでしょうか？

シンプルで信頼感のあるデザインなので、
制作依頼を受けた際、こちらのテーマをご提案する機会も多いのですが
h1タグを手動カスタマイズするのがかなりの手間となっております。

お忙しい中かと思いますが、ご検討のほどお願いいたします。

**Comment by kurudrive** [comment]
ご利用ありがとうございます。
BizVektorはLightningと違いHTML5で組んでいます。
html5において aside タグや article タグの中の h1 は、ページの見出しではなくサブ要素の見出しとしてGoogleなどは判断するので、SEO上現状のマークアップ構造で問題ありません。
ページの見出しとなるh1は一つだけ適切にマークアップしています。

また、既に２万以上のサイトで利用されているので、今の段階でタグを変更すると、デザインをカスタマイズして利用しているサイトのデザインが崩れてしまったりする事があるので、変更する事は難しいです。

以上何卒ご理解いただけますと幸いです。
