### ISSUE TITLE
子ページ一覧見出し、概要文の改行方法

### ISSUE THREAD

**Issue by wyoshitaka** [vektor-inc/lightning#243]
charmを現在使用していますが、charmに限らずのことになるかと思います。
同じ悩みや解決策お持ちの方いましたらお教え頂けますでしょうか。

１、
固定ページのタイトルを子ページ一覧の見出し、H3 class="childPage_list_title"にも使用しているかと思いますが、タイトルを英語、カタカナ併記した場合、文章の途中で変に自動で折り返してしまいます。

例、
固定ページタイトル：
WordPressLightning　ワードプレスライトニング

子ページ一覧での見出し：

WordPressLightning　ワードプ
レスライトニング

こちら英語　改行　カタカナ　と表示させる解決策ありますでしょうか。

２、１と同じ形ですが、子ページ一覧の概要文は固定ページの抜粋を利用していますが、こちらも改行やbrタグが効かないので変に文章途中で折り返してしまいます。
こちらも改行効かせる解決策はありますでしょうか。

下記参考のような解決策もあるようですが、こちらライトニングに適応できるでしょうか。

参考
■レスポンシブデザインテキスト折り返しの指定
css
https://app.codegrid.net/entry/responsive-text-1#toc-0
■抜粋html
プラグイン
https://www.dctweb.jp/201607t/
PHP
https://qiita.com/yumayamada1029/items/91cbbb23447618161899

**Comment by kurudrive** [comment]
ExUnit に関する事項なのでclose
