### ISSUE TITLE
スマホのグローバルナビ：同一ページのカスタムリンク（wordpress）を押した際にメニューが閉じない

### ISSUE THREAD

**Issue by kuunyy** [vektor-inc/Lightning#246]
お世話になります。スマホのグローバルナビから同一ページへのリンクを挿入していますが裏側ではスクロールして指定の箇所まで行きますが、メニューが自動で閉じません。過去に下記のようなissueを見つけました。

「スマホのグローバルナビ:同一ページのアンカーポイント移動でメニューが閉じない。
#80 opened on 20 Jul 2016 by inaina-sayuu  updated on 4 Apr」

こちら試してみたのですが、こちらのコードをどこへ入力すれば良いのかわかりません。教えて頂けますと幸いです。

**Comment by kurudrive** [comment]
修正しましたーん。
