### ISSUE TITLE
投稿ページをシングルカラムにしたい

### ISSUE THREAD

**Issue by dskhaga** [vektor-inc/Lightning#252]
＞このウィジェットエリアに何もセットされていない場合は、「最新記事リスト」「カテゴリーリスト」「月別アーカイブリスト」が表示されます。

シングルカラムにして投稿ページの横幅を大きく取りたいのですが可能でしょうか。

**Comment by kurudrive** [comment]
外観 > カスタマイズ > レイアウト設定 などで設定可能に機能追加済み
