### ISSUE TITLE
BizVektorからの移行における不具合？

### ISSUE THREAD

**Issue by bj2web** [vektor-inc/Lightning#253]
お世話になります。同様の書き込みが見当たらないのでこちらに報告させて頂きます。
以前はBizVektorを利用していましたが、「今後のBizVektorとアップデートのお願い」との案内があったため、手順通りLightning（Ver. 6.6.3）に移行しました。

この際、BizVektorから引き継がれた「カスタム投稿」では、「パーマリンク編集」「メディアを追加」「ビジュアル/テキスト切り替え」などのボタンが機能しなくなってしまいました。
新しくLightning上で作成した「カスタム投稿」については、問題無く機能していますので、今後はこちらを使用する事にしましたが、固有の問題でしょうか。

もしかすると同様のトラブルでお困りの方がいるかもしれませんので、ご参考まで。

**Comment by kurudrive** [comment]
> この際、BizVektorから引き継がれた「カスタム投稿」では、

これは ExUnitのカスタム投稿タイプマネージャーで作成した info という意味ですか？

**Comment by bj2web** [comment]
ExUnitではなく、以前のBizVektor上で作成したものです。

**Comment by kurudrive** [comment]
んー、多分 BizVektor から引き継いだからとかではなく別でなにか設定が違うのかなとは思います。

info と Lightning上で作成した「カスタム投稿」 は両方ともカスタム投稿タイプマネージャーで作成したものですか？

どちらか片方はfunctions.phpに直接記載して作成してるとかだと、記載内容によって設定の違いがあるかもしれません...。

**Comment by bj2web** [comment]
>『info』と『Lightning上で作成した「カスタム投稿」』 は両方ともカスタム投稿タイプマネージャーで作成したもの

その通りです。
承知しました。ご回答ありがとうございます！
