### ISSUE TITLE
CTAが表示されなくなった

### ISSUE THREAD

**Issue by yshrtkuc** [vektor-inc/Lightning#259]
本日、Lightningをバージョンしました。
Lightning Proバージョン: 0.8.5です。
Wordpress、プラグインはすべて最新です。

以前はCTAが正常に表示されていましたが、現在はCTAの説明が表示されるのみで、
画像とボタンが表示されなくなってしまいました。
Varietyでも、Originでも、同じ現象がおきます。

対応方法があれば教えていただけないでしょうか。

**Comment by kurudrive** [comment]
僕の環境で確認する限りは問題ないのですが、
該当URLを貼っていただく事は可能ですか？

**Comment by yshrtkuc** [comment]
ここに直接は貼りにくいのですが、
個々でメッセージをお送りできるところはありますでしょうか。

**Comment by kurudrive** [comment]
CTAは別のCTAを登録して、その新しく登録したCTAを記事ページで選択して表示させた時に同じ不具合は発生しますか？

**Comment by yshrtkuc** [comment]
ありがとうございます。結論から申し上げますと、正しい表示ができるようになりました。
ただし、特定のパターンで不具合もあるようです。

お知らせいただいたように、別のCTAを新しく登録しました。
取り急ぎ、画像とボタン、リンクだけにしたら、正常に表示されました。

そこで、他の項目を一つ一つ入力してみたところ、
こちらの環境では、CTA作成画面にGutenbergのエディアが表示されているのですが、
「タイトルを追加」の下の、
「文章を入力、または/でブロックを選択」（コンテンツの部分）に何らかの文字列が入っていると、
表示がおかしくなってしまうようです。

**Comment by kurudrive** [comment]
あ...それはきっとこれの事ですね（・ｗ・；

https://ex-unit.nagoya/ja/archives/cta-and-block-demo

**Comment by yshrtkuc** [comment]
なるほど、新旧の機能で中途半端な状態になっていたのですね。
もともと、コンテンツを入力するところに文字列が入っていたため、
新機能のほうが優先されたのですね。

新旧の切り替えがボタン等で分かれていると、
より、分かりやすいかもしれないなと思いました。

いずれにせよ、解決できました。ありがとうございました！
