### ISSUE TITLE
VK_Recent Posts の見出しがとても大きい。

### ISSUE THREAD

**Issue by jjiijjii** [vektor-inc/Lightning#26]
大きいことは良いことなのですが、テーマのバランスを見ると、少し大きすぎるようにも思います。ご検討ください…．

**Comment by kurudrive** [comment]
スケボーブログの表示で大きいですか？
もしスケボーブログの方では違和感ないという事であれば、開発中の最新版では解消されている問題だと思いますので、最新版の公開までしばらくお待ちください。

**Comment by kurudrive** [comment]
修正済み
