### ISSUE TITLE
No sidebarを適用していても、プレビューでサイドバーが表示される

### ISSUE THREAD

**Issue by MayaOta** [vektor-inc/Lightning#260]
lightning、いつも活用させていただいております。

Wordpress英語フォーラムの方に先に書いてしまったのですが、こちらの方が内容的に合っているかと思い投稿させていただきます。
----------

固定ページのテンプレート「No sidebar」を適用していても
「変更をプレビュー」からページを確認するとサイドバーが表示されてしまいます。
サイドバーに表示されているのは、そのページの親子ページの一覧です。

「更新」をして実際の公開ページを開くとサイドバーなしの状態で見られます。

No sidebarを適用したページはプレビューでもサイドバーなしの状態で確認できるはずなのですが…これはバグでしょうか？

少し現象は違いますが、以下のサイトの方法は試してみました。
https://tijaji.jp/%E3%83%97%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%81%A7%E3%81%AF%E3%82%B5%E3%82%A4%E3%83%89%E3%83%90%E3%83%BC%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%82%8B%E3%81%AE%E3%81%AB%E6%9C%89%E5%8A%B9/

原因がお分かりになりましたら、アドバイスお願いします。

**Comment by kurudrive** [comment]
本件既に仕様がかわっているので close いたします。

https://lightning.nagoya/ja/archives/lightning-pro-5-layout-specification
