### ISSUE TITLE
ipad proでの表示

### ISSUE THREAD

**Issue by howcomeit** [vektor-inc/Lightning#261]
ipad (12.2)での表示でグローバルメニューのドロップダウンメニューが反映されない。（ドロップダウンメニュー設定のメニューが無反応）ほかのデバイスでは不具合はありません。対処法をご教示ください。（Lightning　Version: 6.8.0使用）

**Comment by kurudrive** [comment]
これの事ですか？
https://vws.vektor-inc.co.jp/forums/topic/touch-device-menu

**Comment by kurudrive** [comment]
別件の場合は症状など詳細記載いただけると助かります。

**Comment by howcomeit** [comment]
早々にコメントをありがとうございます。当方はグローバルナビゲーションの下位メニューが表示もされないのですが、試しにブラウザを変えて確認したところ、Safari、Chromeでは無反応、firefox、Sleipnirでは問題ありませんでした。恐らく原因内容は該当するように思われます。次回のメジャーアップデートを待つしかなさそうですね。

**Comment by kurudrive** [comment]
ノーカスタマイズで使ってる人だけの前提なら修正できるのですが、
独自でCSSカスタマイズしてるサイト数も多いので、
そちらに影響出てしまったりする事を考慮すると安易に直せない部分もありまして...
なるべく早く解消できるように善処します...。

**Comment by howcomeit** [comment]
こちら、ほぼノーカスタマイズです。
修正方法、シェアしていただけますか？

**Comment by kurudrive** [comment]
header.php を子テーマにコピーして
30行目を

`'items_wrap'     => '<ul id="%1$s" class="%2$s nav gMenu vk-menu-acc">%3$s</ul>',`

に変更（vk-menu-accを追加）

機能的にはそれで出来ますが、CSSがきっとぐちゃぐちゃになるので、
修正が必要です。

まずそこでそれなりに工数がかかるのと、
そこでCSSを変更すると既存カスタマイズされたサイトが壊れるので、
簡単には変更できないという状態です。

**Comment by howcomeit** [comment]
シェアありがとうございました。
早速変更してみましたが、確かに機能的には動きました。しかしおっしゃる通り表示は正しくされません。
この修正はかなり厳しいですね。

引き続き、何か朗報がございましたらお知らせいただけますと幸いです。

**Comment by kurudrive** [comment]
次期メジャーアップデートから実装するデザインスキン「Origin II」で解消されます。

以下のような状態になります。

https://www.vektor-inc.co.jp

急ぎの場合は開発中のバージョンを下記よりダウンロード可能です。

https://github.com/vektor-inc/Lightning/tree/skin_bs4

※かなり構造変更を行っている途中なので、子テーマでのカスタマイズなどは正式リリースまでお待ちください。
9月中旬頃リリース予定です。
