### ISSUE TITLE
Lightning デザイン設定のページリストの設定がない

### ISSUE THREAD

**Issue by suzuki669** [vektor-inc/Lightning#264]
いつの間にかなくなったのでしょうか？

https://lightning.nagoya/ja/archives/adv_2_1_1

**Comment by kurudrive** [comment]
表記がいつの間にか「サイドバーに子ページのリストを表示しない」に変更されていますが、
今もあります。

**Comment by suzuki669** [comment]
お返事ありがとうございます。

なるほど、そういうことだったのですね。
結局この設定はサイドバーの、それもデフォルトのウィジェットにしか作用しないんですね。

カスタマイズしたウィジェットや固定ページ下の子ページ一覧にも適用することはできないんでしょうか？

どうぞよろしくお願い致します。

**Comment by kurudrive** [comment]
> カスタマイズしたウィジェット

ウィジェットだとカレントページのclass名が出力されないので、どこほ非表示にすればいいのか制御できない

> 固定ページ下の子ページ一覧

外観 > カスタマイズ > 追加CSS に下記追加にて対応ください。

```
.veu_pageList_ancestor li li {
	display:none;
}

.veu_pageList_ancestor li.current_page_item li,
.veu_pageList_ancestor  li.current_page_ancestor li{
	display:block;
}
```
