### ISSUE TITLE
「 Contactを編集」と出ないようにしたい

### ISSUE THREAD

**Issue by fujisunny** [vektor-inc/Lightning#272]
お世話になります。

さて、Contactの下に「 Contactを編集」という表示が出てしまいます。
一般の人の目には触れないようにしたいのですが可能でしょうか？
管理者がログインした時だけ表示されたら嬉しいです。
よろしくおねがいします。

**Comment by kurudrive** [comment]
非ログインユーザーには表示されません。
ログアウトした状態などで一度ご確認くださいませ。

**Comment by fujisunny** [comment]
ありがとうございます。ログアウトした状態でも表示されていたのですが、いろいろ触っていたら治っていました。（ウィジェットの保存のし直しとか）
ちなみに、ウィジェットで「VK お問い合わせボタン」を設置した時、その下に「 Contactを編集」と表示されていました。
なお、Polylangという多言語化プラグインを使ってて、それぞれのページで、「すべての言語」「日本語」「英語」を設定できるのですが、それが原因だったのかも？？

**Comment by kurudrive** [comment]
ブラウザのキャッシュなどかもしれませんね。
解決という事でcloseします。
