### ISSUE TITLE
Chrome デベロッパーツールでエラー

### ISSUE THREAD

**Issue by hiro003** [vektor-inc/lightning#274]
いつもお世話になります。
Lightning 6.13.6 を WooCommerce で利用しています。

Chrome デベロッパーツールで以下のエラーが表示されました。

`Uncaught ReferenceError: jQuery is not defined
    at (index):59
(anonymous) @ (index):59
(index):65 Uncaught ReferenceError: jQuery is not defined
    at (index):65
(anonymous) @ (index):65
(index):72 Uncaught ReferenceError: jQuery is not defined
    at (index):72
(anonymous) @ (index):72
jquery-migrate.min.js,qver=1.4.1.pagespeed.jm.C2obERNcWh.js:1 JQMIGRATE: Migrate is installed, version 1.4.1
(index):479 GET https://www.xxxxx.com/wp-content/themes/lightning/woocommerce/js/address-i18n.js net::ERR_ABORTED 404
(index):486 46
(index):479 GET https://www.xxxxx.com/wp-content/themes/lightning/woocommerce/js/address-i18n.js net::ERR_ABORTED 404
content.js:470 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ content.js:470
content.js:977 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write`

HTMLには、以下の記載があります。
`<script async src='https://www.xxxxx.com/wp-content/themes/lightning/woocommerce/js/address-i18n.js'></script>`

/wp-content/themes/lightning/woocommerce/フォルダーが存在しないためのエラーかと思います。
お忙しいところ、よろしくお願いいたします。

**Comment by kurudrive** [comment]
報告ありがとうございます！

@naogify これ確認よろり。

**Comment by naogify** [comment]
@kurudrive 了解です。確認します。

**Comment by naogify** [comment]
@hiro003
報告ありがとうございます!

Lightning 6.13.6、WooCommerce 3.6.4で検証してみたのですが、報告して頂いたバグは再現できませんでした。何か他にバグの原因になっているプラグインなどはないでしょうか？

**Comment by hiro003** [comment]
ありがとうございます。

私の環境では、すべてのプラグインを停止、以下のみの状態でもエラーが表示されます。
Lightning 6.13.6
VK All in One Expansion Unit 9.1.3
WooCommerce 3.6.4

Ubuntu 18.04.2
Plesk Onyx 17.8.11

**Comment by kurudrive** [comment]
現行バージョンで確認できないため一旦closeさせていただきます。
引き続き発生している場合あらためて通報ください。
