### ISSUE TITLE
Polylangプラグインで多言語対応した場合の「Lightningヘッダー上部」「お問い合わせ情報」の英語化について

### ISSUE THREAD

**Issue by fujisunny** [vektor-inc/Lightning#275]
「外観」「カスタマイズ」の「Lightningヘッダー上部」の要素をPolylangプラグインを使った英語ページでも使えるようにしたい。特に、お問い合わせのボタンを英語ページの時は英語で表記されるようにしたい。

また、ExUnitの「お問い合わせ情報」も、英語ページとしても登録できるようにして、スマホでも「VK お問い合わせ情報」ウィジェットを使って英語で表示されるようにしたい。

**Comment by kurudrive** [comment]
オプション値で保存する構造なので一つのサイト構造で多言語化を実現するのは不可能です。
Multisite Language Switcher などを使い、別のサイトとして作成した方がおすすめです。
ただ、長期的に構造変更を行えば対応できない事もないと思えたので、今後の検討課題とさせていただきます。

**Comment by fujisunny** [comment]
ありがとうございます！
