### ISSUE TITLE
Lightning Pro の metadeta の破損（？）により Lightning Pro が更新不可能状態に

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/Lightning#278]
フォーラムにも書きましたが、現在 Lightning Pro の更新が不可能なようです。
詳細はフォーラムにて
https://vws.vektor-inc.co.jp/forums/topic/lightning-pro-%e3%81%ae%e6%9b%b4%e6%96%b0%e7%94%a8%e3%82%b5%e3%83%bc%e3%83%90%e3%83%bc%e3%81%8c%e5%81%9c%e6%ad%a2%e4%b8%ad%ef%bc%9f

**Comment by kurudrive** [comment]
報告ありがとうございます。
対応完了しておりますのでCloseします。
