### ISSUE TITLE
Font Awesome の 5.10.1 が出ています。

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/Lightning#279]
Font Awesome の 5.10.1 が出ています。
新たなアイコンも追加されているようなので、
ぜひバージョンアップを検討していただきたいです。

**Comment by kurudrive** [comment]
はいー、順次対応しますー。
いろいろテンパってますので今しばらくお待ち願います！＞＜

**Comment by kurudrive** [comment]
- [ ] vektor-lib
- [ ] vk-blocks 
- [ ] vk-blocks release
- [ ] ExUnit 
- [ ] ExUnit release
- [ ] Post Author Display
- [ ] Post Author Display release
- [ ] Lightning BS4
- [ ] Lightning release
- [ ] Lightning Pro BS4
- [ ] Lightning release

**Comment by rick-addison** [comment]
タイミングが悪く恐縮ですが・・・
5.10.2にアップデートされたようです。

**Comment by rick-addison** [comment]
現在の最新版は5.11.2で、5.11では新アイコンが325追加されたそうです。
https://fontawesome.com/changelog/latest

**Comment by kurudrive** [comment]
- [x] vektor-lib
- [ ] vk-blocks 
- [ ] vk-blocks release
- [ ] ExUnit 
- [ ] ExUnit release
- [ ] Post Author Display
- [ ] Post Author Display release
- [ ] Lightning BS4
- [ ] Lightning release
- [ ] Lightning Pro BS4
- [ ] Lightning release
