### ISSUE TITLE
[vk-mobile-nav]モバイル端末で正しく動作していない / Ecwidのプラグイン?

### ISSUE THREAD

**Issue by mi0421** [vektor-inc/Lightning#286]
モバイル端末利用時、タップしてもメニューが展開されない。正しく動作していない。

**Comment by kurudrive** [comment]
javascriptがなにかエラー吐いていませんか？
弊社以外のプラグインを停止して確認してみてください。
子テーマを利用している場合は親テーマに戻して確認してみてください。

**Comment by mi0421** [comment]
コメントありがとうございます。
御社以外のプラグインを全て停止して確認してみたところ、
ショッピングカートのプラグインを有効にすると、
メニューのモバイルナビが動作しなくなることが分かりました。

Ecwidというプラグインですが、リアル店舗の決済方法と同じ決済方法が使えて、
売上計上等をまとめてオンラインで確認ができ、
Ecwidのプラグインをバージョンアップするまでは何事もなく使えていたのですが、
どうしたものかと・・・

何か良い方法があれば教えていただきたいです。
よろしくお願いします。

**Comment by kurudrive** [comment]
トップページのスライドショーは利用してますか？
スライドショーを利用している場合は正常に動作してますか？
ExUnitの スムーススクロール ボタンは有効にしていますか？
有効にしている場合 PageTopボタンなどを押した時にスルスル動作しますか？
スムーススクロールを停止した時に正常に動作しますか？

**Comment by kurudrive** [comment]
Ecwidのプラグインを一応有効にしてみましたが、単純に有効化しただけだと再現しませんでした。
該当URLは貼れませんよね...?
