### ISSUE TITLE
[ 仕様変更 ] アクションフック追加 #121 について

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/Lightning#287]
[ 仕様変更 ] アクションフック追加 #121 
上記は single.php は対象外なのですか？
あと、個人的には the_content(); の前後と <article>（略）</article>の前後にも欲しいところです。

また、個人的には固定ページでもコメント部分を表示できるようにしたほうがいいような気がします。（WP側のオプションでデフォルトではOFFですがONにすることも可能なので）

**Comment by kurudrive** [comment]
> [ 仕様変更 ] アクションフック追加 #121
> 上記は single.php は対象外なのですか？
> あと、個人的には the_content(); の前後と
> 
> （略）の前後にも欲しいところです。

追加しました。

> また、個人的には固定ページでもコメント部分を表示できるようにしたほうがいいような気がします。（WP側のオプションでデフォルトではOFFですがONにすることも可能なので）

うーん、これは出来るだけ設定で気にしないといけないところを減らしたいのと、コメント機能自体スパムだらけで正常に機能しにくい状況なので、必要な人だけカスタマイズして貰うという形のままとしたいと思います。

**Comment by rick-addison** [comment]
前回コメントしたとき上手く表示されていませんでしたが、
`<article>` の前と `</article>`の後にもほしいです。
ひょっとして`<article>` の前はすでに対応済みですか？

**Comment by kurudrive** [comment]
articleの前後・prependに入れるとレイアウト崩れやループモジュールによって出る出ないのトラブルの温床になるので入れたくないデス ＞＜

**Comment by rick-addison** [comment]
`<article>` の前には
`<?php do_action( 'lightning_mainSection_prepend' ); ?>`
で対応してくださってありがとうございます。
`</div><!-- [ /.mainSection ] -->`
の直前に
`<?php do_action( 'lightning_mainSection_append' ); ?>`
が欲しいです。

**Comment by rick-addison** [comment]
４ファイルへの適用ありがとうございます。
index.php には`<?php do_action( 'lightning_loop_after' ); ?>`があるので良いのですが、
front-page.php や  woocommerce.php や page-lp-builder.php には追加しないのですか？

**Comment by kurudrive** [comment]
page-lp-builder.php はそもそも mainSection がないので追加していません。
その他は追加しましたんー。

**Comment by rick-addison** [comment]
対応ありがとうございます。 prepend があるものは対称位置に append が欲しいところですが、
暇がある時でOKです。先に他のことを優先してください。

**Comment by rick-addison** [comment]
下記は single.php の終盤です。
誠に恐縮ながら下記の様にアクションフックを増やしていただたいです。
やりたいことはコード中のコメントで書いています。
```
<?php do_action( 'lightning_mainSection_append' ); ?>
</div><!-- [ /.mainSection ] -->

<div class="<?php lightning_the_class_name( 'sideSection' ); ?>">
<?php get_sidebar( get_post_type() ); ?>
</div><!-- [ /.subSection ] -->

<!--↓追加のサイドバーを配置したい↓-->
<?php do_action( 'lightning_sidebar_after' ); ?>
<!--↑追加のサイドバーを配置したい↑-->

</div><!-- [ /.row ] -->
	
<!--↓ウィジェットを配置したい↓-->
<?php do_action( 'lightning_siteContent_container_append' ); ?>
<!--↑ウィジェットを配置したい↑-->

</div><!-- [ /.container ] -->
	
<!--↓ウィジェットを配置したい↓-->
<?php do_action( 'lightning_siteContent_append' ); ?>
<!--↑ウィジェットを配置したい↑-->
	
</div><!-- [ /.siteContent ] -->
<?php get_footer(); ?>
```
page,php 等のファイルにも同等の機能がほしいです。
テンプレート中にサイドバーがないものには
```
<!--↓追加のサイドバーを配置したい↓-->
<?php do_action( 'lightning_sidebar_after' ); ?>
<!--↑追加のサイドバーを配置したい↑-->
```
の部分は不要です。

同様に
`<div class="container">`～`</div><!-- [ /.container ] -->`
がないものには
```
<!--↓ウィジェットを配置したい↓-->
<?php do_action( 'lightning_siteContent_container_append' ); ?>
<!--↑ウィジェットを配置したい↑-->
```
の部分は不要です。

**Comment by kurudrive** [comment]
これも今回入ったと思うのでclose
