### ISSUE TITLE
LTGコンテンツエリアウィジェットでNotice

### ISSUE THREAD

**Issue by pooh-kamakura** [vektor-inc/Lightning#293]
Lightning 7.0にアップデート後、LTGコンテンツエリアウィジェットでNoticeが出ます。

Undefined variable: postType
lightning/inc/widgets/widget-new-posts.phpの92と98行目

**Comment by kurudrive** [comment]
just a moment ...

**Comment by kurudrive** [comment]
I fixed id check it out !! 
m9っ・ｗ・）ｂ

**Comment by pooh-kamakura** [comment]
動作確認しました。
早速の対応、ありがとうございます。
