### ISSUE TITLE
single.php の ページヘッダーとパンくずリストの書き方がレガシー

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/Lightning#298]
子テーマを作成しようと思って single.php を子テーマに複製して中身を見てみたらページヘッダーとパンくずリストのレガシーな書き方がレガシーでした。

表示はなぜか正常にできているので今の所問題は無いのですが忘れないうちに対処しておくことをおすすめします。

**Comment by kurudrive** [comment]
おっと...ホントですね...

表示してされるのは 古い階層指定で子テーマが作られた時にも問題なく表示するように処理が入っているからです。

報告ありがとうございました！助かります！

**Comment by kurudrive** [comment]
修正リリースしました。
ありがとうございました。
