### ISSUE TITLE
itemtype="http://schema.org/BreadcrumbList" スキーマが消えている問題?

### ISSUE THREAD

**Issue by ifNoob** [vektor-inc/Lightning#304]
breadcrumb.php 内で
```
$panListHtml = '<!-- [ .breadSection ] -->
<div class="section breadSection">
<div class="container">
<div class="row">
<ol class="breadcrumb" itemtype="http://schema.org/BreadcrumbList">';
```

スキーマの設定を、以下の wp_kses_post 関数で消してしまっている。
$panListHtml = wp_kses_post( apply_filters( 'lightning_panListHtml', $panListHtml ) );

この場合以下でないと、スキーマを書き出せない。
$allowed_html = array(
	'div' => array(
  	'id' => array(),
  	'class' => array(),
    'itemprop' => array(),
    'itemscope' => array(),
    'itemtype' => array()
	),
  'ol' => array(
  	'id' => array(),
  	'class' => array(),
    'itemprop' => array(),
    'itemscope' => array(),
    'itemtype' => array()
	),
	'li' => array(
  	'id' => array(),
  	'class' => array(),
		'itemprop' => array(),
		    'itemscope' => array(),
    'itemtype' => array()
	),
	'a' => array(
  	'id' => array(),
  	'class' => array(),
    'href' => array(),
    'target' => array(),
		'itemprop' => array()
	),
	'span' => array(
  	'id' => array(),
  	'class' => array(),
		'itemprop' => array(),
   	'itemscope' => array(),
    'itemtype' => array()
	),
	'i' => array(
  	'id' => array(),
  	'class' => array()
	)
);
$panListHtml = wp_kses( $panListHtml, $allowed_html );
ひょっとして、Lightning Theme の仕様???。

**Comment by kurudrive** [comment]
ありがとうございます。
次回リリース時に反映されます。

**Comment by ifNoob** [comment]
他にも緩い希望....。
index.php 等のスキーマ追加対応を。
echo wp_kses_post( apply_filters( 'lightning_mainSection_archiveTitle', $archiveTitle_html ) );
wp_kses_post <= DBからのエスケープのハズ?

**Comment by kurudrive** [comment]
具体的にどこかわかりかねますので、詳細記載いただくかプルリクエストなどいただけると助かります。

**Comment by ifNoob** [comment]
上記は希望で、現在こちらもcodeの検証中...。
それと、meta.php   内のquotation 忘れミス
                                                                                                                                                  ↓  quotation 忘れ
<span class="entry-meta_items entry-meta_updated<?php echo $meta_hidden_update; ?>">

**Comment by ifNoob** [comment]
`<span class="entry-meta_items entry-meta_updated<?php echo $meta_hidden_update; ?>">`
オット!。codeで投稿し忘れ...。

**Comment by kurudrive** [comment]
`<span class="entry-meta_items entry-meta_updated<?php echo $meta_hidden_update; ?>">`

どこの部分がおかしいですか？

**Comment by ifNoob** [comment]
最後の部分でのquotation 忘れですがdebug中に此方が消したかも知れません...。
`?>>/`

**Comment by kurudrive** [comment]
`?>">` で正しいかと（・ｗ・

**Comment by ifNoob** [comment]
すいません....。

**Comment by kurudrive** [comment]
パンくずのschema対応しましたので本件closeします。
他の箇所あれば別issueでよろしくお願いいたします。
