### ISSUE TITLE
breadcrumb.php のフィルターフックが消失？

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/Lightning#306]
以前存在した `apply_filters( 'lightning_panListHtml', $panListHtml ) );`が最新版では存在しないため弊害が出ているようです。

https://vws.vektor-inc.co.jp/forums/topic/%e6%a4%9c%e7%b4%a2%e7%b5%90%e6%9e%9c%e3%81%ae%e3%83%91%e3%83%b3%e3%81%8f%e3%81%9a%e3%83%aa%e3%82%b9%e3%83%88%e3%82%92%e5%a4%89%e6%9b%b4%e3%81%97%e3%81%9f%e3%81%84

以前のように設置するなり、代替を作るなりしたほうが良いかもしれません。

**Comment by kurudrive** [comment]
おや、基本フィルターフックの削除はしないはずなのですが...確認します。

**Comment by kurudrive** [comment]
修正済みにつき本件closeします。
