### ISSUE TITLE
要望

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/Lightning#313]
以下２点を要望いたします。可能ならば対応をお願いします。
①コメントテンプレートを`</article>`ないしはループ終了の下に移動（分離したい）
②`<div class="<?php lightning_the_class_name( 'sideSection' ); ?>">`～`</div><!-- [ /.subSection ] -->`を sidebar.php シリーズに同梱

**Comment by kurudrive** [comment]
> ①コメントテンプレートを</article>ないしはループ終了の下に移動（分離したい）

これは

* 長年これで来たので変更するとCSSでカスタマイズした人が困る事になる
* twenty-twenty 系なども article内なので先人のセオリーに乗っておいた方が無難かと

> ②<div class="<?php lightning_the_class_name( 'sideSection' ); ?>">～</div>を sidebar.php シリーズに同梱

あぁ...これは...ですよねー...
僕も変更したいとは思うのですが、やはり子テーマで single.php や sidebar.php をカスタマイズしている人の影響も大きいのでこのままいきたいと思います。

ご要望に添えずすみません (￣人￣)
