### ISSUE TITLE
プラグイン Download Manager のデザイン崩れ

### ISSUE THREAD

**Issue by matumatu333** [vektor-inc/Lightning#314]
左右にすき間ができてしまっているようですので、ご確認ください
Download ManagerでのLink TemplateにDefaultTemplate（old）を使用

以前にもデザイン崩れがあったようなので、相性が悪いのかもしれません（使用している他のテーマでは大丈夫です）

2019年6月11日 / 最終更新日 : 2019年6月11日
Lightning 6.13.5 / Lightning Pro 1.3.7 の変更について
プラグイン Download Manager の仕様変更により、ダウンロード部分の表示が崩れるため調整いたしました

**Comment by rick-addison** [comment]
Lightning では下記 3 つのスクリプトは標準装備しているので、
Downloads > Setting > User Interface > Disable Style & Script
から下記 3 つのスクリプトを無効化してみてください。

- Bootstrap JS
-  Bootstrap CSS
-  Font Awesome

あと、外観 > カスタマイズ > Lightning デザイン設定  のスキンの設定において、
Origin を選択している場合は Active Bootstrap Version は Bootstrap 3 を選択し、
Origin II を選択している場合は Active Bootstrap Version は Bootstrap 4 を選択してみてください。

**Comment by matumatu333** [comment]
回答ありがとうございました。
読みながら、どこのファイルのコードを書き換えるか、すっと悩んでたのですが、単純にプラグインの設定だったんですね。
Bootstrap Version のバージョンを合わせたら、うまくいきました。
テーマの問題ではなくて、プラグインの設定だったという単純なことに気づきませんでした。
ありがとうございました。
