### ISSUE TITLE
レスポンシブ時のメニューアイコンが表示されない

### ISSUE THREAD

**Issue by nehiro** [vektor-inc/Lightning#315]
メニューの開閉は可能で四角の枠も表示されているのですが、ハンバーガーと×のアイコンが表示されません。

**Comment by kurudrive** [comment]
https://demo-ja.lightning.nagoya/

テーマのバージョンはいくつですか？
デザインスキンは何を使っていますか？

**Comment by nehiro** [comment]
テーマ：7.6.3
デザインスキン：origin　で、
WordPress 5.3.2　です。

**Comment by kurudrive** [comment]
https://demo-ja.lightning.nagoya/

↑ このサイトを見てアイコンは表示されますか？

**Comment by nehiro** [comment]
表示されます！

**Comment by kurudrive** [comment]
該当URLは貼れますか？

サーバー側でsvgファイルの使用が許可されているか確認してください。 ←たぶんこれ

**Comment by nehiro** [comment]
ありがとうございます！許可したら表示されました！

ご迷惑をおかけしました。

**Comment by kurudrive** [comment]
|・ｗ・）ｂ

|彡 ｻｯ!
