### ISSUE TITLE
IE11にてサイトロゴとヘッダーナビゲーションが横並びにならない

### ISSUE THREAD

**Issue by tsuchida** [vektor-inc/Lightning#321]
サイトロゴとヘッダーナビゲーションは横並びになるのが正しいのかと思いますが、IE11ではロゴの下部にヘッダーナビゲーションが配置されてしまうようです。

![スクリーンショット 2020-01-23 15 51 08](https://user-images.githubusercontent.com/3775431/72962671-51190780-3df8-11ea-8391-88ab01190dd6.png)

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/Lightning/pull/322/commits/f0a36c3f33061e06a965be75da5a88492b95a7a3

**Comment by kurudrive** [comment]
ご報告ありがとうございました。
アップデートしてご確認ください。
