### ISSUE TITLE
comments title の翻訳バグ

### ISSUE THREAD

**Issue by kiyopong** [vektor-inc/Lightning#326]
コメントが、常に1件と出ています。

wp-content/languages/lightning-ja.po
を確認しました。

誤：&ldquo;%2$s&rdquo; に対して1件のコメントがあります。
正：&ldquo;%2$s&rdquo; に対して%1$s件のコメントがあります。

と、直して使用しております。

**Comment by kurudrive** [comment]
報告ありがとうございます。
修正しました。

https://translate.wordpress.org/projects/wp-themes/lightning/ja/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=current&page=11
