### ISSUE TITLE
fontawesomeのアイコンが全く表示されなくなりました

### ISSUE THREAD

**Issue by teke3** [vektor-inc/Lightning#349]
カスタマイズ画面では、fontawesomeのアイコンが表示されるものの、カスタマイズを終えるとすべてが消えています。
対応方法はありますでしょうか。

[https://pocketmotors.net/](https://pocketmotors.net/)
↑
こちらのページになります。

**Comment by kurudrive** [comment]
今こちらで見た限り普通に表示されているように見えますがどこの事ですか？

**Comment by teke3** [comment]
すみません、プラグインが原因だってようで停止したら直りました。
他からみても普通に見えるようで安心いたしました。
反応いただきありがとうございました。
