### ISSUE TITLE
tree shaking での file_get_content エラー対策

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#406]
Warning: file_get_contents(http://localhost:8888/wp-content/themes/lightning/assets/css/common.css): failed to open stream: Cannot assign requested address in /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-vk-css-optimize.php on line 55 
Notice: Undefined variable: exclude_clssses in /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-vk-css-optimize.php on line 35 
Fatal error: Uncaught Error: Unsupported operand types in /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-vk-css-optimize.php:35 
Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(287): VK_CSS_Optimize::css_tree_shaking_exclude(Array) #1 /var/www/html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #2 /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-css-tree-shaking.php(191): apply_filters('css_tree_shakin...', Array) #3 /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-vk-css-optimize.php(56): celtislab\CSS_tree_shaking::extended_minify(false, '

**Comment by kurudrive** [comment]
@drill-lancer developにマージしてあるのでそのままdevelopで作業でも良いです。

**Comment by drill-lancer** [comment]
これ Docker 限定っぽい感じのようです。
https://teratail.com/questions/201623

**Comment by kurudrive** [comment]
個人的に懸念しているのは

* file_get_contents() は許可されてないサーバーがあったりするので、そこで致命的なエラーにならないかどうか？
* Docker を活用したサービスとか存在して、そこで問題にならないか？（Shifterのような静的HTML変換サービスなどがAWS上にDocker起動してその上で走らせるとか）
* Dockerベースの開発環境使ってるエンジニアは多いので、そこでエラーが出るのは直した方が良いのでは？

という点で、
だだし、僕の前提知識が致命的に乏しいので、上記の点はただの素人考えで実際は問題ないという感じならそのままでOKですー。

**Comment by drill-lancer** [comment]
・Yasakani Chache でも file_get_contents() で取得している
・先述以外の方法を試しましたがどれも上手くファイルを取得できなかった（俺俺証明書が原因？）
・わざわざ Bootstrap 4 の軽量版を用意した
上記の点からしばらく様子見でいいような気がします。

**Comment by drill-lancer** [comment]
https://github.com/vektor-inc/Lightning/pull/407
これでどうですか？
私の環境だとうまくいきました。

**Comment by kurudrive** [comment]
Notice: Undefined variable: exclude_clssses in /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-vk-css-optimize.php on line 35 
Fatal error: Uncaught Error: Unsupported operand types in /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-vk-css-optimize.php:35 
Stack trace: 
#0 /var/www/html/wp-includes/class-wp-hook.php(287): VK_CSS_Optimize::css_tree_shaking_exclude(Array) 
#1 /var/www/html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) 
#2 /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-css-tree-shaking.php(191): apply_filters('css_tree_shakin...', Array) 
#3 /var/www/html/wp-content/themes/lightning/inc/vk-css-optimize/package/class-vk-css-optimize.php(77): celtislab\CSS_tree_shaking::extended_minify(false, '

file_get_content() はいけました。
他 Undefined variable とは潰せそうじゃないですかね？

**Comment by drill-lancer** [comment]
多分今回のコミットでつぶせたと思います。

**Comment by kurudrive** [comment]
残念ながらCSSがあたらなくなりましたｗ

**Comment by drill-lancer** [comment]
私の環境では普通に当たりますが・・・
もしかして追加のものですか？
