### ISSUE TITLE
ナビゲーションメニューの不具合

### ISSUE THREAD

**Issue by taki424** [vektor-inc/lightning#412]
Lightningバージョン: 11.0.1に更新いたしました。
更新してから、
ナビゲーションメニューの投稿ページ　１つのカテゴリーのページだけナビゲーションメニューがうまく表示されません。
＜strong class="gMenu_name">ここが表示されない</strong＞
＜span class="gMenu_description">ここは表示される</span＞

メニューの名前の部分が表示されません。
メニューのディスクリプションは表示されます。

投稿ページの他カテゴリー、固定ページともナビゲーションメニューが正常に表示されます。

**Comment by kurudrive** [comment]
ちょっと状況が再現しないのでわかりません。
子テーマを使っている場合は親テーマでも発生するか確認してください。
治らない場合はとりあえず該当のURLを貼ってください。

**Comment by taki424** [comment]
親テーマでも不具合生じました。今は子テーマに戻しております。
他のカテゴリーもナビゲーションメニューがうまく表示されなくなりました。

現在
正しいナビゲーションメニュー　http://f-table.jp/category/trial/
うまく表示されないナビゲーションメニュー　http://f-table.jp/category/information/

**Comment by kurudrive** [comment]
う〜ん、メニューに関連するようなところは今回触っていないはずなのですが、
下記から 10.2に戻したら治りますか？

https://wordpress.org/themes/download/lightning.10.2.0.zip?nostats=1

**Comment by drill-lancer** [comment]
「特定カテゴリのみ」という点がおかしいですね。
キャッシュプラグイン や CDN 等は利用されていますか？

**Comment by taki424** [comment]
10.2にしてみましたが、やはりナビゲーションメニューの不具合があります。
更新してからというのでなかったようです。
以前からなっていたのですが、気づかなかっただけだったようです。

**Comment by kurudrive** [comment]
内容的にテーマの不具合かどうかわかりかねるので一応バックアップをとった上で

・プラグインを全て止めたら正常に表示されるかどうか？
・テーマを変更したら改善するかどうか？

を確認してください。

**Comment by taki424** [comment]
分かりました。やってみます。

**Comment by kurudrive** [comment]
一旦 close します。
また何かありましたら改めて投稿よろしくお願いいたします。
