### ISSUE TITLE
サイドメニューの挙動不具合

### ISSUE THREAD

**Issue by kunisaki1986** [vektor-inc/lightning#413]
最新verにアップグレードしたらサイドバナーがスクロール時に移動するようになりました。
テーマをダウングレードしたら解消されるのでテーマの問題かと思います。

https://koneta.nifty.com/koneta_detail/170519000294_1.htm

こちら解消法についてご教授いただいてもよろしいでしょうか？

**Comment by drill-lancer** [comment]
外観 ＞ カスタマイズ ＞Lightning レイアウト設定 のLightning レイアウト設定 の「サイドバー固定設定」から変更してみてください。

**Comment by kunisaki1986** [comment]
ありがとうございます。
解消できました。
