### ISSUE TITLE
lightning.min.jsに値が不明

### ISSUE THREAD

**Issue by ifNoob** [vektor-inc/lightning#415]
var n = e.clientHeight;
<header class="navbar siteHeader">部、デフォルト高さサイズではなく大きく変更した場合、
n 値が正確な数値を取れない。それにより直下のタイトル部***数値が正確でない値を出力してしまう。
<div class="section page-header" style="margin-top: ***px;">

CSSにて、追加 .navbar.siteHeader { height: ***px } とすれば良いが、根本的にvar n = e.clientHeight;の値が、不明な値を吐き出すので汚染されているかも知れない。

**Comment by kurudrive** [comment]
ご報告ありがとうございます。
症状が発生する検証手順をよろしくお願いいたします。

**Comment by ifNoob** [comment]
グローバルメニューを、デフォルトサイズ(高)から大幅に変更した場合(例:高さ200px等)、
<div class="section page-header">タイトル部がLightning.jsコントロールにて隠れる。また、
<div class="section page-header" style="margin-top: 126px;">　<- 126px が何処からの不明値が入る
タイトル隠れは一旦スクロール後("margin-top: 200px;)正常な数値へ。

尚、デフォルトグローバルメニューサイズの場合はLightning.jsコントロールではstyle="***"は出ない。
<div class="section page-header">

**Comment by kurudrive** [comment]
現行版で問題が目視されないので一旦close
