### ISSUE TITLE
サイドバーを固定すると、IE11でスクロールした際、サイドバーがメインコンテンツに重なる

### ISSUE THREAD

**Issue by Namutaro** [vektor-inc/lightning#419]
Lightningレイアウト設定でサイドバーを固定にすると、IE11で表示してスクロールした際に、サイドバーがメインコンテンツに重なって表示されるようになります。

**Comment by kurudrive** [comment]
恐れ入りますが IE 11 は対応しておりません。
サイドバー固定を解除するか、修正コードをプルリクエストいただければ確認の上マージさせていただきます。

**Comment by kurudrive** [comment]
すみません、IE11に対応していると他の便利な実装に非常に大きな足かせとなるため、既にマイクロソフト自身も非推奨としているブラウザなので対応は予定しておりません。

https://vws.vektor-inc.co.jp/forums/topic/internet-exploler-11%e3%81%a7%e3%81%ae%e8%a1%a8%e7%a4%ba%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6

ご要望にお応えしたい気持ちは大きいのですが、デメリットが大きすぎてLightningが他のテーマに大きく遅れをとる要因となるため、IEが対応外である事は2年近く前から記載させていただいておりますが、今後本格的に対応を停止させていただきます。
何卒ご理解のほどよろしくお願いいたします。

**Comment by Namutaro** [comment]
IE11は非対応であることを見落としておりました。
大変失礼いたしました。
申し訳ございません。

アクセスログを見るとIE11からのアクセスがいまだに2割近くあり、当方も困っています。
MicrosoftさんにはIE11を完全廃止していただきたいところです。

**Comment by kurudrive** [comment]
2割ですかー・・・難しいですねぇ・・・。
ただ、我々製作者が対応してしまうからIEユーザーが自分の使用しているブラウザに問題がある事をいつまでたっても認識せずに乗り換えが進まない面もあるので、やはり心を鬼にしてそのままいきたいと思います...。
そうですね、ExUnit側でIEユーザーに警告を出す機能を追加します！

**Comment by drill-lancer** [comment]
ついでに 旧 Edge ( chromium 出ない方 ) も警告出しますか？

**Comment by kurudrive** [comment]
@drill-lancer 
いやー、うーんそこはまだいいんじゃないかな。
IE11はこれ入れればそのまま使えるかと。
https://github.com/vektor-inc/vk-ie-alert/blob/master/vk-ie-alert.php

**Comment by Namutaro** [comment]
魅力的な機能ですね…すごく魅力的。

**Comment by kurudrive** [comment]
実装済みにつき close
