### ISSUE TITLE
右サイドバーの不具合『スクロールをするとコンテンツの前面に表示される』

### ISSUE THREAD

**Issue by MakotoHasegawa45** [vektor-inc/lightning#422]
Lightning バージョン: 11.4.5 にアップデートをいたしましたところ、右サイドバーに不具合が発生するようになりました。
不具合の詳細『スクロールをするとコンテンツの前面に表示される』

こちらの不具合はスマートフォンでは発生いたしません。
パソコンのみ発生いたします。

以下のURLが該当するホームページです。

https://central-noise-voice.school/

どのようにしたら直りますでしょうか。
お手数をおかけいたしまして誠に申し訳ございません。
どうか、ご教示ください。

**Comment by kurudrive** [comment]
まずは高速化関連のプラグインを停止してください。

**Comment by kurudrive** [comment]
その前に外観 > カスタマイズ > Lightningデザイン設定 から デザインスキンを OriginIIに変更してください。

**Comment by MakotoHasegawa45** [comment]
ご返信くださいまして、深謝申し上げます。

早速、kurudrive様のご教示の通りに行いましたところ、右サイドバーの不具合が直りました。
この度は、ご多忙のところ、ご教示くださいまして、本当にありがとうございます。
