### ISSUE TITLE
プラグインWordPress Download Managerで日本語を使用するとレイアウトが崩れる

### ISSUE THREAD

**Issue by kanaxpon** [vektor-inc/lightning#444]
lightningのテーマ使用時にて、WordPress Download Managerを使った際に
ダウンロードのタイトル名を一度でも日本語を使用するとタイトル名が
右いっぱいまでいかず途中で改行してしてしまいます。

新規作成の時点で英語を使用するとその現象は発生せず
一度でも日本語名を使用した場合途中で改行してしまいます。
ちなみに、lightning以外のテーマではその現象はなかったため
テーマ自身の問題なのかなと思っております。

よろしくお願い致します。

**Comment by drill-lancer** [comment]
WordPress Download Manager の件は過去にもいくつか事例がありまして・・・
とりあえず下記を読んだ上で設定をお試し願いますでしょうか？
https://github.com/vektor-inc/lightning/issues/314

**Comment by kanaxpon** [comment]
回答ありがとうございます。
#314 の件も試してみたんですがBootstrapのバージョンと記載の3つのスプリクトを無効化してもずれているんですよね…。

**Comment by drill-lancer** [comment]
ちょっと奥が深そうな気がします。

正直言って実際にサイトを見たほうが解決が早まりそうな気がします。
・・・というわけでサイトの URL を拝借することは可能でしょうか？

**Comment by kanaxpon** [comment]
こちらのページで使用しております。
よろしくお願いします。
https://www.hayashidera.com/products/pdcath/download/

**Comment by kurudrive** [comment]
本件対応いたしました。
おそらく 12.6.0 で大丈夫だと思います。
