### ISSUE TITLE
カラムの内容が本文に重なって表示される

### ISSUE THREAD

**Issue by wanokizuna** [vektor-inc/lightning#454]
ページの右側に表示するようにしているメニュー画面が、一部のブラウザでは、本文に重なって表示されてしまうようです。
非対称のブラウザのみ、メニューを表示しない方法はあるでしょうか。

**Comment by kurudrive** [comment]
非表示にする方法はありません。
外観 > カスタマイズ > Lightning レイアウト設定 > サイドバー固定 で固定しない に設定してください。

ただ、IEはもうWordPress自体も対応を終了しており、そこを固定にしなかったとしても色が反映されないなどどんどん正常に表示されない範囲は増えていきます。
