### ISSUE TITLE
スライドショーがChromeで動作しない

### ISSUE THREAD

**Issue by sohsohsoh** [vektor-inc/lightning#473]
Wordpress初心者です。

マニュアル通りに画像をスライドショーに設定したのですが、
WindowsEdgeでは正常に動作するのに、
メインで使用するChromeでは全く反映がされていません。

ググって調べてみても確証のある情報にはたどり着けず、
解消方法をご存知の方がいらしたら、ぜひお願い致します。

**Comment by kurudrive** [comment]
該当サイトのURLを貼れませんか？

**Comment by sohsohsoh** [comment]
コメント頂いたところすみません、解決しました！

**Comment by sohsohsoh** [comment]
どうやら、画像URLがhttpsではなくhttpのまま保存されていたのが原因のようでした。
