### ISSUE TITLE
Lightning Pro

### ISSUE THREAD

**Issue by kmisoo** [vektor-inc/lightning#478]
Lighting Pro で
テーマ-カスタマイズ
が下記のエラーで最近表示しなくなってしまいました（最近、特に中身は編集してません）。

エラー詳細
===============
エラータイプ E_COMPILE_ERROR が /var/www/html/wp/wp-content/themes/lightning-pro/inc/customize/customize.php ファイルの 13 行目で発生しました。 エラーメッセージ: Cannot declare class Custom_Text_Control, because the name is already in use

ソースを調べると、Custom_Text_Control　は、　VK All in One Expansion Unit でも定義しているようなのですが。
とりあえず、テーマを Lightning に変更して（こちらだとエラーは出ない）事なきを得ています。
バージョンは以下の通りです。

WordPress バーション5.5.3
現在のテーマ: Lightning Pro (バージョン 0.8.0)
現在のプラグイン:  VK All in One Expansion Unit  9.48.1.0
PHP バージョン7.2.34

急いでませんが、よろしかったらご確認して頂かると助かります。
（Lightning Proの方がデザインがきれいなので）
よろしくお願いいたします。

**Comment by kurudrive** [comment]
@kmisoo 
ご報告ありがとうございます。ちょっと症状が再現しないのですが、他に有効化されている弊社のプラグインは何がありますか？

**Comment by kurudrive** [comment]
8.0.0でなくて0.8.0ですか？

**Comment by kmisoo** [comment]
御社のプラグインは以下になります。
BizVektor FooterPowerdDelete
BizVektor Theme Updater
VK All in One Expansion Unit

Lighting Proが年度更新ランセンスだということを認識してなくて、バージョンが古いままになってました。
近日中にライセンスを新規購入して、バージョンを最新にしてみます。

**Comment by kurudrive** [comment]
1系以前はアップデートシステムにライセンス認証関連がありませんので、
ご購入の際は 更新ライセンスではなく通常版をご購入検討よろしくお願いいたします。
