### ISSUE TITLE
日本語翻訳誤り

### ISSUE THREAD

**Issue by BeJf86** [vektor-inc/lightning#520]
投稿ページ自動表示ウィジェットの翻訳に誤りがありました。
lightning-ja.po
line 816

#: sidebar-post.php:66
msgid "Archive"
msgstr "アーカイブ化"

**Comment by kurudrive** [comment]
プロ版ですか？無料版ですか？

**Comment by kurudrive** [comment]
報告ありがとうございます。修正しました。
無料版の翻訳修正は以下から修正リクエストをする事ができます。
https://translate.wordpress.org/projects/wp-themes/lightning/ja/default/?page=14

**Comment by BeJf86** [comment]
迅速なご対応ありがとうございます!
