### ISSUE TITLE
サイドバー(共通)の場合にトップページに表示がされない

### ISSUE THREAD

**Issue by Hideo-Ninomiya** [vektor-inc/lightning#541]
共通上部のサイドバーウイジェットを設定した場合に、トップページのサイドバーに表示がされない。
プレビューでは正しく表示されるが、本番環境では表示がされない。

**Comment by kurudrive** [comment]
外観 > カスタマイズ > Lighting レイアウト設定 のトップページは２カラムになっていますか？

**Comment by Hideo-Ninomiya** [comment]
特に変更はしていないので設定は1カラムと思われます。見た目には2カラムになっているように見えます。

**Comment by kurudrive** [comment]
> 特に変更はしていないので設定は1カラムと思われます。

今の設定がどうなっているのかによって挙動がかわるので、実際どういう設定になっているのかがわからないと仕様通りの表示をしているのか不具合なのかがわかりません。

外観 > カスタマイズ > Lighting レイアウト設定パネルでトップページのカラム数を指定して、それと合致したカラム数になるか確認よろしくお願いいたします。

**Comment by Hideo-Ninomiya** [comment]
失礼しました。Lightningレイアウト設定パネルのトップページは｢指定なし｣になっています。因みに、Wordpressのバージョンは5.6.2になっています。

**Comment by kurudrive** [comment]
指定なしの場合は本体の仕様変更によって変動しますので、２カラム希望の場合は２カラムに指定してください。
最新版のLightingで２カラムに指定しても２カラムにならない場合は不具合なので、その旨ご報告いただけると助かります。

**Comment by Hideo-Ninomiya** [comment]
ありがとうございます。2カラムに設定変更したら出るようになりました。どうもお手数をお掛けして申し訳ありませんでした。

**Comment by kurudrive** [comment]
無事に解決したようで何よりです。
今後ともLightningをよろしくお願いいたします。
