### ISSUE TITLE
Bug: Previous/Next article not displaying preview images

### ISSUE THREAD

**Issue by joshpetit** [vektor-inc/lightning#589]
Hello! I am helping a friend out with his WordPress site and we've encountered a small bug in the previous/next article widget at the bottom of posts.
[here](https://twonieproject.com/?p=850#post-772) is the site with an example of the missing next/previous images. 

I played with the HTML a bit and after removing these classes from the image tag:
```
vk_post_imgOuter_img 
card-img card-img-use-bg
```
The images seemed to work fine. I was considering altering the PHP to just do that but couldn't find where these classes are added to the image tag. Either way, though I think it'd make more sense to ask if you guys had an idea on why this is happening.

I compared the HTML to that on the demo site [here](https://demo.lightning.nagoya/?p=170#post-217) and it seemed to be the same. Any idea why it is not working for us?

Problemed Section:

![image](https://user-images.githubusercontent.com/59021155/114543701-8a20e000-9c27-11eb-8307-4874f3629f7f.png)

**Comment by kurudrive** [comment]
@joshpetit 

Hellow :)

Please try 
Jetpack > site accelerator > image spped up > turn off

**Comment by joshpetit** [comment]
Nice, thanks! That fixed it. Thanks a lot.
