### ISSUE TITLE
ドメイン直下にインストールしていない場合に style.css の読み込みが404になると思われる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#592]
https://vws.vektor-inc.co.jp/forums/topic/g3-%e3%83%87%e3%83%99%e3%83%ad%e3%83%83%e3%83%91%e3%83%bc%e3%83%84%e3%83%bc%e3%83%ab%e3%82%a8%e3%83%a9%e3%83%bc%e3%80%80404

**Comment by kurudrive** [comment]
@shimotmk 

これG3の特殊な処理を把握しないと修正が難しい気もするので、
症状確認だけで後は僕対応でも良いっす。

まぁG3がどんな処理してるのか調べる意味で対応して貰ってもOKですが（・ｗ・

**Comment by shimotmk** [comment]
@kurudrive

承知いたしました
お願いします！

G3がどんな処理してるのかは確認します！

**Comment by kurudrive** [comment]
確認したところ不具合発生せず。
現状でまったく問題ないはず。
