### ISSUE TITLE
ブロックボタン(WPのデフォルト)の黒背景に黒文字になっている

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/lightning#593]
![block-button](https://user-images.githubusercontent.com/4631838/114685522-ea5d7200-9d4c-11eb-8b06-f1f81404ca7b.jpg)

Bootstrapのリンク色(黒)が反映されているかも？
編集画面では正常(白)

**Comment by kurudrive** [comment]
おや？これは再現しなかったのですがG3です？

**Comment by sysbird** [comment]
> おや？これは再現しなかったのですがG3です？

最新バージョンで再現しません
ProでないLightningでG3でなかったですが、
閉じます！
