### ISSUE TITLE
【G3】スライダーの表示・非表示を切り替えるフックがほしい【VideoUnit】

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/lightning#595]
https://github.com/vektor-inc/lightning/blob/7716183fe0d74023944c3d85163e7d1264d342f1/template-parts/slide-bs4.php#L2
https://github.com/vektor-inc/lightning-video-unit/blob/a31fbd39e8cdf2e6f9cfa3c1347def02f817c691/lightning-video-unit.php#L70

**Comment by drill-lancer** [comment]
@kurudrive
上記の件 Video Unit 側で G3 スライダーのオプション値をいじっても構わない場合、なかったことにできますがいかが致しましょう？

**Comment by kurudrive** [comment]
@drill-lancer 
Video Unit 側で G3 のオプション値変更する分には構いません。
ただ、カスタマイズ画面での操作でlightning_theme_optionsを書き換えると、保存処理タイミングの問題でして意図した保存されるかやや心配なので、実装後の動作確認よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
今考えたらなんか危険な香りがしてきたので、フックで対応したいと思います。
（カスタマイザー側で復活可能なので予期せぬバグを引き起こしそう・・・）
フック名は lightning_default_slide_display 続投で OK ですか？

**Comment by drill-lancer** [comment]
フックを追加できれば対応可能なところまで作業は済んでます。

**Comment by kurudrive** [comment]
G2以前で存在してるなら同じフック名でOKです。

**Comment by drill-lancer** [comment]
@kurudrive 
プルリク送っておきました。
https://github.com/vektor-inc/lightning/pull/596
