### ISSUE TITLE
フロー内に設置している画像が枠からはみ出てしまう

### ISSUE THREAD

**Issue by kaorock72** [vektor-inc/lightning#598]
フロー内に設置している画像が枠からはみ出てしまいます。
VK Blocks側なのかどうか？よく分からず、、
ひとまずこちらにissueしました。

WordPress 5.7.1
Lightning14.0.7
VK Blocks1.3.1

https://demo.dev3.biz/lightning-g3/sample-design/vk-blocks-free/

<img width="765" alt="スクリーンショット 2021-04-20 22 24 15" src="https://user-images.githubusercontent.com/59037734/115407202-cc02e500-a22a-11eb-8fb0-162cd24623ff.png">

以下のサイトでは正常

WordPress 5.7.1
Lightning13.8.13
VK Blocks1.3.1 

https://demo-ja.lightning.nagoya/sample-design/vk-blocks-free/
<img width="482" alt="スクリーンショット 2021-04-20 22 24 33" src="https://user-images.githubusercontent.com/59037734/115407256-d45b2000-a22a-11eb-9ade-b698fae77a24.png">

**Comment by kurudrive** [comment]
@kaorock72 修正しました。
Lightning の g3/main ブランチをプルするか、14.0.8 以降アップ（本日夕方予定）したら確認よろしくお願いいたします。

**Comment by kaorock72** [comment]
@kurudrive ありがとうございます！了解です

**Comment by kaorock72** [comment]
14.0.9にアップして正常に表示されました、ありがとうございました！
