### ISSUE TITLE
G3 トップページにブログカードって出るようにならないんだっけ？

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/lightning#601]
[元となるタスクnotion](https://www.notion.so/G3-b6d77d5503d64af4843e120a83fe4182
)
- [ ]  Lightning g3/main
- [ ]  Lightning Pro
- [ ]  Katawara

### カードにならない例

![_2021-04-08_14 39 16](https://user-images.githubusercontent.com/42362903/115676350-79403f00-a38a-11eb-99b2-442b8fdfeb4e.png)

-  Lightning g3/main
-  Lightning Pro
- Katawara

全てでブログカードにはならない

Written by Tomohiro Hirakawa Start

```html
<figure class="wp-block-embed is-type-wp-embed is-provider-wordpressとかパソコンとか wp-block-embed-wordpressとかパソコンとか">
	<div class="wp-block-embed__wrapper">
		<blockquote class="wp-embedded-content" data-secret="mENIp1Llbx">
			<a href="https://www.drill-lancer.com/wd_4tb_hdd_and_outer_case.html">WD Blue 4TB の HDD と外付けケースを買いました。</a>
		</blockquote>
		<iframe loading="lazy" class="wp-embedded-content" sandbox="allow-scripts" security="restricted" style="position: absolute; clip: rect(1px, 1px, 1px, 1px);" title="“WD Blue 4TB の HDD と外付けケースを買いました。” — WordPressとかパソコンとか" src="https://www.drill-lancer.com/wd_4tb_hdd_and_outer_case.html/embed#?secret=mENIp1Llbx" data-secret="mENIp1Llbx" width="600" height="338" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
	</div>
</figure>
```

上記のような HTML がデフォルトでは出力されるのですがその中の loading="lazy" が影響しているようです。

公式でも loading="lazy" ついて触れてるようでした

[https://make.wordpress.org/core/2021/02/19/lazy-loading-iframes-in-5-7/](https://make.wordpress.org/core/2021/02/19/lazy-loading-iframes-in-5-7/)

トップページを埋め込もうとするとページ全体を iframe で取得しようとしている模様です。

Written by Tomohiro Hirakawa End

**Comment by shimotmk** [comment]
@kurudrive 
こちらのタスクについて一度、進捗と相談です
該当コード
https://github.com/vektor-inc/lightning/compare/g3/main...try/vk-wp-oembed-blog-card

一旦ブログカードが動く形にはなりました

・WordPressが生成するブログカードのHTMLを調整
・WordPressがブログカードを生成出来ない時の処理
・URLリンクにした際の処理
を確認しました


以下の点で少しご相談したいです。
・cssは私が考えて作って大丈夫でしょうか？
(今は一旦Horizontalカードを使用しています)
・仮でLightningの中で作っていますが他のディレクトリに移動したほうが良いでしょうか？

また他の書き方を参考に作っているのですが、もしおかしな箇所がありましたらご指摘いただきたいです

よろしくお願いします

**Comment by kurudrive** [comment]
@shimotmk 
ありがとうございます！
以下よろしくお願いいたします。

1.  /inc/vk-wp-oembed-blog-card/ ディレクトリを作成して、その中に移動

lightning/_g3/inc/vk-wp-oembed-blog-card/
lightning/_g3/inc/vk-wp-oembed-blog-card/config.php
lightning/_g3/inc/vk-wp-oembed-blog-card/package/class-vk-wp-oembed-blog-card.php

2. class-vk-wp-oembed-blog-card.php の中身を class化 VK_WP_Oembed_Blog_Card クラス

3. function vk_get_blog_card の content の部分だけ一つのメソッドに分割
4. ってあれ、function vk_get_blog_card の $content 以外 return されてないけどいいの（・ｗ・？

**Comment by shimotmk** [comment]
@kurudrive 
お疲れさまです！

テストコードも書いたのですが
・WordPressで作られたサイト トップページ
・WordPressで作られたサイト 下層ページ
・WordPressでは作られていないサイト
・外部からの接続を拒否しているサイト
・HTMLの文字コードが異なるサイト
でのブログカードまたはURLの実装、表示確認しました

一旦私が思いつく実装は行ったのですが、もしおかしな箇所や不足している所がありましたらご指摘いただきたいです
よろしくお願いします

**Comment by kurudrive** [comment]
@shimotmk 

実装ありがとうございました。
非常に素晴らしい実装だったと思います。

以下フィードバック及び修正確認依頼点です。

- [ ] ローカルのサイト内記事がブログカードにならないようでした（・ｗ・；

![幅確認-Lightning](https://user-images.githubusercontent.com/3272660/119379602-a7eb6580-bcfa-11eb-93a3-07e36ee2c5ea.png)

- [ ] クラス内のメソッド名は vk_embed なのは既にクラス名でわかってるので省略した方がすっきりすると思いまする。
https://github.com/vektor-inc/lightning/commit/fb4ec142c26f642d88ce89a72c8e8e32801a5e4d

- [ ] 要相談 : 出力のHTMLを標準の埋め込みのHTMLに合わせた方が別途CSS書かなくて良いんじゃね？

- [ ] 画像がないケースが想定されるので、画像は右にしておいた方が、画像のあるサイト、無いサイトを積んだ時に見た目がガタガタしないので右にしました。
- [ ] 今のブランチのHTMLがイキなら画像がない時に識別要class付けてCSS書き足す必要がある
- [ ] 補足 : 現状sassがビルドできるような設定はしてないので、今のブランチのHTML部分をそのままイキならCSSの調整はあとで僕がやりまするん。

**Comment by shimotmk** [comment]
@kurudrive 
フィードバック、ご確認ありがとうございます！！！

ローカルのサイト内記事、調査します！😨

クラス名、HTMLの構造は確かにご指摘いただいた形の方がシンプルでわかりやすいと思いました！

**Comment by shimotmk** [comment]
@kurudrive 
お疲れさまです！
ブログカードの修正点がおおよそ完成しました
https://github.com/vektor-inc/lightning/pull/659/files

> 出力のHTMLを標準の埋め込みのHTMLに合わせる

こちらですが埋め込み先によって標準の埋め込みの形が変わります
大きく表示されるパターン(Pub)
https://ja.wordpress.org/themes/lightning/embed/
画像が右のパターンフォントサイズなどが少し異なるLightning
/assets/css/wp-embed.cssにCSSが追加されていました
https://lightning.nagoya/ja/feature/embed
Katawara
https://www.vektor-inc.co.jp/post/updraftplus/embed/
画像が左のパターン
https://tomolog.org/contact-form7-error/embed/

そしてWordPressが作った埋め込みHTMLに対して埋め込みサイトがそれをiframeで読み込む形になります

post_idを持つものとそうでないもので埋め込みが生成される様です
https://github.com/WordPress/WordPress/blob/master/wp-includes/embed.php#L633

なので、ひとまず右側に画像があるパターンにHTMLをあわせて実装しました

お時間ある時に確認していただければと思います
よろしくお願いします🙇‍♂️

**Comment by kurudrive** [comment]
@shimotmk 添付の状態になりましたのでまた確認よろしくお願いいたします ＞＜

![ブログカード-デザイン要素サンプル-Lightning](https://user-images.githubusercontent.com/3272660/120460136-cc6ad000-c3d3-11eb-8f98-08c66d2b7544.png)

**Comment by shimotmk** [comment]
@kurudrive 
これは初歩的なミスで手間をおかけしてしまい申し訳ないです🙏
内部リンクをURLだけ取得するように調整しました
https://github.com/vektor-inc/lightning/pull/659/commits/1716c58846fb3757ea74d1c823ec006a832586c8

**Comment by kurudrive** [comment]
@shimotmk こ...これも欲しいデス！＞人＜

![ブログカード-デザイン要素サンプル-Lightning (1)](https://user-images.githubusercontent.com/3272660/120677811-6d3fb500-c4d2-11eb-9ebd-cc23c4cd9f7d.png)

**Comment by shimotmk** [comment]
@kurudrive 
ブログカードのファビコン、タイトルの追加しました
https://github.com/vektor-inc/lightning/pull/659

[現状sassがビルドできるような設定はしてない](https://github.com/vektor-inc/lightning/issues/601#issuecomment-847190436
)とのことなので簡易的ですがcssファイルに直接書きました...

以下、仕様の確認と相談です(長いですが見てほしいです..申し訳ないです🙏)

## カード右下の共有アイコンの実装方法について
トップページ以外の内部リンクでpost_idが取得できる場合はWordPress標準が出力するブログカードに
それ以外の場合のものはvk_blog_card_htmlで生成したものを表示する形にしました

外部のサイトは一旦アイコンをクリックしたらURLがクリップボードにコピーされるようにしました
WordPress標準のJavaScrtiptを持ってくればいいのではとも思ったのですがCSSなども一致させるとブログカード
とは関係のない部分まで影響が出てしまったのでこのような仕様にした次第です

## 外部のサイトも標準のブログカードのようにしたい場合
`vk_blog_card_html`のHTMLの前後に標準の実装のように`get_header( 'embed' );`、`get_footer( 'embed' );`
https://github.com/WordPress/WordPress/blob/master/wp-includes/theme-compat/embed.php
とすればそれっぽくはなりますが標準のJavaScrtiptはひとつの共有ボタンに反応するように作られているので複数貼り付けた場合などに不具合が出てしまいます

## WordPress標準のブログカードの仕様について
WordPressは埋め込まれたサイトが作るブログカードを利用してiframeで埋め込みます
iframeで読み込むのでブログカード内でHTML,CSS,JavaScrtiptがあたります
ちなみにURLに/embedをつけるとブログカード レイアウトかわかります
例：https://lightning.vektor-inc.co.jp/lightning-g3-pro-unit/embed/

## 根本の原因
トップページのカードがおかしいということでした
埋め込むサイトがブログカードを作るかどうかはpost_idを持つかどうかです
https://github.com/WordPress/WordPress/blob/master/wp-includes/embed.php#L633
トップページはpost_idが取得されてしまうが埋め込みスタイルは持たないため引用タグのように表示されます

よって埋め込むサイトでブログカードのHTMLなどを変えるためにはURLから情報を取得しなければならずWordPress標準が作るブログカードと同様のスタイルにするには少し無理があるといった状況です

どのように実装するか判断してもらいたいところですが実装方法は３つほどかなと
・今回のコードのように標準のブログカードと作ったものを分けて表示する
・他のテーマが実装しているようにWordPressデフォルトのブログカードを利用せずオリジナルのブログカード
・WordPress標準のブログカードを使用する

いかがいたしましょうか。またおかしな箇所や不足している所がありましたらご指摘、コードの修正など頂きたいです＞＜
よろしくお願いします

**Comment by kurudrive** [comment]
@shimotmk あーりがとうございますー！
確認遅くなりましてすみません。

```
・今回のコードのように標準のブログカードと作ったものを分けて表示する
・他のテーマが実装しているようにWordPressデフォルトのブログカードを利用せずオリジナルのブログカード
・WordPress標準のブログカードを使用する
```

おや？３が無理なので１か２を検討しなくてはいけないのではなくて？

**Comment by kurudrive** [comment]
@shimotmk まぁでも僕としては

* オリジナルのブログカードを利用する
* ただし、HTML構造、クラス名はできるだけ標準に近いものにする
と...言いたいけど、中途半端に揃ってると構造を勘違いしやすいからクラス名は全く独自のクラス名にしましょう。
vk-embed-card とか。

というのが落とし所かなと思います。

**Comment by kurudrive** [comment]
@shimotmk ちな css は _g3 ディレクトリで gulp すれば動きまする。

**Comment by kurudrive** [comment]
追伸 : 
各種調査・実装・確認内容の記述などすばらしいです！
最後、ベクトル的には、確認の際は「どれにしましょう？」ではなく、「選択肢としてはこれがあるけれど、個人的にはこういう理由でこれがいいと思いますけどこれで良い？」という感じで選択肢の中で自分の意見としてどれがオススメなのかを提示いただけるとパーフェクトです！

**Comment by kurudrive** [comment]
@shimotmk そしてなんだか結局最初に実装してもらったのに後戻りするような状態になった気がしてすみません...。

**Comment by shimotmk** [comment]
@kurudrive 
確認ありがとうございます！

こちらの実装方法でもう一度実装してみます！
https://github.com/vektor-inc/lightning/issues/601#issuecomment-861985620


> ・WordPress標準のブログカードを使用する

わかりずらくすみません。
こちらは共有ボタンを優先させたいなら標準のものを使うしかないかなと思い書きました

> 選択肢の中で自分の意見としてどれがオススメなのかを提示いただけるとパーフェクトです！

ありがとうございます！
今後は自分の意見も添えられるようにします！

**Comment by shimotmk** [comment]
@kurudrive 
お疲れさまです。ブログカード調整しました
https://github.com/vektor-inc/lightning/pull/659

カードのHTML,CSSは以前石川さんが作っていただいたものをベースにサイト名とファビコンを追加しました！
お時間ある時にご確認お願いします

**Comment by kurudrive** [comment]
@shimotmk 参考までに上２つのコミット軽く見といてください。
と、言っても全然致命的な話じゃないので参考程度です。

**Comment by shimotmk** [comment]
@kurudrive 
ありがとうございます！
確かにsite_url()ではなくhome_url()が正しいです🙇‍♂️
