### ISSUE TITLE
【14.0.10以降確認】Lightinig サイドバー「最近の投稿」スマホ表示の崩れ

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/lightning#604]
参考URL
https://dev3-wpml.chiakikouno.com/new-products-info-20180201/

ウィジェットの設定では「サイドバー（投稿）」を空にしていますので、自動的に　最新記事・カテゴリ・月別アーカイブが表示されています。

「最近の投稿」をスマホで見ると、画像が小さかったり、短いタイトルでも折り返されたりして見えます。

参考URLの環境
Lightningバージョン: 14.0.9　G3
スキン：G３サンプルスキンを使用

表示した環境
Mac Chrome でのスマホ表示
iPhone SE Safari

プレビューで G2に切り替えたり、G３の他のスキンに切り替えても変化がないようでした。

**Comment by kurudrive** [comment]
@ChiakiKouno 
修正しましたので 14.0.10 以降リリースしましたら確認よろしくお願いいたします。

**Comment by kurudrive** [comment]
14.0.10 アップしましたん。
https://lightning.vektor-inc.co.jp/

**Comment by ChiakiKouno** [comment]
確認遅くなりまして申し訳ないです。
バージョン14.0.14にて、修正されていることを確認しました。
早々のご対応ありがとうございました！
