### ISSUE TITLE
デモサイトのロゴをかっこよくしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#606]

**Comment by goutetsuguma** [comment]
@kurudrive 
こちらに書き出したロゴを添付いたします。
(Zoomでは上のロゴで、ということでしたので上のシンボルマークのほうでよいでしょうか)


![sample-logo01](https://user-images.githubusercontent.com/5525368/116653744-c0e64c80-a9c2-11eb-878a-f6333f97d263.png)


![sample-logo02](https://user-images.githubusercontent.com/5525368/116653765-c8a5f100-a9c2-11eb-8797-006b5b0912d2.png)

### Figmaはこちらから
https://www.figma.com/file/yscxN8j2DIMwO9fTTgiua1/sample-logo?node-id=0%3A1

**Comment by kurudrive** [comment]
かっこいい！OK！

**Comment by kaorock72** [comment]
@kurudrive @goutetsuguma ありがとございました！設置してみました。
https://demo.dev3.biz/lightning-g3/
