### ISSUE TITLE
カラーサジェスト機能？別プラグインで作るべきかもですが、色選びを迷わせない機能を考えたいです

### ISSUE THREAD

**Issue by miminari** [vektor-inc/lightning#610]
関連課題 #518

**Comment by kurudrive** [comment]
関連要望
https://vws.vektor-inc.co.jp/forums/topic/%E3%80%90%E6%A9%9F%E8%83%BD%E8%BF%BD%E5%8A%A0%E8%A6%81%E6%9C%9B%E3%80%91%E4%BB%A3%E8%A1%A8%E7%9A%84%E3%81%AA%E3%82%AB%E3%83%A9%E3%83%BC%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E3%81%AE%E7%B5%84%E3%81%BF

**Comment by kurudrive** [comment]
G3 Pro Unit のプリセットでやれない事もない & X-T9 に開発リソース回したいため close
