### ISSUE TITLE
G3 パンくずの<ol>タグが閉じていませんと出ています

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/lightning#617]
HTMLエラーチェッカーで
`<ol class="breadcrumb-list"> : タグが閉じていません`
と出ました。

Chromeの検証の画面では閉じタグが補完されて見えたのですが、HTMLチェッカーで気が付きました。
ページのソースをみるとたしかに閉じタグがありませんでした。

**Comment by kurudrive** [comment]
@ChiakiKouno なおしましたん！
