### ISSUE TITLE
固定ページでNo sidebar ( not recommended )を選択していても右側にスペースができます

### ISSUE THREAD

**Issue by shokun0803** [vektor-inc/lightning#624]
g2で自動アップデート後そのまま使用しています。
ソースコードを見ると、rowの下のdivでmainSection-col-twoが指定されているので、style.cssでwidth: 66.66667%が適用されてしまうのではないかと思われます。
divのclass指定に問題があるのか、CSSに問題があるのかは今のところ分かりません（未検証）。

**Comment by kurudrive** [comment]
g2 でも No Sidebar は使用せずに、記事の編集画面のLightnig デザイン設定 のパネルからレイアウトを設定できるようになっていますので、そちらから1カラムを選択してください。

**Comment by kurudrive** [comment]
@shokun0803 

![固定ページを編集-‹-Lightning-×-ExUnit-日本語デモ-—-WordPress](https://user-images.githubusercontent.com/3272660/118083071-3dcce980-b3f9-11eb-9da3-b307a2b26df1.png)

**Comment by kurudrive** [comment]
※ ~13 で No Sidebar で保存された場合にアップデートした時に 1カラムにならない可能性がある

- [ ] 管理画面に表示されるデータベースの更新処理が機能しない？
- [ ] ↑機能しない場合修正
- [ ] page-onecolumn.php の時を _g2/page-onecolumn.php の時のクラス名書き換え処理確認

**Comment by shokun0803** [comment]
@kurudrive 
デフォルトテンプレートでデザイン設定を1カラムにすることで、元の状態に戻すことはできました。
テンプレは変更しない方がよいですかね。
ありがとうございます。

**Comment by kurudrive** [comment]
g3で旧テンプレートは選択できなくするのでclose
