### ISSUE TITLE
【確認待ち】公開日時のDatePickerのカレンダーがはみ出てしまう

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/lightning#628]
G3/Katawaraにおいて、table td { margin: 1em } が効いていて、編集画面のセルが広がってしまい、はみ出てしまっている。
![image](https://user-images.githubusercontent.com/1535140/117776718-d0914b00-b276-11eb-9060-23aec1a45e0e.png)

**Comment by goutetsuguma** [comment]
こちら、フォーラムにてバグ報告がありましたので、優先度中にあげましたmm

**Comment by arborvitae666** [comment]
`.components-datetime__date td { padding: 0; }`
か
`table.CalendarMonth_table td { padding: 0; }`
の片方を適用すると解消されました。
よろしくお願いいたします。

**Comment by goutetsuguma** [comment]
以下のブランチで修正いたしました。
https://github.com/vektor-inc/lightning/pull/665
