### ISSUE TITLE
【確認待ち】Inspectorの見出しのfont-sizeが不揃いになっている

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/lightning#629]
本来均一のはずのInspectorの見出しの大きさが不揃い。（G3/Katawara）

![貼り付けた画像_2021_05_11_16_37](https://user-images.githubusercontent.com/1535140/117777590-b60ba180-b277-11eb-850c-513ca8ce3ed1.png)

**Comment by goutetsuguma** [comment]
editor側で読み込んでいる@import "common";　のbodyのfont-sizeが打ち消しているのが原因

@import "common";を外すと、若干編集画面とフロント画面に差が出るので、編集画面側のサイドバーに直接font-sizeを指定したほうがいい？

**Comment by goutetsuguma** [comment]
以下のブランチで修正いたしました。
https://github.com/vektor-inc/lightning/pull/665

**Comment by kurudrive** [comment]
@goutetsuguma @mthaichi ありがとうございました！
Lightning マージ＆リリース済みにつきcloseします。
