### ISSUE TITLE
ヘッダーを非表示にするとJSエラーが1件出る

### ISSUE THREAD

**Issue by miminari** [vektor-inc/lightning#631]
ヘッダーを非表示すると以下のエラーが出ます

> Uncaught TypeError: Cannot read property 'offsetHeight' of null
>     at main.js?ver=14.1.5:1
> https://lightning.vektor-inc.co.jp/wp-content/themes/lightning/_g3/assets/js/main.js?ver=14.1.5

**Comment by miminari** [comment]
@kurudrive すみません、これアサインされているのは、私の確認が必要ということですか？

**Comment by kurudrive** [comment]
@miminari いやー、とりあえず修正・リリース済みではあるのですが、
確認して貰ってからcloseするべきかどうなのかなーと思いまして保留してた感じでする０。

**Comment by kurudrive** [comment]
なので、 @miminari さん的にOKであれば close いただければ（・ｗ・ｂ

**Comment by miminari** [comment]
@kurudrive あ、なるほど。他にも同じコメントありましたね。ありがとうございます。クローズさせてもらいますー、対応ありがとうございます！

**Comment by kurudrive** [comment]
@miminari ありがとうございます！
