### ISSUE TITLE
ヘッダのスライドのアニメーションが特定ブラウザで動作しない

### ISSUE THREAD

**Issue by Hotzpring** [vektor-inc/lightning#632]
無料版Lightningです。

少し前のアップデートから、Chromeで閲覧するとヘッダのスライドショーがアニメーションしていないようです。

スライド・フェードなどの効果がなく、瞬時に切り替わっています。
IE、Edge（旧ver）では動作しています。
Chrome、Edge(Chrome ver）、Android内蔵ブラウザではアニメーションがなくなっています。

ためしに去年８月のテーマのバックアップに戻してみたところ、正常に動作していました。

https://demo-ja.lightning.nagoya/
デモサイトでも同様にアニメーションしていないので、こちらの環境の可能性は薄いと考えていますがどうでしょう。

**Comment by kurudrive** [comment]
@Hotzpring 
今 私の環境で確認する限りデモサイトでは問題なくフェードでアニメーションしています。

**Comment by Hotzpring** [comment]
@kurudrive 
ご確認ありがとうございます。手元の端末でデモサイトにアクセスしてみましたが、

・Windows10
Chrome、Firefox → X
IE→○

・Android10、Android9
Chrome→X

・Android4.4
Chrome(ver77）→X

iPad Air 14.4.1
Chrome、Safari → ○

・iPhone6 iOS 12.5.1
Chrome、Safari → X

こんな状況です。
手元の６つの端末で試して問題なく動作してたのがiPadだけ、というのはこちらだけの問題とはなかなか考えにくくて。
以前のテーマに戻せば問題なくフェードするので、最近のアップデートでどこかおかしくなっているのでは、感じています。

**Comment by kurudrive** [comment]
上記の状態は弊社のデモサイトでしょうか？

スキンは何を利用していますか？

Lightning Advanced Slider は使っていますか？
※ Lightning Advanced Slider は現在利用は非推奨です。

**Comment by Hotzpring** [comment]
@kurudrive 
デモサイトでも、公式トップ（https://lightning.nagoya/ja/）でもスライド・フェードせず瞬時切り替わりになります。
もちろん広告ブロックなどの外的要因は可能な限り排除してあります。
また、Windows7端末でChrome、Edgeで同じ状況なのを追加で確認しました。

当方のサイトではLightning Advanced Sliderは使っていません。スキンも特に使用せず初期状態のままです。

**Comment by kurudrive** [comment]
@Hotzpring 
↓ アップデートしていなかったので念の為アップデートしました。これだとどうでしょうか？
https://lightning.nagoya/ja/

**Comment by kurudrive** [comment]
※ 現状 確認事項
Android 9 Chrome 90 動作問題なし
iOS 14  Chrome 動作問題なし

**Comment by Hotzpring** [comment]
@kurudrive 
すべての端末で確認したわけではありませんが、公式サイトトップもデモサイトもフェードしませんね…。
同じ環境のAndroid9のChrome90で、Chromeを再インストールしたりいろいろ試しましたがダメです。
Windows+Chromeでも問題なく動作確認できているでしょうか。
それが大丈夫ないのであれば、私以外に特に問題にしている人がいないようですし、おそらく世の中の大部分は問題なく閲覧できていると信じます。

**Comment by kurudrive** [comment]
手持ちのWindows10 Chrome で確認した限り問題なく動作していました。

ちょっと症状が再現しないので次回月例のオンライン勉強会の時にでも症状が発生する人が出るかきいてみます。

**Comment by kurudrive** [comment]
以下 つしまさんより情報提供

---

手元の複数のWindows 10 パソコンで試したところ、スライドショーのフェード・スライドが動作しない台数の割合がけっこう多く、私のお客様のサイトもこの問題の対象なので、心配になってさらに動作状況を調べました。
調べている過程で、画面右下の [TOP に戻る] ボタンをクリックしたときにスムーススクロールしないという現象が起きていることも確認しました。
現象が起きている Windows 10 パソコンの Chrome で動作確認した結果は以下の通りです。
○：問題なし　×：問題の現象が起きる
【サイト】https://demo.dev3.biz/lightning-g3-pro/
スライド切り替え効果：○
[TOP に戻る] ボタンのスムーススクロール：×
【サイト】https://demo.dev3.biz/katawara/
スライド切り替え効果：○
[TOP に戻る] ボタンのスムーススクロール：×
【サイト】https://demo-ja.lightning.nagoya/
スライド切り替え効果：×
[TOP に戻る] ボタンのスムーススクロール：×
【サイト】https://uonuma-js.com/
スライド切り替え効果：× (フェード・スライドともに × です)
[TOP に戻る] ボタンのスムーススクロール：×
【サイト】https://yamato-shokokai.com/
スライド切り替え効果：○
[TOP に戻る] ボタンのスムーススクロール：○
このサイトは WordPress 4.9.18 / Lightning Pro 0.2.0 / Lightning Skin Fort 3.0.4 という古いバージョンのままになっています。
まとめると、以下のようになります。
■■■スライド切り替え効果について■■■
問題が起きるケース：Lightning Pro の新しいバージョン
問題が起きないケース：Lightning Pro の古いバージョン / Swiper を使っているもの (スライダーブロックも問題が起きませんでした)
■■■[TOP に戻る] ボタンについて■■■
問題が起きるケース：Lightning / Katawara の新しいバージョン
問題が起きないケース：Lightning の古いバージョン
私が確認したかんじだと、スペック低め または 古め の Windows 10 パソコンで試していただくと現象を再現できるのではないかという気がします。

**Comment by kurudrive** [comment]
@drill-lancer この件調査よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
私は「スペック低め または 古め の Windows 10 パソコン」は所持していないので再現できません。
（５年前の PC でもゲーミング PC なので今でもそこそこ通用するレベルです。）

Bootstrap のサポートブラウザリスト
https://getbootstrap.com/docs/4.6/getting-started/browsers-devices/

ブラウザのバージョンが古い or OS のバージョンが古いとインストールできるブラウザのバージョンが制限される
こういう事象が起こっているような気がします。

セキュリティの観点から考えても常に OS は最新であることが好ましいのでこの件は再度一旦保留に戻します。

**Comment by Hotzpring** [comment]
今年買ったファーウェイのWindows10のノートパソコン（Matebook D15）でエフェクトが動作していない状態です。
一概に「閲覧側の端末・ブラウザが古い」のが原因とは思えませんがどうでしょうか。

古いLightningでは問題なく動作しているので、どこかのタイミングのアップデートでJavascriptが上手く動かなくなっていると感じています。

**Comment by drill-lancer** [comment]
私の検証環境は下記のとおりです。
（設定⇒システム⇒詳細情報で確認）

【OSの情報】
エディション：Windows 10 Pro
バージョン：21H1
インストール日：‎2020/‎10/‎17 ‎土
OS ビルド：19043.985
エクスペリエンス：Windows Feature Experience Pack 120.2212.2020.0

【ハードウェア情報】
プロセッサ：Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.40 GHz
実装 RAM：32.0 GB (31.9 GB 使用可能)
グラフィック：Intel(R) HD Graphic 530 ( CPU 内蔵)・Nvidia GeForce GTX 1660 Super

**Comment by drill-lancer** [comment]
@Hotzpring
Matebook D15 の性能を調べたところスペック的には問題なさそうな気がします。
https://consumer.huawei.com/jp/laptops/matebook-d-15-amd/specs/

しかし、下記部分がひっかかってるかもしれません。

プロセッサー 
AMD Ryzen 5 3500U (2.1 GHz、最大3.7 GHz)
AMD Ryzen 7 3700U (2.3 GHz、最大4.0 GHz)

グラフィックス ( 以下 GPU )
AMD Radeon™ Vega 8 Graphics
AMD Radeon™ RX Vega 10 Graphics

というのは、AMD 製のグラフィックは Intel の内蔵 GPU やNvidia 製の GPU と比べると問題が発生しやすいという話を聞いたことがあります。引っかかるとすればそこかもしれません。

**Comment by kurudrive** [comment]
@drill-lancer 

> パソコンのリカバリー or OS の再インストール or OS のみをクリーンインストール（可能ならば）を試すと解消する可能性があります。

いや、発生台数が多そうなので、それを全ユーザーにお願いするわけにはいかないし、旧 Lightning で問題なく動作するなら Lightning 側で回避策を検討する必要があります。

Bootstrapというより Swiper との相性や、読み込みタイミングなどが関連しているのではないかなと思います。

手元の環境で再現しないので、難しいですが、手元で行うような修正検証版を用意して、
発生するユーザーに検証をお願いするしかないので、その方向でよろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
https://demo-ja.lightning.nagoya/
上記サイトでは Lightning Pro が適用されていて Lightning Advanced Slider は使用されていないため
 Bootstrap によるスライドショーが採用されています。

対馬さんも Swiper を使ったものは問題ないと言われているのでおそらく Bootstrap がネックになっているかと思われます。

**Comment by kurudrive** [comment]
@drill-lancer 

G3 は Swiper なので

```
【サイト】https://demo.dev3.biz/lightning-g3-pro/
スライド切り替え効果：○
[TOP に戻る] ボタンのスムーススクロール：×
```

という報告がひっかかるかな。

とは言え、スライド効果が動作しないのと、スムーススクロールは全く別の問題なのか...。

**Comment by drill-lancer** [comment]
@kurudrive 
スムーススクロールは Bootstrap も Swiper も関係ないはずなので別の問題だと思います。

```
【サイト】https://demo.dev3.biz/lightning-g3-pro/
スライド切り替え効果：○ ⇒ Swiper
[TOP に戻る] ボタンのスムーススクロール：×

【サイト】https://demo.dev3.biz/katawara/
スライド切り替え効果：○ ⇒ Swiper
[TOP に戻る] ボタンのスムーススクロール：×

【サイト】https://demo-ja.lightning.nagoya/
スライド切り替え効果：× ⇒ Bootstrap 4
[TOP に戻る] ボタンのスムーススクロール：×

【サイト】https://yamato-shokokai.com/
スライド切り替え効果：○ ⇒  Lightning Pro 0.2.0 であるため Bootstrap 3
[TOP に戻る] ボタンのスムーススクロール：○
```

スムーズスクロールは独自実装なのでスライダーとは切り分けて考える必要が必要があります。

**Comment by drill-lancer** [comment]
@kurudrive 
あと、Lightning を新規インストールしても初期状態ではっきりと G3 にはならないような気がします。
外観 > カスタマイズ > Lightning 機能設定にはじめてアクセスすると世代設定が空欄になってました。
なので、今回の件は G2 の疑いが濃厚なのでスライダーに関しては Bootstrap 4 がネックになってると思われます。

**Comment by drill-lancer** [comment]
@kurudrive 
> 少し前
最近 Bootstrap を 4.6 にしたり node で読み込む仕様にしたり ( Lightning Pro は同じ状態ですか？ ) したのでその影響かもしれません。

**Comment by drill-lancer** [comment]
@Hotzpring
Windows 10 の 設定 > 簡単設定 > ディスプレイ 
上記の Windows のシンプル化と個人用設定の Windows にアニメーションを表示する
にチェックを入れなかった場合再現しましたのでそのあたりの確認をお願いします。

**Comment by Hotzpring** [comment]
@drill-lancer 
Windows10PCの、「Windows にアニメーションを表示する」の設定はオフになっておりました。
オンにして試したところ、切替効果が動作するようになりました。
同様に、Androidも開発者オプションでアニメーションを切っていたため、これをオンにしたところ切替効果が動作しました。

ただ、オフのままでも古いLightningのサイトでは問題なく動作しているため、「アニメーションを切っていても今までのように動作して欲しい」というのが希望です。

こちらの環境での確認事項を記載しておきます
アニメーションオン→問題なし
アニメーションオフ＆IE→問題なし
アニメーションオフ＆Chrome＆古いLightning→問題なし
アニメーションオフ＆Chrome＆新しいLightning→動かない

**Comment by kurudrive** [comment]
> アニメーションを切っていても今までのように動作して欲しい

利用者によっては「アニメーションを切りたいと思ってオフにしているのに動作されてしまう」という"不具合"を報告される要因にもなり、一概に動作する事が正しいとは言い切れないので、現状まま close とさせていただきます。

ご意見ありがとうございました。
