### ISSUE TITLE
エディターで キーボード のスタイル追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#633]
![スクリーンショット 2021-05-14 11 49 16](https://user-images.githubusercontent.com/3272660/118214292-7082ea80-b4aa-11eb-8087-7957b32e98ed.png)

- [x] G3
- [x] G2
- [x] Lightning Pro
- [x] Katawara
- [x] X-T9

**Comment by mtdkei** [comment]
全てMergeされましたのでCloseします
