### ISSUE TITLE
子テーマ直下のstyle.cssを編集画面で読み込む？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#635]
デフォルトのテーマが読み込む仕様にしてるか確認して検討

https://vws.vektor-inc.co.jp/forums/topic/%e8%a6%8b%e5%87%ba%e3%81%97%e3%83%87%e3%82%b6%e3%82%a4%e3%83%b3%e3%80%80%e7%b7%a8%e9%9b%86%e7%94%bb%e9%9d%a2%e3%81%a7%e3%82%ad%e3%83%bc%e3%82%ab%e3%83%a9%e3%83%bc%e3%81%ab%e3%81%ab%e3%81%aa%e3%82%89

**Comment by drill-lancer** [comment]
@kurudrive 
対応するなら・・・
子テーマに editor.css を作って enqueue_block_editor_assets で読み込むか add_editor_style で読み込むか・・・
add_editor_style のほうがしてであるため強いのでそちらで読み込むのが良さそうな気がします。

ちなみに公式テーマは子テーマの CSS を一切読まない仕様になってるので参考にはならないかと・・・
（子テーマの CSS は子テーマ側で読み込ませるのが普通っぽいです。）

**Comment by drill-lancer** [comment]
唯一子テーマを参照してるのはカスタムカラーのみですね。
https://github.com/WordPress/twentytwentyone/blob/ba9f20cad89163761185c0467b346ba42541ae22/classes/class-twenty-twenty-one-custom-colors.php#L112-L117

**Comment by kurudrive** [comment]
そもそもWordPress標準が子テーマのstyle.cssを編集画面で読み込まないなら優先度は低くて良い気がス...。
