### ISSUE TITLE
セクションベースが無しの場合、コンテンツの一番外側の.site-body の左右の余白は不要なのでは？

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#641]
セクションベースが無しの場合に、コンテンツの一番外側の.site-body の左右の余白は不要なのでは？と思いissue立てました。が勘違いかもしれないので確認します

![FireShot Capture 008 - Lightning × ExUnit 日本語デモ - WEBに関する様々な問題に対応いたします - demo dev3 biz](https://user-images.githubusercontent.com/5525368/118757007-1e293b80-b8a7-11eb-8399-27d391e4b8c6.png)

```
.site-body {
    padding: ○rem 15px ○rem;
}
```

**Comment by kurudrive** [comment]
たし蟹

**Comment by oshin3** [comment]
こちらの適応以降、スマートフォンでの表示の際の左右余白が小さくなったと感じています。具体的には固定ページや投稿の本文、その中に置いた小ページリストや投稿リストなどが左右パツパツな感じです。意図した変更の場合申し訳ありませんが、ご確認いただけますと幸いです。

**Comment by kurudrive** [comment]
@oshin3 こちら意図的な変更です。
原則後からこういった変更はしないのですが、大本の設計意図と異なる余白でしたので削除しました。
余白を広くしたい場合はお大変手数ですがCSSにて調整よろしくお願いいたします。

**Comment by oshin3** [comment]
@kurudrive ご回答いただきありがとうございます。
意図的な変更ということで、スマホで端に寄りすぎないようCSSにて調整させていただきます。
大変失礼いたしました。
