### ISSUE TITLE
【G3】H3 見出しの表示がおかしい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#653]
▼不具合報告
https://vws.vektor-inc.co.jp/forums/topic/%e3%80%90g3%e3%80%91h3-%e8%a6%8b%e5%87%ba%e3%81%97%e3%81%ae%e8%a1%a8%e7%a4%ba%e3%81%8c%e3%81%8a%e3%81%8b%e3%81%97%e3%81%84#post-52259

**Comment by kurudrive** [comment]
G3 Pro Unit で修正済み
