### ISSUE TITLE
LTG _ ヘッダーに検索ボックスを追加する

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#656]
虫眼鏡ボタン配置
クリックしたらフォームがオーバレイ（ モバイルナビみたいな。でもCSSで実装。 ）で出てこればOK

headerTo の 電話番号の左

----

Trelloから移動
https://trello.com/c/Ubnt7YLm/701-ltg-%E3%83%98%E3%83%83%E3%83%80%E3%83%BC%E3%81%AB%E6%A4%9C%E7%B4%A2%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B

**Comment by kurudrive** [comment]
ブロックテーマで対応
