### ISSUE TITLE
G3 Pro Unit を有効化すると 投稿詳細ページで分類リストが表示されなくなる？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#664]
https://vws.vektor-inc.co.jp/forums/topic/g3-pro-unit%e3%82%92%e6%9c%89%e5%8a%b9%e5%be%8c%e3%81%ab%e6%8a%95%e7%a8%bf%e8%a8%98%e4%ba%8b%e4%b8%8b%ef%bc%88entry-footer%ef%bc%89%e3%81%ae%e3%80%8c%e3%82%ab%e3%83%86%e3%82%b4%e3%83%aa%e3%80%8d

ローカルでは発生しない。
デモサイト（ https://demo.dev3.biz/lightning-g3-pro/ ）では発生。

`$taxonomies    = VK_Helpers::get_display_taxonomies( get_the_ID(), $args );`

の帰り値が空になる？

**Comment by drill-lancer** [comment]
@kurudrive 
下記部分の条件が Pro Unit を有効化すると false になります。
なにか心当たりはありますか？
https://github.com/vektor-inc/lightning/blob/344bac9bf6813c926dfa84fc7f65a792a9f35d16/_g3/template-parts/entry.php#L57-L93

**Comment by kurudrive** [comment]
@drill-lancer あー、変数名自体がおかしですね...。

根本的にバグというか非表示処理がちゃんと作り込まれてない空気を感じます。

ありがとうございます！

僕の実装漏れだと思うので調整します！

**Comment by drill-lancer** [comment]
https://github.com/vektor-inc/lightning-g3-pro-unit/blob/3c4cb14458bca9767eeaa7a420ffe36f89d8ba96/inc/page-header/package/class-vk-page-header.php#L97
多分これが影響しているかも。

**Comment by kurudrive** [comment]
ですねー。
ありがとうございます！
条件分岐が $is_entry_footer_display じゃないといけなくて $is_entry_header_display 自体の処理が何も入ってないから調整しまっす！
