### ISSUE TITLE
【確認待ち】[ G3 スライダー ] ボタンがない場合の文字の上でリンクが効かない不具合が再び発生しているようなので確認

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#674]
不具合が発生することを確認しました。
<img width="1424" alt="スクリーンショット 2021-06-21 10 38 31" src="https://user-images.githubusercontent.com/5525368/122696130-4e387580-d27d-11eb-904a-cd4221b0120d.png">

▼過去のコミット
https://github.com/vektor-inc/lightning/commit/529f2fcba31ee24ef4a203ad2f45850701a73119

**Comment by kurudrive** [comment]
@drill-lancer @goutetsuguma 
マージしました。ありがとうございました！
