### ISSUE TITLE
【要検討】やっぱり Variety のレイアウトは需要あるかも

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/lightning#676]
フォーラムからの要望：
https://vws.vektor-inc.co.jp/forums/topic/lightning%e3%81%a7%e6%8a%95%e7%a8%bf%e4%b8%80%e8%a6%a7%e3%83%9a%e3%83%bc%e3%82%b8%e3%83%bb%e6%8a%95%e7%a8%bf%e5%80%8b%e5%88%a5%e3%83%9a%e3%83%bc%e3%82%b8%e3%81%a7%e3%81%ae%e3%83%9a%e3%83%bc%e3%82%b8

デモサイト：
https://demo.dev3.biz/variety/

**Comment by kurudrive** [comment]
一覧ページにおいて何の一覧ページなのかのタイトルはちゃんと表示されているべきで、
それをメインコンテナエリアに移動しているのがVarietyでしたが、
需要とメンテナンスコストのバランスを考えると、現状ではそのあたりは個別のカスタマイズの領域で良いという考えのため一旦closeさせていただきます。
