### ISSUE TITLE
【確認待ち】【グループブロック】管理画面で、幅広や全幅で配置すると左側によってしまう 

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#681]
Lightningバージョン: 14.4.2
WPバージョン: 5.7.2
フロント画面では問題ありません。編集画面の幅広や全幅で配置した場合に左に寄ってしまうようでした。

**Comment by kurudrive** [comment]
@goutetsuguma 

多分もう治ってるハズ。

今見た限り発生しなかったので次見て問題なかったらcloseしてください。

**Comment by goutetsuguma** [comment]
@kurudrive 確認遅くなりました！
今LightningもVK Blocks Proもmasterブランチで確認したのですが、編集画面でグループブロックを全幅にすると、やはり左に寄ってしまうようでした。フロント画面では問題ありません。

**Comment by kurudrive** [comment]
@goutetsuguma 多分現行版は問題ないかとー。

![group-inner](https://user-images.githubusercontent.com/3272660/151646530-218c546f-670b-4f49-a80e-cd1d988a847f.png)

**Comment by kurudrive** [comment]
@goutetsuguma 修正しました。
また問題あったら issue 立てるか reopen してください。
