### ISSUE TITLE
【 要PHPUnit テスト修正 】G3の時（G2以外の時） に「ページ属性」から デフォルトテンプレート以外を選択できないようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#684]
プルダウン項目を改変するフックがあるかどうか調査

**Comment by drill-lancer** [comment]
使えそうなフィルターフック

その１：
https://github.com/WordPress/WordPress/blob/0dadbcab6bdbc3039b9946e6fad1cbaaaac80c84/wp-includes/class-wp-theme.php#L1289-L1299

その２：
https://github.com/WordPress/WordPress/blob/0dadbcab6bdbc3039b9946e6fad1cbaaaac80c84/wp-includes/class-wp-theme.php#L1301-L1321

**Comment by kurudrive** [comment]
@drill-lancer 

ありがとうございます。
処理実装してみてください。

**Comment by drill-lancer** [comment]
@kurudrive 
多分これでうまくいくと思います。（その２）を選択しました。

```
function lightning_page_templates( $page_templates ) {
	$generation = get_option( 'lightning_theme_generation' );
	$old_templates = array(
		'_g2/page-lp-builder.php' => __( 'Landing Page for Page Builder ( not recommended )', 'lightning' ),
		'_g2/page-lp.php' => __( 'Landing Page ( not recommended )', 'lightning' ),
		'_g2/page-onecolumn.php' => __( 'No sidebar ( not recommended )', 'lightning' ),
	);
	if ( ! empty( $generation ) && 'g2' !== $generation ) {
		$page_templates = array_diff_assoc( $page_templates, $old_templates );
	}
	return $page_templates;

}
add_filter( 'theme_page_templates', 'lightning_page_templates' );
```

functions.php に追記しようと思いましたがなんか違う気がするのでコードを貼っておきます。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます。

ちなみに現行版の人が 過去のテンプレートを設定している状態で 今回の改修版にアップデートした場合の対応は想定されていますか？
→ G３利用なのにG2の過去のテンプレートを選択しているのでヘッダーやフッターが非表示になってしまうけど、変更する事もできないという状態になったりしないかどうか
→ 設定が古い場合は データベースの更新を促す処理があるはずなので、必要に応じてそのあたりで対応するなど検討

**Comment by drill-lancer** [comment]
@kurudrive 
> G３利用なのにG2の過去のテンプレートを選択しているのでヘッダーやフッターが非表示になってしまうけど、変更する事もできないという状態になったりしないかどうか

この点についてはそのようになっていたので修正しました。

> 設定が古い場合は データベースの更新を促す処理があるはずなので、必要に応じてそのあたりを活用して対応するなど検討

こちらは確か Legacy Notice で判定したあと任意での切り替えを求めるだったような気がします。
石川さんの気が変わって強制変更ということならばそのように対応します。

**Comment by kurudrive** [comment]
> Legacy Notice で判定したあと任意での切り替えを求める形だったような気がします。
> 石川さんの気が変わって強制変更ということならばそのように対応します。

G2 の場合は実際に意図して子テーマでカスタマイズして使っているケースが多いためその判断ですが、G3ではそもそもそのテンプレートを選択すると正常に表示されないので、データベースの更新を促した上で書き換えれば良いと思うのですが、まぁでもマイナス面もあるし無理に実装しないといけない機能でもないので現状でOKです。

ありがとうございます。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました！
