### ISSUE TITLE
スマホで閲覧時、投稿のタイトルが短いと一覧画面で崩れてしまう

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#686]
`.vk_posts` の display: flex;　をblockにすると治りますが、`.vk_posts`いろいろなところに影響がありそうなので、表示確認しながら作業するかんじでしょうか

▼関連するフォーラム
https://trello.com/c/a5H3oJv0/3330-%E3%82%B9%E3%83%9E%E3%83%9B%E3%81%A7%E3%82%A2%E3%82%A4%E3%82%AD%E3%83%A3%E3%83%83%E3%83%81%E7%94%BB%E5%83%8F%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%81%BE%E3%81%9B%E3%82%93

▼症状が確認できるでもサイト
https://demo.dev3.biz/lightning-g3/information/

**Comment by kurudrive** [comment]
あら...

**Comment by kurudrive** [comment]
@goutetsuguma 
VK Posts の 他のレイアウトで不具合出ないか気をつけつつ一度やってみてー。

**Comment by goutetsuguma** [comment]
【メモ】このCSSを記載すればOKです。

```
/* 標準デザインの投稿リスト */
.post-list.vk_posts{
display:block;
}
```

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/lightning/commit/93c0a5974991bfe531cf4dad25c382a9ccbdaa83

修正済み close
