### ISSUE TITLE
【確認待ち】幅広指定をするとスマホ表示で左に寄る

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/lightning#702]
WordPress 5.8
Lightning 14.5.5

WordPress標準のブロック（カバー、見出し、画像、テーブル、プルクオートを確認しました）で、幅広指定をすると、スマホで見たときに左に寄って表示されます。

テストページ
https://demo-vk.chiakikouno.com/habahiro/

スマホ表示では .alignwide のクラスをオフにすると左右均等余白となるようでした。

**Comment by ChiakiKouno** [comment]
お休みの日に書いてごめんなさい。[フォーラムで同時に上がっているケース](https://vws.vektor-inc.co.jp/forums/topic/%e3%82%b9%e3%83%9e%e3%83%9b%e8%a1%a8%e7%a4%ba%e3%81%ab%e3%81%99%e3%82%8b%e3%81%a8%e3%83%ac%e3%82%a4%e3%82%a2%e3%82%a6%e3%83%88%e3%81%8c%e5%b4%a9%e3%82%8c%e3%81%be%e3%81%99)と同じ思われます。

**Comment by kurudrive** [comment]
@ChiakiKouno ありがとうございます。
14.5.6にて修正しましたー。

**Comment by ChiakiKouno** [comment]
早速のご対応誠にありがとうございます！14.5.6にて確認できました。バッチリでした！
