### ISSUE TITLE
管理メールアドレスが vektor-inc を含んでいたら警告を出すようにする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#714]

**Comment by drill-lancer** [comment]
とりあえず、管理者メールアドレスは
```get_option( 'admin_email');```
で取得できるようです。

---

そもそもメールアドレスの変更が必要なのはデモデータなので
デモデータに添付するプラグインを作ったほうが良さそうな気がします。

【中身】
- メールアドレスの警告
- 追加で必須なプラグインをお知らせ & インストール or 購入の最速
