### ISSUE TITLE
Lightningの構造調査

### ISSUE THREAD

**Issue by miminari** [vektor-inc/lightning#725]
余白・マージンその他のグローバル変数等について整理のための現状調査をこのIssueにまとめます

**Comment by miminari** [comment]
## Global Navi

### PC View

- .global-nav-description の line-height が14pxになってる　1.4 では
- メニュー文字長めちゃくちゃ長いときにバグるので、制限かけたほうがいい
-  .global-nav-name のウェイト指定がstrong由来になっている
- #724 
-

**Comment by miminari** [comment]
## Color

### Primary

```
--vk-color-primary: #3461AC;
--vk-color-primary-vivid: #396ABD;
--vk-color-primary-dark: #294d89;
```
primary より 0.8 / 1.1 brighten がかかっている

**Comment by kurudrive** [comment]
ブロックテーマ開発にリソースを回すため close
