### ISSUE TITLE
vk-cols--reverse とかの便利なCSSがわかるリストをつくりたい

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/lightning#735]
開発者ドキュメント？
スタイルガイド？
notionの公開ページとかで編集しやすくする？

など、そうだんしたいです。

**Comment by kurudrive** [comment]
解説しましょう。これなぜ作ってないかというと、そもそも class 名を手入力するというのがcoolじゃなくて本来GUIでできるべきだと思うんですよねー。
なのでその実装ができればと思いつつ、全く目処が立ってない以上作る方が良いか...とか思う今日この頃...。

**Comment by ChiakiKouno** [comment]
VK パターンライブラリが公開となって気になっていた点が解消さると思いますのでクローズにしたいと思います。
ありがとうございました！
