### ISSUE TITLE
Undefined array key "color_key"

### ISSUE THREAD

**Issue by oshin3** [vektor-inc/lightning#739]
テーマが14.11.0に自動更新されてから以下のエラーが表示されるようになってしまい、もしテーマ側に問題があるようでしたら修正していただけますと助かります。こちら側のミス等でしたら申し訳ございませんがどうぞよろしくお願いいたします。
Warning: Undefined array key "color_key" in /home/********/public_html/************.com/wp-content/themes/lightning/_g3/inc/vk-color-palette-manager/config.php on line 27

**Comment by kurudrive** [comment]
@oshin3 ご報告ありがとうございます。
14.11.1 にて修正いたしましたのでアップデートの上ご確認ください。

**Comment by oshin3** [comment]
@kurudrive バージョン14.11.1 にアップデートし無事解決いたしました。早速のご対応ありがとうございました。
