### ISSUE TITLE
サンプルデータダウンロードページのリンク切れ

### ISSUE THREAD

**Issue by ironsand** [vektor-inc/lightning#746]
テーマそのものではなくサイトの不具合なのですが
他に適した問い合わせ先が見つかりませんでしたのでこちらに投稿させていただきます。

【Lightning クイックスタート】
https://lightning.nagoya/ja/setting/quick-start-sp

上記ページの【1. デモサイトのデータをダウンロード】をクリックすると以下のエラーが出てダウンロードできませんでした。
> Invalid File Type (/home/vs2/lightning.nagoya/public_html/wp-content/uploads/download-manager-files/1605004170wpdm_ltg-demo.wpress)!

また【サンプルデータを手動でインポートする方法】も同様のエラーになります。
https://lightning.nagoya/ja/setting/quick-start-sp/corporate_inport

あとこれはエラーではありませんがページURLが inport になってしまっています。

一時的にダウンしてるだけかもしれませんが修正よろしくおねがいします。

**Comment by kurudrive** [comment]
下記よりよろしくお願いいたします。
https://lightning.vektor-inc.co.jp/quick-start/
