### ISSUE TITLE
【対応済・確認待】Warning: Attempt to read property "ID" on null

### ISSUE THREAD

**Issue by oshin3** [vektor-inc/lightning#757]
こちらのエラーはPHP8.0環境において固定ページのクイック編集ページで表示されるものです。フロントエンドで表示されるものではないので大きな問題ではございませんが、カレンダープラグイン「The Events Calendar」を入れた際にはプラグイン関連の設定ページの全てに表示されてしまうこともあったため、念のためご報告させていただきます。修正のご検討のほどどうぞよろしくお願いいたします。
`Warning: Attempt to read property "ID" on null in /home/********/public_html/******************.com/wp-content/themes/lightning/inc/old-page-template.php on line 13`

**Comment by kurudrive** [comment]
ご報告ありがとうございます。
本件こちらで対応済みなので改善されているかと思います。
https://github.com/vektor-inc/lightning/commit/127f6e264554581998a46c776caf7213f0f7056c

よろしくお願いいたします。

**Comment by oshin3** [comment]
ご修正いただきありがとうございます。
エラーが出ないことを確認いたしました。
今後ともよろしくお願いします。

**Comment by kurudrive** [comment]
@oshin3 対応遅くなり失礼しました。
こちらこそ今後ともLightningをよろしくお願いいたします。
