### ISSUE TITLE
フッターメニューについて

### ISSUE THREAD

**Issue by kanizo1091** [vektor-inc/lightning#767]
お世話になります。
Lightning G3を無料のテーマLightningバージョン: 14.13.2使っているのですが、PC用のフッターメニューの上下の間隔が非常に狭くクリックしにくい状態になっています。
これは設定か何かで改善するんでしょうか
![フッターメニュー](https://user-images.githubusercontent.com/68579618/144173253-552ac85c-225e-4364-b499-b53c5475dfe8.jpg)
？

**Comment by kurudrive** [comment]
@kanizo1091 フッターメニューはあくまでサブコンテンツを配置する想定です。
たくさん配置したい場合はフッターウィジェットエリアにカスタムメニューウィジェットを配置するなどして運用ください。

https://training.vektor-inc.co.jp/courses/lightning-basic-settings/lessons/lightning-navigation-setting/

**Comment by kanizo1091** [comment]
分かりました！
ありがとうございます。
