### ISSUE TITLE
VK blocksプラグインアップデートエラー後

### ISSUE THREAD

**Issue by taki424** [vektor-inc/lightning#773]
Lightningをいつもご利用させていただいてありがとうございます。

プラグインアップデートですが、
VK blocksのアップデートはいつもひっかかり、1回で更新成功できることが珍しいです。

で、本日もプラグインアップデートをしたのですが、VK blocksでまた更新に失敗しました。
そこまではいいのですが、
その後、固定ページが更新できなくなってしまいました。
（バックアップを取っていません。）

固定ページの更新ボタンを押すと、
なぜか投稿一覧ページに遷移します。

どなたか解決方法をご教授いただければ幸いです。
よろしくお願いいたします。

**Comment by kurudrive** [comment]
こちらで再現しないので以下から該当サイトのログイン情報を送付いただくか、

https://vws.vektor-inc.co.jp/contact/inquiry2

all in one wp migration で出力したデータをどこかにアップしてダウンロードURLをご連絡いただければ、
直接確認させていただきます。

**Comment by taki424** [comment]
ありがとうございます。ダウンロードURL送ります。少々お待ちください。

**Comment by taki424** [comment]
http://kawasaki.f-table.jp/wp-content/ai1wm-backups/kawasaki.f-table.jp-20220112-015438-5pzt7e.wpress
です。よろしくお願いいたします。

**Comment by kurudrive** [comment]
@taki424 とりあえず解決なによりです。

**Comment by taki424** [comment]
そう言っていただけると感謝です。ありがとうございます。
