### ISSUE TITLE
【確認待ち】見出しスタイルのプレビューが壊れている

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/lightning#774]
特に「括弧 黒」がおかしいように思います。
後括弧が前括弧とくっついてしまっているのは
.block-editor-block-list__layout .block-editor-block-list__block:after の  left: に  0 が設定されているため（これはWordPress側で設定されているのかも）
Lightningで常にborder-topに線が入ってしまうのは、
```
.editor-styles-wrapper .entry-title--post-type--page, .editor-styles-wrapper h2 {
    border-top: 2px solid var(--vk-color-primary);
}
```
の指定が効いているように思います。
以下、画面キャプチャです。

# Lightning
![image](https://user-images.githubusercontent.com/1535140/149463154-d855d1e8-cdde-45ea-8644-fdce5a56c8f7.png)
 
# Katawara
![image](https://user-images.githubusercontent.com/1535140/149463243-b50a58cc-a82c-4829-8586-e7599a58cc62.png)

**Comment by kurudrive** [comment]
@mthaichi 確認・調整するっす（・ｗ・；

**Comment by kurudrive** [comment]
あぁ、これは VK Blocks の見出しスタイルがあたってない感じですねぇ...（＝ｗ＝

**Comment by mthaichi** [comment]
@kurudrive なるほど

https://github.com/vektor-inc/vk-blocks-pro/pull/945

これと関連があるかなと思い、これを取り込んでみても駄目だったんですよね。
石川さんの方で察しがついてますか。もしついてなければ、こっちで再調査します。

**Comment by kurudrive** [comment]
@mthaichi たぶん

https://qiita.com/TetsuakiHamano/items/88861e3b78a5009994e5

あたりが関係するのかなと思うのですが、現状 うーむ、という感じで調査中っす。

**Comment by kurudrive** [comment]
@mthaichi 対応しましたんー
