### ISSUE TITLE
【お知らせ記事待ち】Font Awesomeアイコンリストからそのままコピーするとアイコンが表示できない

### ISSUE THREAD

**Issue by oshin3** [vektor-inc/lightning#788]
Font Awesome6.0.0の正式リリースに伴い、「Font Awesomeアイコンリスト」（ https://fontawesome.com/icons?d=gallery&m=free ）を選択して検索しそのままコードをコピーして貼り付けると、Font Awesome5ではなくFont Awesome6を指定してしまうことになり「□」としか表示されない現象が発生しています。
自分でFont Awesome5系を選択し直せばよいのですが、初心者の方が迷う可能性があると思い、念のためご報告しておきます。
なお5系の検索URLは https://fontawesome.com/v5/search?m=free となっている模様です。

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/font-awesome-versions/commit/8202ed1fa95548bb0e7273baa7027f4301fe238b

**Comment by kurudrive** [comment]
@oshin3 おまたせいたしました。

Lightning 14.18.0 + VK Blocks 1.27.7 で Font Awesome 6 に対応しました。
（ 外観 > カスタマイズ > Lightning Font Awesome でバージョン切り替えが必要）

ブロックからのアイコンリストのリンクも選択中のバージョンで切り替わるようになっていますのでご確認ください。

**Comment by kaorock72** [comment]
お知らせ公開しましたのでクローズいたします
https://www.vektor-inc.co.jp/product-update/support-font-awesome-6/
