### ISSUE TITLE
VK PR_broksのスマホ表示

### ISSUE THREAD

**Issue by shin3w** [vektor-inc/Lightning#81]
VK PR_broksをスマホで表示すると、以前は全て横に並んで表示されたのですが、プラグインとテーマを更新してからは縦表示になってしまいます。
この現象はスマホを横にしても起こるため、横がすかすかに空いてしまい、説明文を入れていない私のようなサイトでは見映えが悪いです。
もとに戻すか、選択できるようにしていただけると嬉しいです。

**Comment by kurudrive** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/commit/aebbcacbd7e84a6933d5864c134d7aaaa41e4098

**Comment by shin3w** [comment]
ありがとうございます。

**Comment by kurudrive** [comment]
本件 画面が狭い場合は通常横並びで見栄えを損なわない方がレアケースかと思います。
ExUnitは多機能で収拾がつかず、需要の少ない部分の機能実装は実装コストもメンテナンスコストも限界なので、恐れ入りますが必要に応じて個別にCSS指定にて対応願います。
