### ISSUE TITLE
WordPress6.0でUnitControlコンポーネントにcssが当たっている

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/lightning#832]
WordPress6.0でUnitControlコンポーネントにcssが当たっている
![6 0](https://user-images.githubusercontent.com/42362903/168532570-ff398f4f-0edd-4ca8-a38f-4364b1c76e99.png)

lightning/_g3/assets/css/editor.css

**Comment by shimotmk** [comment]
画像ブロックのInsert from URLも幅が狭い
![input](https://user-images.githubusercontent.com/42362903/170629132-e1dffd5d-8daa-4414-bbb9-b13e648677ac.png)

**Comment by kurudrive** [comment]
@shimotmk 報告ありがとうございました。
修正した（次回リリース）ので close します。
