### ISSUE TITLE
編集画面で区切り線が見えない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/lightning#845]
テーマが Lightning のときだけ発生します
フロントでは見えます
ブラウザは Firefox とChrome で確認しました
WordPress は5.9 と 6.0  で確認しました
※ Lightning Pro では発生しません

**Comment by mtdkei** [comment]
現在確認したところ、区切り線が見えているようだったのでCloseします。
@YukinobuAsakawa さん、ありがとうございました。
