### ISSUE TITLE
Tree shaking を有効化時、見出し/装飾無し/中央寄せ の見出しブロックを配置すると、他の見出しブロックのスタイルが付かなくなる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#851]
Tree shaking を有効化時、見出し/装飾無し/中央寄せ の見出しブロックを配置すると、他の見出しブロックのスタイルが付かなくなる。（見出し/装飾無し/中央寄せの見出しブロックの配置を左寄せor右寄せor削除すると、他の見出しブロックのスタイルがつくようになる。）

▼デモサイトで確かめられます。
https://demo.dev3.biz/lightning-g3-pro/heading-test/

インラインで出力するときに、なにかおかしくなるのかな、、、？
調査をよろしくお願いいたしますmm
【追記】[この修正とは関係ないかな、、？](https://github.com/vektor-inc/vk-blocks-pro/pull/1263)
`has-text-align-center is-style-vk-heading-plain`　

---
▼報告のあったフォーラム
https://vws.vektor-inc.co.jp/forums/topic/%e8%a6%8b%e5%87%ba%e3%81%97%e3%81%ae%e8%a3%85%e9%a3%be%e3%81%8c%e5%8f%8d%e6%98%a0%e3%81%95%e3%82%8c%e3%81%aa%e3%81%84

**Comment by drill-lancer** [comment]
`.is-style-vk-heading-plain:not(.has-text-align-center{text-align:left}`
みたいな構文を見つけたのでこれが原因かも・・・

**Comment by kurudrive** [comment]
えーっと、tree shaking が古いから `.is-style-vk-heading-plain:not(.has-text-align-center{text-align:left}` の書き方に対応してないっぽいな...。

**Comment by kurudrive** [comment]
@drill-lancer Tree Shaking が
not(.has-text-align-center,.has-text-align-right) で誤動作しないように元のライブラリが改善されてるか見に行くなどして、修正よろしくお願いいたします。

**Comment by drill-lancer** [comment]
マージされたので Close します。

**Comment by kurudrive** [comment]
@drill-lancer |￣￣￣￣────￣￣￣￣） close がちょっと早いでー。
