### ISSUE TITLE
Lightningでデフォルトのカラーパレット、カスタムカラーパレットが表示されていない

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/lightning#857]
Lightning 14.22.1では正常
Lightning 14.22.2では
キーカラー、キーカラー明、キーカラー暗は出ている、それ以外が出ていない

これが関連しているかもしれない
https://github.com/vektor-inc/lightning/pull/854

### 14.22.1
<img width="583" alt="14 22 2" src="https://user-images.githubusercontent.com/42362903/174009812-6b69d12b-92d1-46c5-8ecd-6b1eb9f12e72.png">

### 14.22.2

<img width="581" alt="14 22 1" src="https://user-images.githubusercontent.com/42362903/174009794-1a7eb8ce-4478-44e5-8b1c-b56ba6770eb4.png">

**Comment by drill-lancer** [comment]
修正されたようなので Close
