### ISSUE TITLE
テーブルが中央揃えにならない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/lightning#885]
テーブルブロックの配置でが「中央揃え」が効かないように見えます
編集画面では正常、フロントのみです
Pro版では、編集画面、フロントとも正常です

![table](https://user-images.githubusercontent.com/4631838/183016570-02f5af7d-7637-4ffa-aacd-c7bc794d2bb5.jpg)

**Comment by kurudrive** [comment]
@doshimaf ちなみに担当が複数アサインされている場合はやりたい人が先にやればOKデス。
本件に限らず不明点はお気軽にお問い合わせをー。

**Comment by doshimaf** [comment]
@kurudrive 
承知しました。

**Comment by sysbird** [comment]
リリース済につきクローズします、ありがとうございました！
