### ISSUE TITLE
Outerブロックでセクションベースありでレイアウトが壊れる例がある

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#889]
https://demo.dev3.biz/lightning-g3-pro/main-section-base-off/
▼セクションベースありの場合に中のコンテンツが狭くなって崩れる
https://demo.dev3.biz/lightning-g3-pro/main-section-base-on/
余白（左右）を「コンテンツエリアに合わせる」 にした場合に、中のコンテンツの左右に大きな余白ができてしまう。
（セクションベース有効の時は全幅はウィンドウサイズではなくセクションベースに吸着が正しい仕様）

Outerを全幅で「コンテンツエリアに合わせる」にした場合に以下のCSSがつくので、セクションベースありにした場合は、padding-left とpadding-right を0にすると治る

```
.vk_outer-width-full.vk_outer-paddingLR-none {
    padding-left: calc(50vw - 50%);
    padding-right: calc(50vw - 50%);
}
```

![セクションベースありで全幅のカバーブロック・Outer-ブロックを配置-いつか削除-Lightning-×-ExUnit-日本語デモ](https://user-images.githubusercontent.com/5525368/188099141-daae0417-beb8-451a-ae0c-c34d5988a834.png)

**Comment by kurudrive** [comment]
@goutetsuguma ありがとうございました！
