### ISSUE TITLE
【確認待ち】BBP拡張で存在しないキー名を指定された警告が出る

### ISSUE THREAD

**Issue by TokyoJump** [vektor-inc/lightning#893]
Buddypress と bbpress の両方をインストールしたPHP8環境で、ホームページをBuddyPressのユーザー個人ページに設定していると、そこにアクセスした場合に次のような警告文が出てきてしまいます。

Warning: Undefined array key "bbp_user" in /mysite.com/wp-content/themes/lightning/_g3/plugin-support/bbpress/functions-bbpress.php on line 68

Warning: Undefined array key "bbp_user" in /mysite.com/wp-content/themes/lightning/_g3/plugin-support/bbpress/functions-bbpress.php on line 70

Warning: Undefined variable $display_name in /mysite.com/wp-content/themes/lightning/_g3/plugin-support/bbpress/functions-bbpress.php on line 74

エラー状況としては、「lightning/_g3/plugin-support/bbpress/functions-bbpress.php」の関数「function lightning_bbp_get_displayed_user_field」が「bbp_get_displayed_user_field」にフックされている所から誤作動を起こしているようです。なので、113行目の「$value = lightning_the_bbp_display_name();」をコメントアウトするとエラーは止まります。

恐らくタイミングや使い方による所が大きく、警告文が出るのみで表示等に異常は出ていないので、詳しい原理は紐解かなくて良いと思いますが、構文的な問題として修正の必要があると思慮します。

「Undefined array key」はPHP8より前のPHPではエラー警告にはならない物だったと記憶しているので、コードが古いのだと思います。PHP8からは配列参照には「array_key_exists()」や「isset()」で値が指定されていない時の回避策を入れておくことが推奨されているようなので、そのように更新されると助かります。

私は現状ではクールな対処法ではないかもしれませんが、「lightning/_g3/plugin-support/bbpress/functions-bbpress.php」の66行目から先をとりあえず次のようにして変更してエラーを回避しています。

function lightning_the_bbp_display_name() {
	global $wp_query;
	if(isset($wp_query->query['bbp_user'])){
    	$users = get_users( array( 'search' => $wp_query->query['bbp_user'] ) );
		foreach ( $users as $user ) {
			if ( $user->data->user_login === $wp_query->query['bbp_user'] ) {
				$display_name = $user->data->display_name;
			}
		}
		return esc_html( $display_name );
	}
}

いつも素敵なテーマを有難うございます。修正をお待ちしています。

**Comment by kurudrive** [comment]
@TokyoJump 該当箇所修正いたしましたのでアップデートの上ご確認くださいー。
