### ISSUE TITLE
【機能追加要望】ヘッダーロゴ画像の設定で、PCとモバイルでmax-height が設定できるとうれしいです

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#897]
ロゴ画像を入れた時に、ちょっと大きいなと思うことがあります。
ヘッダーロゴ画像の設定で、PCとモバイルでmax-height が設定できるとうれしいです

こんな感じのイメージです。
デフォルト値は現在の数値が入るイメージです。

【追記です】
▼文言修正
「ロゴの高さ」→「ロゴの最大の高さ」

![カスタマイズ-サンプル工務店-職人が手がける、ワンランク上の家](https://user-images.githubusercontent.com/5525368/193980652-aac063e4-3db9-48aa-bd77-dde9305b3bfa.jpg)

**Comment by mtdkei** [comment]
マージされましたのでCloseします。
