### ISSUE TITLE
Lightning 単体だと Swiper が正常に動作しない空気を感じる...

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#898]
https://wordpress.org/support/topic/lightning%e3%81%ae%e3%82%b9%e3%83%a9%e3%82%a4%e3%83%80%e3%83%bc%e3%81%ab%e9%96%a2%e3%81%99%e3%82%8b%e3%83%90%e3%82%b0/#post-16082647

**Comment by kurudrive** [comment]
@drill-lancer Swiper 関連で以前調整したときの影響かな？
火曜日以降に確認よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
Swiper は単体でもしっかりと読み込まれています。
気になるのはデザインスキンの CSS を読み込んだ後に Swiper の CSS が読み込まれていますが仕様ですか？

**Comment by drill-lancer** [comment]
@kurudrive 
Swiper のバージョンは
VK Blocks Proが有効な場合: 6.8.0
Lightning 単体の場合: 8.0.7

6.8.0 から 8.0.7 で変更があったっぽいのでそれが原因かもしれません。
6 -> 7: https://swiperjs.com/migration-guide
7 -> 8:; https://swiperjs.com/migration-guide-v8

**Comment by kurudrive** [comment]
@drill-lancer 確認ありがとうございました！
