### ISSUE TITLE
WP6.1のエディター画面において、コアのボタンブロックのスタイルが反映されない。

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/lightning#915]
件名の通りです。CSSの読み込み順が変わったからでしょうか。
当方の環境の問題でしたらすみません。気づいたので、取り急ぎあげておきます。

<img width="247" alt="image" src="https://user-images.githubusercontent.com/1535140/199630952-2665b848-4893-4ceb-8e3b-76d6f0b3fe38.png">

上がコアのボタン、下がVKボタン

**Comment by kurudrive** [comment]
@mthaichi ありがとうございます！修正しました！

**Comment by kurudrive** [comment]
@mthaichi ありがとうございます！修正しました！
