### ISSUE TITLE
PHPUnit で theme.json のファイル名変更処理が GitHub Action 上で Permission denied で通らない

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning#933]
ローカル環境では PHPUnit はすべて通るが、GitHub Action 上で Permission denied で通らない

https://github.com/vektor-inc/lightning/actions/runs/3509281829/jobs/5878271865

**Comment by kurudrive** [comment]
@mthaichi ありがとうございます。
一応トライはしたのですがうまくいかず…
https://github.com/vektor-inc/lightning/tree/fix/githuvactions/theme.json

**Comment by mthaichi** [comment]
@kurudrive その後いかがでしょう。
```
       chmod +x ./inc/class-ltg-theme-json-activator.php
       chmod +x ./tests/test-ltg_theme_json_activator.php
       chmod +x ./_theme.json
       chmod +x ./theme.json
       chmod +x ./
 ```
+x で実行権限をつけてるのは意味ありますでしょうか。
書き込み属性をつけたいので、

chmod 777 ./  
chmod 777 ./_theme.json  

をやってみてください。（私がやってもいいんですが時間がなかなかとれず・・・）

**Comment by kurudrive** [comment]
@mthaichi ありがとうございました！
