### ISSUE TITLE
要文言修正：ログイン中モバイルナビ表示、「ここはウィジェットエリアです…」モバイルナビ上部ではなく下部に

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/lightning#949]
WordPress 6.1 
Lightningバージョン: 15.2.1 で確認しました。

## 現状
<img width="1064" alt="Screenshot 2022-12-15 at 1 19 24 PM" src="https://user-images.githubusercontent.com/43702482/207780209-67615eca-cce5-400a-9b3b-bf333f990c76.png">

> ここはウィジェットエリアです。
>  [外観 > カスタマイズ ] ページ -> 「ウィジェット」 パネル -> 「モバイルナビ上部」 パネルから設定できます。
> 
> * このメッセージは編集権限のあるユーザーにのみ表示されています。

## 下記に要修正

誤：「モバイルナビ上部」 パネルから設定できます。
正：「モバイルナビ下部」 パネルから設定できます。
※`上部`になっているのを`下部`に。

**Comment by kurudrive** [comment]
@ChiakiKouno 修正しました！
https://translate.wordpress.org/projects/wp-themes/lightning/ja/default/?filters%5Bterm%5D=Mobile+Nav+Bottom&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by ChiakiKouno** [comment]
@kurudrive ありがとうざいます！翻訳データを更新して修正されていることが確認できました！
（は！そうか翻訳データの方だけで大丈夫な箇所だったんですね！お手数かけました！）
