### ISSUE TITLE
【相談】KUSANAGIの環境でTree Shakingを有効化すると一部のCSSが読み込まれなくなるかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/lightning#979]
修正できるのかわかりませんがissueをたてておきます。

> Lightning 15.2.4まではKUSANAGI環境でもTree Shakingが機能していたので

↑何かヒントになれば。。。

https://vws.vektor-inc.co.jp/forums/topic/lightning-15-3-0%e4%bb%a5%e9%99%8d%e3%81%a7tree-shaking%e3%82%92%e6%9c%89%e5%8a%b9%e5%8c%96%e3%81%99%e3%82%8b%e3%81%a8%e3%82%b5%e3%82%a4%e3%83%88%e5%85%a8%e4%bd%93%e3%81%ae%e8%a1%a8%e7%a4%ba%e3%81%8c

Assigneesにはリックさんと石川さんをインさせていただきました🙇‍♀️

**Comment by drill-lancer** [comment]
一応対応したので Close
