### ISSUE TITLE
リストのスタイルや段落ブロック背景色が初期値に！？

### ISSUE THREAD

**Issue by toshi2303** [vektor-inc/lightning#996]
2023年3月13日AM11時の時点、最新のWordPressバージョン、最新のLightningバージョン（無料版）。旧バージョン時に公開済みのページを編集しようと開くと、リストブロックのスタイルや、段落ブロックの背景色などが、すべて初期値になってしまう…。その都度、装飾をやり直さないといけないのでしょうか、、、

**Comment by kurudrive** [comment]
これは WordPress 本体の問題で WordPress 6.2 で解消されます。
